//! Round-trip property tests (Epic 23.1).
//!
//! Verifies that `serialize(build(…))` → `Platform::with_all_profiles().parse(bytes)` preserves the
//! observable message properties: type, Pruefidentifikator, release code.
//!
//! The test corpus is generated by `proptest`, which tries many random
//! input combinations and shrinks failures automatically.

// All *_RELEASES constants and top-level imports are used exclusively inside
// feature-gated test modules; they carry individual #[allow(dead_code)] /
// #[allow(unused_imports)] annotations below.

// Items used via `use super::*` inside feature-gated test modules.
#[allow(unused_imports)]
use edi_energy::{
    AnyMessage, EdiEnergyMessage, MessageType, ObjectType, Platform, Pruefidentifikator, Release,
};

// ── Helpers ───────────────────────────────────────────────────────────────────

/// Known UTILMD release codes used in the German energy market.
///
/// Classic 5.5.x releases are **parse-capable** (the EDIFACT wire format is
/// the same) but have **no registered profiles** — `validate()` returns
/// `Error::ProfileNotFound` for them.  They are included here to verify that
/// the serialize→parse round-trip preserves the wire release code even when
/// no validation profile exists.
#[cfg(feature = "utilmd")]
const UTILMD_RELEASES: &[&str] = &[
    "5.5.3a", "5.5.4a", "5.5.5a", "5.5.6a", "5.5.7a", "5.5.8a", "S2.1", "S2.2",
];

/// Known MSCONS release codes (wire assoc_codes from registered profiles).
#[cfg(feature = "mscons")]
const MSCONS_RELEASES: &[&str] = &["2.4c", "2.5"];

/// Known APERAK release codes.
#[cfg(feature = "aperak")]
const APERAK_RELEASES: &[&str] = &["2.0a", "2.0b", "2.0c", "2.1a", "2.1i", "2.2"];

/// Known CONTRL release codes.
#[cfg(feature = "contrl")]
const CONTRL_RELEASES: &[&str] = &["1.0a", "1.0b", "2.0a", "2.0b"];

// ── UTILMD round-trip ─────────────────────────────────────────────────────────

#[cfg(feature = "utilmd")]
mod utilmd_roundtrip {
    use super::*;
    use edi_energy::builders::UtilmdBuilder;
    use proptest::prelude::*;

    proptest! {
        /// For any valid Pruefidentifikator in 10_000–99_999, a UTILMD message
        /// built and serialized must re-parse to the same type and same PID.
        #[test]
        fn utilmd_pid_survives_roundtrip(
            pid_u32 in 10_000u32..=99_999,
            release_idx in 0usize..UTILMD_RELEASES.len(),
            sender in "[0-9]{13}",
            receiver in "[0-9]{13}",
        ) {
            let pid = Pruefidentifikator::new(pid_u32).unwrap();
            let release = Release::new(UTILMD_RELEASES[release_idx]);

            let bytes = UtilmdBuilder::new(release.clone())
                .pruefidentifikator(pid)
                .sender(sender.as_str())
                .receiver(receiver.as_str())
                .serialize()
                .expect("serialize must not fail for valid inputs");

            let reparsed = Platform::with_all_profiles().parse(&bytes)
                .expect("serialized UTILMD must re-parse without errors");

            prop_assert_eq!(reparsed.try_message_type(), Some(MessageType::Utilmd));

            let reparsed_pid = reparsed.detect_pruefidentifikator()
                .expect("re-parsed UTILMD must carry a Pruefidentifikator");
            prop_assert_eq!(reparsed_pid.as_u32(), pid_u32);

            let reparsed_release = reparsed.detect_release()
                .expect("re-parsed UTILMD must carry a release code");
            prop_assert_eq!(reparsed_release.as_str(), release.as_str());
        }

        /// Message reference is preserved across a round-trip.
        #[test]
        fn utilmd_message_ref_survives_roundtrip(
            msg_ref in "[A-Z0-9]{1,14}",
        ) {
            use edi_energy::builders::UtilmdBuilder;
            use edi_energy::AnyMessage;
            let pid = Pruefidentifikator::new(11001).unwrap();
            let bytes = UtilmdBuilder::new(Release::new("5.5.3a"))
                .pruefidentifikator(pid)
                .sender("4012345000023")
                .receiver("9900357000004")
                .message_ref(msg_ref.as_str())
                .serialize()
                .expect("serialize must not fail");

            let reparsed = Platform::with_all_profiles().parse(&bytes).expect("must re-parse");
            prop_assert_eq!(reparsed.try_message_type(), Some(MessageType::Utilmd));

            // message_ref() carries the UNH reference number — downcast to typed message
            if let AnyMessage::Utilmd(utilmd) = reparsed {
                prop_assert_eq!(utilmd.message_ref(), msg_ref.as_str());
            } else {
                panic!("expected Utilmd variant");
            }
        }
    }
}

// ── MSCONS round-trip ─────────────────────────────────────────────────────────

#[cfg(feature = "mscons")]
mod mscons_roundtrip {
    use super::*;
    use edi_energy::builders::MsconsBuilder;
    use proptest::prelude::*;

    proptest! {
        /// For any valid MSCONS PID, a built-and-serialized message must
        /// re-parse with the same type and PID.
        #[test]
        fn mscons_pid_survives_roundtrip(
            pid_u32 in 10_000u32..=99_999,
            release_idx in 0usize..MSCONS_RELEASES.len(),
        ) {
            let pid = Pruefidentifikator::new(pid_u32).unwrap();
            let release = Release::new(MSCONS_RELEASES[release_idx]);

            let bytes = MsconsBuilder::new(release.clone())
                .pruefidentifikator(pid)
                .sender("4012345000023")
                .receiver("9900357000004")
                .serialize()
                .expect("serialize must not fail for valid inputs");

            let reparsed = Platform::with_all_profiles().parse(&bytes)
                .expect("serialized MSCONS must re-parse without errors");

            prop_assert_eq!(reparsed.try_message_type(), Some(MessageType::Mscons));

            let reparsed_pid = reparsed.detect_pruefidentifikator()
                .expect("re-parsed MSCONS must carry a Pruefidentifikator");
            prop_assert_eq!(reparsed_pid.as_u32(), pid_u32);

            let reparsed_release = reparsed.detect_release().expect("must have release");
            prop_assert_eq!(reparsed_release.as_str(), release.as_str());

            // validate() must not panic. Bare messages (no UNB envelope)
            // always return a Parse error; registered PIDs may return Ok or
            // ProfileNotFound. Any of these outcomes are acceptable here.
            let _validation_result = reparsed.validate();
        }

        /// Metering point data survives serialization: location IDs and OBIS
        /// codes must appear verbatim in the serialized bytes.
        #[test]
        fn mscons_metering_point_data_in_bytes(
            malo_id in "DE[0-9]{11}",
            obis in "[0-9]{1,2}-[0-9]{1,2}:[1-9][0-9]?\\.[0-9]{1,2}\\.[0-9]{1,2}",
            quantity in "[0-9]{1,8}",
        ) {
            let bytes = MsconsBuilder::new(Release::new("2.4c"))
                .pruefidentifikator(Pruefidentifikator::new(13003).unwrap())
                .sender("4012345000023")
                .receiver("9900357000004")
                .metering_point(malo_id.as_str())
                .obis(rubo4e::identifiers::ObisCode::new(obis.as_str()).expect("proptest regex ensures valid OBIS"))
                .quantity("220", quantity.as_str(), "KWH")
                .done()
                .serialize()
                .expect("serialize must not fail");

            // malo_id and obis must be present in the output
            let output = String::from_utf8(bytes).expect("serialized output must be valid UTF-8");
            prop_assert!(
                output.contains(malo_id.as_str()),
                "malo_id {malo_id} not found in output"
            );
        }
    }
}

// ── APERAK round-trip ─────────────────────────────────────────────────────────

#[cfg(feature = "aperak")]
mod aperak_roundtrip {
    use super::*;
    use edi_energy::builders::AperakBuilder;
    use proptest::prelude::*;

    proptest! {
        /// A built APERAK must re-parse to an APERAK message.
        #[test]
        fn aperak_pid_survives_roundtrip(
            pid_u32 in 10_000u32..=99_999,
            release_idx in 0usize..APERAK_RELEASES.len(),
        ) {
            let pid = Pruefidentifikator::new(pid_u32).unwrap();
            let release = Release::new(APERAK_RELEASES[release_idx]);

            let bytes = AperakBuilder::new(release.clone())
                .pruefidentifikator(pid)
                .sender("4012345000023")
                .receiver("9900357000004")
                .serialize()
                .expect("serialize must not fail for valid inputs");

            let reparsed = Platform::with_all_profiles().parse(&bytes)
                .expect("serialized APERAK must re-parse without errors");

            prop_assert_eq!(reparsed.try_message_type(), Some(MessageType::Aperak));
            let reparsed_pid = reparsed.detect_pruefidentifikator()
                .expect("re-parsed APERAK must carry a PID");
            prop_assert_eq!(reparsed_pid.as_u32(), pid_u32);
        }
    }
}

// ── CONTRL round-trip ─────────────────────────────────────────────────────────

#[cfg(feature = "contrl")]
mod contrl_roundtrip {
    use super::*;
    use edi_energy::builders::ContrlBuilder;
    use proptest::prelude::*;

    proptest! {
        /// A built CONTRL message with any valid release must re-parse as CONTRL.
        #[test]
        fn contrl_survives_roundtrip(
            release_idx in 0usize..CONTRL_RELEASES.len(),
            accept in proptest::bool::ANY,
        ) {
            let release = Release::new(CONTRL_RELEASES[release_idx]);
            let builder = ContrlBuilder::new(release.clone())
                .sender("4012345000023")
                .receiver("9900357000004")
                .interchange_ref("REF001");

            let builder = if accept { builder.accept() } else { builder.reject() };

            let bytes = builder.serialize().expect("serialize must not fail");
            let reparsed = Platform::with_all_profiles().parse(&bytes).expect("serialized CONTRL must re-parse");

            prop_assert_eq!(reparsed.try_message_type(), Some(MessageType::Contrl));
            let reparsed_release = reparsed.detect_release().expect("must have release");
            prop_assert_eq!(reparsed_release.as_str(), release.as_str());
        }
    }
}

// ── Charset invariant ─────────────────────────────────────────────────────────

/// Any builder-generated message must produce only EDIFACT-safe ASCII bytes.
#[allow(dead_code)] // called from multiple feature-gated test modules
fn assert_edifact_charset(bytes: &[u8], label: &str) {
    for (i, &b) in bytes.iter().enumerate() {
        assert!(
            b == b'\t' || b == b'\n' || b == b'\r' || (0x20..=0x7e).contains(&b),
            "byte {b:#04x} at offset {i} in {label} is outside EDIFACT-safe ASCII range"
        );
    }
}

#[cfg(feature = "utilmd")]
mod charset_invariant {
    use super::*;
    use edi_energy::builders::UtilmdBuilder;
    use proptest::prelude::*;

    proptest! {
        /// Builder-generated UTILMD must produce clean ASCII for any valid PID.
        #[test]
        fn utilmd_bytes_are_ascii_safe(pid_u32 in 10_000u32..=99_999) {
            let pid = Pruefidentifikator::new(pid_u32).unwrap();
            let bytes = UtilmdBuilder::new(Release::new("5.5.3a"))
                .pruefidentifikator(pid)
                .sender("4012345000023")
                .receiver("9900357000004")
                .serialize()
                .expect("serialize must not fail");
            assert_edifact_charset(&bytes, "UTILMD");
            assert!(!bytes.contains(&0u8), "no null bytes");
        }
    }
}

// ── UTILMD S2.1/S2.2 transaction builder ─────────────────────────────────────

#[cfg(feature = "utilmd")]
mod utilmd_transaction_tests {
    use super::*;
    use edi_energy::{AnyMessage, builders::UtilmdBuilder};

    /// A UTILMD S2.1 message with a transaction block (SG4/IDE) must round-trip
    /// correctly: the IDE qualifier, location ID, status, and references survive
    /// serialization and re-parsing.
    #[test]
    fn utilmd_s21_transaction_roundtrip() {
        let pid = Pruefidentifikator::new(55001).unwrap();
        let bytes = UtilmdBuilder::new(Release::new("S2.1"))
            .pruefidentifikator(pid)
            .document_code("E01")
            .sender("4012345000023")
            .receiver("9900357000004")
            .document_date("20241101")
            .transaction(ObjectType::Messlokation, "DE00012345678")
            .process_date("163", "20241101")
            .reference("Z13", "55001")
            .done()
            .serialize()
            .expect("S2.1 message with transaction must serialize");

        let reparsed = Platform::with_all_profiles()
            .parse(&bytes)
            .expect("must re-parse");
        assert_eq!(reparsed.try_message_type(), Some(MessageType::Utilmd));

        let AnyMessage::Utilmd(u) = reparsed else {
            panic!("expected Utilmd")
        };
        assert_eq!(u.assoc_code(), "S2.1");

        // Transaction block must be extractable
        assert_eq!(u.transactions().len(), 1, "one transaction expected");
        let tx = &u.transactions()[0];
        assert_eq!(tx.ide.qualifier, "Z19");
        assert_eq!(tx.ide.object_id.as_deref(), Some("DE00012345678"));
        assert!(!tx.dtm.is_empty(), "process DTM must be captured");
        assert!(
            tx.references.iter().any(|r| r.qualifier == "Z13"),
            "Z13 Pruefidentifikator reference must survive roundtrip"
        );
    }

    /// UTILMD S2.1 Sperrung (PID 55555) with STS segment: status must be
    /// extractable after roundtrip.
    #[test]
    fn utilmd_s21_sperrung_sts_roundtrip() {
        let pid = Pruefidentifikator::new(55555).unwrap();
        let bytes = UtilmdBuilder::new(Release::new("S2.1"))
            .pruefidentifikator(pid)
            .document_code("E03")
            .sender("4012345000023")
            .receiver("9900357000004")
            .transaction(ObjectType::Messlokation, "DE00012345678")
            .status("E07")
            .reference("Z13", "55555")
            .done()
            .serialize()
            .expect("S2.1 Sperrung must serialize");

        let reparsed = Platform::with_all_profiles()
            .parse(&bytes)
            .expect("must re-parse");
        let AnyMessage::Utilmd(u) = reparsed else {
            panic!("expected Utilmd")
        };

        let tx = &u.transactions()[0];
        assert_eq!(tx.sts.len(), 1, "STS segment must be captured");
        assert_eq!(tx.sts[0].category.as_deref(), Some("E07"));
    }

    /// UTILMD S2.2 message — structurally identical to S2.1, different assoc_code.
    #[test]
    fn utilmd_s22_transaction_roundtrip() {
        let pid = Pruefidentifikator::new(55001).unwrap();
        let bytes = UtilmdBuilder::new(Release::new("S2.2"))
            .pruefidentifikator(pid)
            .sender("4012345000023")
            .receiver("9900357000004")
            .transaction(ObjectType::Marktlokation, "12345678901")
            .reference("Z13", "55001")
            .done()
            .serialize()
            .expect("S2.2 message must serialize");

        let reparsed = Platform::with_all_profiles()
            .parse(&bytes)
            .expect("must re-parse");
        let AnyMessage::Utilmd(u) = reparsed else {
            panic!("expected Utilmd")
        };
        assert_eq!(u.assoc_code(), "S2.2");
        assert_eq!(u.transactions()[0].ide.qualifier, "Z18");
    }

    /// Multiple transactions in a single message must all be captured.
    #[test]
    fn utilmd_s21_multiple_transactions() {
        let bytes = UtilmdBuilder::new(Release::new("S2.1"))
            .sender("4012345000023")
            .receiver("9900357000004")
            .transaction(ObjectType::Messlokation, "DE00000000001")
            .reference("Z13", "55001")
            .done()
            .transaction(ObjectType::Messlokation, "DE00000000002")
            .reference("Z13", "55001")
            .done()
            .transaction(ObjectType::Messlokation, "DE00000000003")
            .reference("Z13", "55002")
            .done()
            .serialize()
            .expect("multi-transaction S2.1 must serialize");

        let reparsed = Platform::with_all_profiles()
            .parse(&bytes)
            .expect("must re-parse");
        let AnyMessage::Utilmd(u) = reparsed else {
            panic!("expected Utilmd")
        };
        assert_eq!(
            u.transactions().len(),
            3,
            "all three transactions must be captured"
        );
        assert_eq!(
            u.transactions()[0].ide.object_id.as_deref(),
            Some("DE00000000001")
        );
        assert_eq!(
            u.transactions()[2].ide.object_id.as_deref(),
            Some("DE00000000003")
        );
    }
}

// ── IFTSTA round-trip ─────────────────────────────────────────────────────────

/// Known IFTSTA release codes — one per registered fv-dated profile plus legacy.
#[cfg(feature = "iftsta")]
const IFTSTA_RELEASES: &[&str] = &["2.0g", "2.1"];

#[cfg(feature = "iftsta")]
mod iftsta_roundtrip {
    use super::*;
    use edi_energy::builders::IftstaBuilder;

    /// For each IFTSTA release, a message built with IftstaBuilder must
    /// re-parse to the same message type and assoc_code.
    #[test]
    fn iftsta_survives_roundtrip() {
        for &release_str in IFTSTA_RELEASES {
            let release = Release::new(release_str);
            let bytes = IftstaBuilder::new(release.clone())
                .sender("4012345000023")
                .receiver("9900357000004")
                .document_id("00021000")
                .serialize()
                .expect("IftstaBuilder serialize must not fail");

            let msg = Platform::with_all_profiles()
                .parse(&bytes)
                .expect("re-parse must succeed");
            let AnyMessage::Iftsta(m) = msg else {
                panic!("expected Iftsta for release {release_str}");
            };
            assert_eq!(
                m.assoc_code(),
                release_str,
                "assoc_code must survive round-trip for release {release_str}"
            );
            assert_eq!(
                m.sender().unwrap().party_id.as_deref(),
                Some("4012345000023"),
                "sender must survive round-trip"
            );
        }
    }

    /// Both release variants must parse identically as IftstaMessage;
    /// the only observable difference is assoc_code.
    #[test]
    fn iftsta_20g_vs_21_same_structure() {
        let bytes_20g = IftstaBuilder::new(Release::new("2.0g"))
            .sender("4012345000023")
            .receiver("9900357000004")
            .serialize()
            .unwrap();
        let bytes_21 = IftstaBuilder::new(Release::new("2.1"))
            .sender("4012345000023")
            .receiver("9900357000004")
            .serialize()
            .unwrap();

        let AnyMessage::Iftsta(m1) = Platform::with_all_profiles().parse(&bytes_20g).unwrap()
        else {
            panic!()
        };
        let AnyMessage::Iftsta(m2) = Platform::with_all_profiles().parse(&bytes_21).unwrap() else {
            panic!()
        };

        assert_eq!(m1.assoc_code(), "2.0g");
        assert_eq!(m2.assoc_code(), "2.1");
        // Both have the same sender/receiver — only wire code differs
        assert_eq!(m1.sender(), m2.sender());
        assert_eq!(m1.receiver(), m2.receiver());
    }
}

// ── INSRPT round-trip ─────────────────────────────────────────────────────────

/// Known INSRPT release codes — one wire release "1.1a" shared by both fv-dated profiles.
#[cfg(feature = "insrpt")]
const INSRPT_RELEASES: &[&str] = &["1.1a"];

#[cfg(feature = "insrpt")]
mod insrpt_roundtrip {
    use super::*;
    use edi_energy::builders::InsrptBuilder;

    /// For each INSRPT release, a message built with InsrptBuilder must
    /// re-parse to the same message type and assoc_code.
    #[test]
    fn insrpt_survives_roundtrip() {
        for &release_str in INSRPT_RELEASES {
            let release = Release::new(release_str);
            let bytes = InsrptBuilder::new(release.clone())
                .sender("4012345000023")
                .receiver("9900357000004")
                .document_id("BEP00021000")
                .serialize()
                .expect("InsrptBuilder serialize must not fail");

            let msg = Platform::with_all_profiles()
                .parse(&bytes)
                .expect("re-parse must succeed");
            let AnyMessage::Insrpt(m) = msg else {
                panic!("expected Insrpt for release {release_str}");
            };
            assert_eq!(
                m.assoc_code(),
                release_str,
                "assoc_code must survive round-trip for release {release_str}"
            );
            assert_eq!(
                m.sender().unwrap().party_id.as_deref(),
                Some("4012345000023"),
                "sender must survive round-trip"
            );
        }
    }

    /// INSRPT uses the same wire code "1.1a" for both fv-dated profiles;
    /// verify that the builder produces a parseable InsrptMessage for both.
    #[test]
    fn insrpt_both_fv_dates_same_wire_code() {
        // fv20211001 and fv20260101 both use wire code "1.1a"
        let bytes1 = InsrptBuilder::new(Release::new("1.1a"))
            .sender("4012345000023")
            .receiver("9900357000004")
            .serialize()
            .unwrap();
        // Re-parsing with "1.1a" always selects the last-registered profile (fv20260101)
        let AnyMessage::Insrpt(m) = Platform::with_all_profiles().parse(&bytes1).unwrap() else {
            panic!()
        };
        assert_eq!(m.assoc_code(), "1.1a");
        assert!(m.sender().is_some());
        assert!(m.receiver().is_some());
    }
}

// ── INVOIC round-trip ─────────────────────────────────────────────────────────

/// Known INVOIC release codes — one wire release "2.8e" shared by both fv-dated profiles.
#[cfg(feature = "invoic")]
const INVOIC_RELEASES: &[&str] = &["2.8e"];

#[cfg(feature = "invoic")]
mod invoic_roundtrip {
    use super::*;
    use edi_energy::builders::InvoicBuilder;

    /// For each INVOIC release, a message built with InvoicBuilder must
    /// re-parse to the same message type and assoc_code.
    #[test]
    fn invoic_survives_roundtrip() {
        for &release_str in INVOIC_RELEASES {
            let release = Release::new(release_str);
            let bytes = InvoicBuilder::new(release.clone())
                .sender("4012345000023")
                .receiver("9900357000004")
                .document_id("INV20251001001")
                .serialize()
                .expect("InvoicBuilder serialize must not fail");

            let msg = Platform::with_all_profiles()
                .parse(&bytes)
                .expect("re-parse must succeed");
            let AnyMessage::Invoic(m) = msg else {
                panic!("expected Invoic for release {release_str}");
            };
            assert_eq!(
                m.assoc_code(),
                release_str,
                "assoc_code must survive round-trip for release {release_str}"
            );
            assert_eq!(
                m.sender().unwrap().party_id.as_deref(),
                Some("4012345000023"),
                "sender must survive round-trip"
            );
        }
    }

    /// INVOIC uses the same wire code "2.8e" for both fv-dated profiles
    /// (AHB 1.0a = fv20251001, AHB 1.0b = fv20260401); verify that the
    /// builder produces a parseable InvoicMessage for both.
    #[test]
    fn invoic_both_fv_dates_same_wire_code() {
        // fv20251001 and fv20260401 both use wire code "2.8e"
        let bytes = InvoicBuilder::new(Release::new("2.8e"))
            .sender("4012345000023")
            .receiver("9900357000004")
            .document_id("INV20251001002")
            .serialize()
            .unwrap();
        // Re-parsing with "2.8e" selects the last-registered profile (fv20260401)
        let AnyMessage::Invoic(m) = Platform::with_all_profiles().parse(&bytes).unwrap() else {
            panic!()
        };
        assert_eq!(m.assoc_code(), "2.8e");
        assert!(m.sender().is_some());
        assert!(m.receiver().is_some());
    }
}

// ── ORDERS round-trip ─────────────────────────────────────────────────────────

/// ORDERS has one active fv-dated profile:
/// - fv20260401 (AHB 1.1b) → wire release "1.4c" (valid from 2026-04-01)
#[cfg(feature = "orders")]
const ORDERS_RELEASES: &[&str] = &["1.4c"];

#[cfg(feature = "orders")]
mod orders_roundtrip {
    use super::*;
    use edi_energy::builders::OrdersBuilder;

    /// For each ORDERS release, a message built with OrdersBuilder must
    /// re-parse to the same message type and assoc_code.
    #[test]
    fn orders_survives_roundtrip() {
        for &release_str in ORDERS_RELEASES {
            let release = Release::new(release_str);
            let bytes = OrdersBuilder::new(release.clone())
                .sender("4012345000023")
                .receiver("9900357000004")
                .document_id("ORD20251001001")
                .serialize()
                .expect("OrdersBuilder serialize must not fail");

            let msg = Platform::with_all_profiles()
                .parse(&bytes)
                .expect("re-parse must succeed");
            let AnyMessage::Orders(m) = msg else {
                panic!("expected Orders for release {release_str}");
            };
            assert_eq!(
                m.assoc_code(),
                release_str,
                "assoc_code must survive round-trip for release {release_str}"
            );
            assert_eq!(
                m.sender().unwrap().party_id.as_deref(),
                Some("4012345000023"),
                "sender must survive round-trip"
            );
        }
    }

    /// ORDERS fv20260401 uses wire code "1.4c".
    #[test]
    fn orders_fv20260401_uses_wire_1_4c() {
        // fv20260401 (AHB 1.1b) uses wire code "1.4c"
        let bytes_1_4c = OrdersBuilder::new(Release::new("1.4c"))
            .sender("4012345000023")
            .receiver("9900357000004")
            .document_id("ORD14C001")
            .serialize()
            .unwrap();
        let AnyMessage::Orders(m2) = Platform::with_all_profiles().parse(&bytes_1_4c).unwrap()
        else {
            panic!("expected Orders for 1.4c");
        };
        assert_eq!(m2.assoc_code(), "1.4c");
    }
}

// ── PARTIN round-trip ─────────────────────────────────────────────────────────

/// PARTIN has one active fv-dated profile:
/// - fv20260401 (AHB 1.1, MIG 1.1) → wire release "1.1" (valid from 2026-04-01)
#[cfg(feature = "partin")]
const PARTIN_RELEASES: &[&str] = &["1.1"];

#[cfg(feature = "partin")]
mod partin_roundtrip {
    use super::*;
    use edi_energy::builders::PartinBuilder;

    /// For each PARTIN release, a message built with PartinBuilder must
    /// re-parse to the same message type and assoc_code.
    #[test]
    fn partin_survives_roundtrip() {
        for &release_str in PARTIN_RELEASES {
            let release = Release::new(release_str);
            let bytes = PartinBuilder::new(release.clone())
                .sender("4012345000023")
                .receiver("9900357000004")
                .document_id("PART20251001001")
                .serialize()
                .expect("PartinBuilder serialize must not fail");

            let msg = Platform::with_all_profiles()
                .parse(&bytes)
                .expect("re-parse must succeed");
            let AnyMessage::Partin(m) = msg else {
                panic!("expected Partin for release {release_str}");
            };
            assert_eq!(
                m.assoc_code(),
                release_str,
                "assoc_code must survive round-trip for release {release_str}"
            );
            assert_eq!(
                m.sender().unwrap().party_id.as_deref(),
                Some("4012345000023"),
                "sender must survive round-trip"
            );
        }
    }

    /// PARTIN fv20260401 uses wire code "1.1" (CTA+COM removed from NAD+MS header).
    #[test]
    fn partin_fv20260401_uses_wire_1_1() {
        // fv20260401 (AHB 1.1, MIG 1.1) uses wire code "1.1"
        let bytes_1_1 = PartinBuilder::new(Release::new("1.1"))
            .sender("4012345000023")
            .receiver("9900357000004")
            .document_id("PART11001")
            .serialize()
            .unwrap();
        let AnyMessage::Partin(m2) = Platform::with_all_profiles().parse(&bytes_1_1).unwrap()
        else {
            panic!("expected Partin for 1.1");
        };
        assert_eq!(m2.assoc_code(), "1.1");
    }
}

// ── REQOTE round-trip ─────────────────────────────────────────────────────────

/// REQOTE uses the SAME wire release "1.3c" for both fv-dated profiles:
/// - fv20250401 (AHB 1.1, MIG 1.3c) → wire release "1.3c"
/// - fv20260401 (AHB 1.2, MIG 1.3c) → wire release "1.3c"
///
/// This is the same-release-multiple-fv-date pattern (same as INVOIC).
#[cfg(feature = "reqote")]
const REQOTE_RELEASES: &[&str] = &["1.3c"];

#[cfg(feature = "reqote")]
mod reqote_roundtrip {
    use super::*;
    use edi_energy::builders::ReqoteBuilder;

    /// A message built with ReqoteBuilder must re-parse to the same message
    /// type and assoc_code for both fv-dated profiles (both use wire "1.3c").
    #[test]
    fn reqote_survives_roundtrip() {
        for &release_str in REQOTE_RELEASES {
            let release = Release::new(release_str);
            let bytes = ReqoteBuilder::new(release.clone())
                .sender("4012345000023")
                .receiver("9900357000004")
                .document_id("REQ20250401001")
                .serialize()
                .expect("ReqoteBuilder serialize must not fail");

            let msg = Platform::with_all_profiles()
                .parse(&bytes)
                .expect("re-parse must succeed");
            let AnyMessage::Reqote(m) = msg else {
                panic!("expected Reqote for release {release_str}");
            };
            assert_eq!(
                m.assoc_code(),
                release_str,
                "assoc_code must survive round-trip for release {release_str}"
            );
            assert_eq!(
                m.sender().unwrap().party_id.as_deref(),
                Some("4012345000023"),
                "sender must survive round-trip"
            );
        }
    }

    /// REQOTE uses the SAME wire code "1.3c" for both fv-dated profiles
    /// (AHB 1.1 = fv20250401, AHB 1.2 = fv20260401) — same-release pattern.
    /// Re-parsing with "1.3c" selects the last-registered profile (fv20260401).
    #[test]
    fn reqote_both_fv_dates_same_wire_code() {
        let bytes = ReqoteBuilder::new(Release::new("1.3c"))
            .sender("4012345000023")
            .receiver("9900357000004")
            .document_id("REQ13C001")
            .document_code("311")
            .serialize()
            .unwrap();
        let AnyMessage::Reqote(m) = Platform::with_all_profiles().parse(&bytes).unwrap() else {
            panic!("expected Reqote");
        };
        assert_eq!(m.assoc_code(), "1.3c");
        assert!(m.sender().is_some());
        assert!(m.receiver().is_some());
    }
}

// ── REMADV round-trip ─────────────────────────────────────────────────────────

/// REMADV has one active fv-dated profile:
/// - fv20260401 (AHB 1.0b, MIG 2.9f) → wire release "2.9f" (valid from 2026-04-01)
#[cfg(feature = "remadv")]
const REMADV_RELEASES: &[&str] = &["2.9f"];

#[cfg(feature = "remadv")]
mod remadv_roundtrip {
    use super::*;
    use edi_energy::builders::RemadvBuilder;

    /// A message built with RemadvBuilder must re-parse to the same message
    /// type and assoc_code.
    #[test]
    fn remadv_survives_roundtrip() {
        for &release_str in REMADV_RELEASES {
            let release = Release::new(release_str);
            let bytes = RemadvBuilder::new(release.clone())
                .sender("4012345000023")
                .receiver("9900357000004")
                .document_id("REMADV20251001001")
                .serialize()
                .expect("RemadvBuilder serialize must not fail");

            let msg = Platform::with_all_profiles()
                .parse(&bytes)
                .expect("re-parse must succeed");
            let AnyMessage::Remadv(m) = msg else {
                panic!("expected Remadv for release {release_str}");
            };
            assert_eq!(
                m.assoc_code(),
                release_str,
                "assoc_code must survive round-trip for release {release_str}"
            );
            assert_eq!(
                m.sender().unwrap().party_id.as_deref(),
                Some("4012345000023"),
                "sender must survive round-trip"
            );
        }
    }

    /// The fv20260401 profile correctly parses REMADV messages with wire "2.9f".
    #[test]
    fn remadv_fv20260401_parses_wire_2_9f() {
        let bytes = RemadvBuilder::new(Release::new("2.9f"))
            .sender("4012345000023")
            .receiver("9900357000004")
            .document_id("REMADV29E001")
            .document_code("239")
            .serialize()
            .unwrap();
        let AnyMessage::Remadv(m) = Platform::with_all_profiles().parse(&bytes).unwrap() else {
            panic!("expected Remadv");
        };
        assert_eq!(m.assoc_code(), "2.9f");
        assert!(m.sender().is_some());
        assert!(m.receiver().is_some());
    }
}

// ── ORDCHG round-trip ─────────────────────────────────────────────────────────

/// ORDCHG has two fv-dated profiles with different wire releases and structure:
/// - fv20241001 (AHB 1.0a, MIG 1.1) → wire release "1.1" (has SG6: CTA+COM)
/// - fv20260401 (AHB 1.1,  MIG 1.2) → wire release "1.2" (SG6 removed)
#[cfg(feature = "ordchg")]
const ORDCHG_RELEASES: &[&str] = &["1.1", "1.2"];

#[cfg(feature = "ordchg")]
mod ordchg_roundtrip {
    use super::*;
    use edi_energy::builders::OrdchgBuilder;

    /// Both ORDCHG releases must re-parse correctly after a builder round-trip.
    #[test]
    fn ordchg_survives_roundtrip() {
        for &release_str in ORDCHG_RELEASES {
            let release = Release::new(release_str);
            let bytes = OrdchgBuilder::new(release.clone())
                .sender("4012345000023")
                .receiver("9900357000004")
                .document_code("Z51")
                .document_id("ORDCHG20241001001")
                .serialize()
                .unwrap_or_else(|e| panic!("serialize failed for release {release_str}: {e}"));

            let msg = Platform::with_all_profiles()
                .parse(&bytes)
                .unwrap_or_else(|e| panic!("parse failed for release {release_str}: {e}"));
            let AnyMessage::Ordchg(m) = msg else {
                panic!("expected Ordchg for release {release_str}");
            };
            assert_eq!(
                m.assoc_code(),
                release_str,
                "assoc_code must survive round-trip for release {release_str}"
            );
            assert_eq!(
                m.sender().unwrap().party_id.as_deref(),
                Some("4012345000023"),
                "sender must survive round-trip for release {release_str}"
            );
        }
    }

    /// fv20241001 (MIG 1.1, wire "1.1") — Stornierung Sperr-/Entsperrauftrag.
    #[test]
    fn ordchg_fv20241001_parses_z51_cancellation() {
        let bytes = OrdchgBuilder::new(Release::new("1.1"))
            .sender("4012345000023")
            .receiver("9900357000004")
            .document_code("Z51")
            .document_id("CANCELSPERR001")
            .serialize()
            .unwrap();
        let AnyMessage::Ordchg(m) = Platform::with_all_profiles().parse(&bytes).unwrap() else {
            panic!("expected Ordchg");
        };
        assert_eq!(m.assoc_code(), "1.1");
        assert!(m.bgm().is_some());
    }

    /// fv20260401 (MIG 1.2, wire "1.2") — same PIDs, SG6 removed.
    #[test]
    fn ordchg_fv20260401_parses_z51_cancellation() {
        let bytes = OrdchgBuilder::new(Release::new("1.2"))
            .sender("4012345000023")
            .receiver("9900357000004")
            .document_code("Z51")
            .document_id("CANCELSPERR002")
            .serialize()
            .unwrap();
        let AnyMessage::Ordchg(m) = Platform::with_all_profiles().parse(&bytes).unwrap() else {
            panic!("expected Ordchg");
        };
        assert_eq!(m.assoc_code(), "1.2");
        assert!(m.bgm().is_some());
    }
}

// ── ORDRSP round-trip ─────────────────────────────────────────────────────────

/// ORDRSP has one active fv-dated profile:
/// - fv20260401 (AHB 1.1b, MIG 1.4c) → wire release "1.4c" (valid from 2026-04-01)
#[cfg(feature = "ordrsp")]
const ORDRSP_RELEASES: &[&str] = &["1.4c"];

#[cfg(feature = "ordrsp")]
mod ordrsp_roundtrip {
    use super::*;
    use edi_energy::builders::OrdrespBuilder;

    /// Both ORDRSP releases must re-parse correctly after a builder round-trip.
    #[test]
    fn ordrsp_survives_roundtrip() {
        for &release_str in ORDRSP_RELEASES {
            let release = Release::new(release_str);
            let bytes = OrdrespBuilder::new(release.clone())
                .sender("9900357000004")
                .receiver("4012345000023")
                .document_id("ORDRSP20251001001")
                .serialize()
                .unwrap_or_else(|e| panic!("serialize failed for release {release_str}: {e}"));

            let msg = Platform::with_all_profiles()
                .parse(&bytes)
                .unwrap_or_else(|e| panic!("parse failed for release {release_str}: {e}"));
            let AnyMessage::Ordrsp(m) = msg else {
                panic!("expected Ordrsp for release {release_str}");
            };
            assert_eq!(
                m.assoc_code(),
                release_str,
                "assoc_code must survive round-trip for release {release_str}"
            );
            assert_eq!(
                m.sender().unwrap().party_id.as_deref(),
                Some("9900357000004"),
                "sender must survive round-trip for release {release_str}"
            );
        }
    }

    /// fv20260401 (MIG 1.4c, wire "1.4c") — Bestellbestätigung.
    #[test]
    fn ordrsp_fv20260401_parses_bestellbestaetigung_14c() {
        let bytes = OrdrespBuilder::new(Release::new("1.4c"))
            .sender("9900357000004")
            .receiver("4012345000023")
            .document_id("ORDRSP14C001")
            .serialize()
            .unwrap();
        let AnyMessage::Ordrsp(m) = Platform::with_all_profiles().parse(&bytes).unwrap() else {
            panic!("expected Ordrsp");
        };
        assert_eq!(m.assoc_code(), "1.4c");
        assert!(m.bgm().is_some());
    }
}

// ── QUOTES round-trip ─────────────────────────────────────────────────────────

/// QUOTES has one fv-dated profile:
/// - fv20260401 (AHB 1.1a, MIG 1.3c) → wire release "1.3c" (valid from 2026-04-01)
///
/// All 5 Prüfidentifikatoren (15001–15005) are covered.
#[cfg(feature = "quotes")]
const QUOTES_RELEASES: &[&str] = &["1.3c"];

#[cfg(feature = "comdis")]
const COMDIS_RELEASES: &[&str] = &["1.0g"];

#[cfg(feature = "quotes")]
mod quotes_roundtrip {
    use super::*;
    use edi_energy::builders::QuotesBuilder;

    /// Both QUOTES releases must re-parse correctly after a builder round-trip.
    #[test]
    fn quotes_survives_roundtrip() {
        for &release_str in QUOTES_RELEASES {
            let release = Release::new(release_str);
            let bytes = QuotesBuilder::new(release.clone())
                .sender("9900357000004")
                .receiver("4012345000023")
                .document_id("QUOTES20250401001")
                .serialize()
                .unwrap_or_else(|e| panic!("serialize failed for release {release_str}: {e}"));

            let msg = Platform::with_all_profiles()
                .parse(&bytes)
                .unwrap_or_else(|e| panic!("parse failed for release {release_str}: {e}"));
            let AnyMessage::Quotes(m) = msg else {
                panic!("expected Quotes for release {release_str}");
            };
            assert_eq!(
                m.assoc_code(),
                release_str,
                "assoc_code must survive round-trip for release {release_str}"
            );
            assert_eq!(
                m.sender().unwrap().party_id.as_deref(),
                Some("9900357000004"),
                "sender must survive round-trip for release {release_str}"
            );
        }
    }

    /// fv20260401 (MIG 1.3c, wire "1.3c") — Angebot Geräteübernahme.
    #[test]
    fn quotes_fv20260401_parses_angebot_geraeteuebernahme() {
        let bytes = QuotesBuilder::new(Release::new("1.3c"))
            .sender("9900357000004")
            .receiver("4012345000023")
            .document_id("QUOTES13C001")
            .serialize()
            .unwrap();
        let AnyMessage::Quotes(m) = Platform::with_all_profiles().parse(&bytes).unwrap() else {
            panic!("expected Quotes");
        };
        assert_eq!(m.assoc_code(), "1.3c");
        assert!(m.bgm().is_some());
        assert!(m.sender().is_some());
    }

    /// fv20260401 (MIG 1.3c, wire "1.3c") — same PIDs, minor structural changes.
    #[test]
    fn quotes_fv20260401_parses_angebot() {
        let bytes = QuotesBuilder::new(Release::new("1.3c"))
            .sender("9900357000004")
            .receiver("4012345000023")
            .document_id("QUOTES13C001")
            .serialize()
            .unwrap();
        let AnyMessage::Quotes(m) = Platform::with_all_profiles().parse(&bytes).unwrap() else {
            panic!("expected Quotes");
        };
        assert_eq!(m.assoc_code(), "1.3c");
        assert!(m.bgm().is_some());
    }
}

// ── COMDIS round-trip ─────────────────────────────────────────────────────────

#[cfg(feature = "comdis")]
mod comdis_roundtrip {
    use super::COMDIS_RELEASES;
    use edi_energy::builders::ComdisBuilder;
    use edi_energy::{AnyMessage, EdiEnergyMessage, Platform, Release};

    /// Serialize then re-parse COMDIS for every registered release; verify that
    /// assoc_code, sender, and Prüfidentifikator all survive the round-trip.
    #[test]
    fn comdis_survives_roundtrip() {
        for &release_str in COMDIS_RELEASES {
            let release = Release::new(release_str);
            let bytes = ComdisBuilder::new(release.clone())
                .sender("9900357000004")
                .receiver("4012345000023")
                .pruefidentifikator(29001)
                .document_id("COMDIS20251001001")
                .reject_document("380", "REMADV-REF-001", "E_0265")
                .serialize()
                .unwrap_or_else(|e| panic!("serialize failed for release {release_str}: {e}"));

            let msg = Platform::with_all_profiles()
                .parse(&bytes)
                .unwrap_or_else(|e| panic!("parse failed for release {release_str}: {e}"));
            let AnyMessage::Comdis(m) = msg else {
                panic!("expected Comdis for release {release_str}");
            };
            assert_eq!(
                m.assoc_code(),
                release_str,
                "assoc_code must survive round-trip for release {release_str}"
            );
            assert_eq!(
                m.sender().unwrap().party_id.as_deref(),
                Some("9900357000004"),
                "sender must survive round-trip for release {release_str}"
            );
            assert_eq!(
                m.detect_pruefidentifikator()
                    .expect("PID must be detected after round-trip")
                    .as_u32(),
                29001,
                "pruefidentifikator must survive round-trip for release {release_str}"
            );
        }
    }

    /// fv20251001 (AHB 1.0g) — Ablehnung REMADV (PID 29001).
    #[test]
    fn comdis_fv20251001_parses_ablehnung_remadv() {
        let bytes = ComdisBuilder::new(Release::new("1.0g"))
            .sender("9900357000004")
            .receiver("4012345000023")
            .pruefidentifikator(29001)
            .document_id("ABL29001001")
            .reject_document("380", "REMADV-REF-001", "E_0265")
            .serialize()
            .unwrap();
        let AnyMessage::Comdis(m) = Platform::with_all_profiles().parse(&bytes).unwrap() else {
            panic!("expected Comdis");
        };
        assert_eq!(m.assoc_code(), "1.0g");
        assert!(m.bgm().is_some());
        assert!(m.sender().is_some());
        assert_eq!(
            m.detect_pruefidentifikator()
                .expect("PID must be detected")
                .as_u32(),
            29001
        );
    }

    /// fv20261001 (AHB 1.0g, placeholder) — Ablehnung IFTSTA (PID 29002).
    ///
    /// Skipped at runtime until the profile becomes active on 2026-10-01 so that
    /// CI always counts the test (it shows as `ok` with a skipped message) rather
    /// than disappearing under `#[ignore]` indefinitely.
    #[test]
    fn comdis_fv20261001_parses_ablehnung_iftsta() {
        // Runtime gate: FV2026-10-01 activates on 2026-10-01.
        // This check replaces a static #[ignore] so the test transitions
        // automatically without any manual code change.
        if !time::OffsetDateTime::now_utc()
            .date()
            .ge(&time::Date::from_calendar_date(2026, time::Month::October, 1).unwrap())
        {
            println!(
                "skipping: COMDIS AHB 1.0g (FV2026-10-01) not yet active \
                 (activates 2026-10-01, today is {})",
                time::OffsetDateTime::now_utc().date()
            );
            return;
        }
        let bytes = ComdisBuilder::new(Release::new("1.0g"))
            .sender("4012345000023")
            .receiver("9900357000004")
            .pruefidentifikator(29002)
            .document_id("ABL29002001")
            .document_code("739")
            .reject_document("Z41", "IFTSTA-REF-001", "E_0265")
            .serialize()
            .unwrap();
        let AnyMessage::Comdis(m) = Platform::with_all_profiles().parse(&bytes).unwrap() else {
            panic!("expected Comdis");
        };
        assert_eq!(m.assoc_code(), "1.0g");
        assert!(m.bgm().is_some());
        assert_eq!(
            m.detect_pruefidentifikator()
                .expect("PID must be detected")
                .as_u32(),
            29002
        );
    }
}

// ── PRICAT release constants ──────────────────────────────────────────────────

#[cfg(feature = "pricat")]
const PRICAT_ALL_RELEASES: &[&str] = &["2.1"];

// ── PRICAT round-trip ─────────────────────────────────────────────────────────

#[cfg(feature = "pricat")]
mod pricat_roundtrip {
    use super::PRICAT_ALL_RELEASES;
    use edi_energy::builders::PricatBuilder;
    use edi_energy::{AnyMessage, EdiEnergyMessage, Platform, Release};

    /// Serialize then re-parse PRICAT for every registered release; verify that
    /// assoc_code, sender, and Prüfidentifikator all survive the round-trip.
    #[test]
    fn pricat_survives_roundtrip() {
        for &release_str in PRICAT_ALL_RELEASES {
            let release = Release::new(release_str);
            let bytes = PricatBuilder::new(release.clone())
                .sender("9900357000004")
                .receiver("4012345000023")
                .pruefidentifikator(27001)
                .document_id("PRICAT20250401001")
                .serialize()
                .unwrap_or_else(|e| panic!("serialize failed for release {release_str}: {e}"));

            let msg = Platform::with_all_profiles()
                .parse(&bytes)
                .unwrap_or_else(|e| panic!("parse failed for release {release_str}: {e}"));
            let AnyMessage::Pricat(m) = msg else {
                panic!("expected Pricat for release {release_str}");
            };
            assert_eq!(
                m.assoc_code(),
                release_str,
                "assoc_code must survive round-trip for release {release_str}"
            );
            assert_eq!(
                m.sender().unwrap().party_id.as_deref(),
                Some("9900357000004"),
                "sender must survive round-trip for release {release_str}"
            );
            assert_eq!(
                m.detect_pruefidentifikator()
                    .expect("PID must be detected after round-trip")
                    .as_u32(),
                27001,
                "pruefidentifikator must survive round-trip for release {release_str}"
            );
        }
    }

    /// fv20260401 (MIG 2.1) — Ausgleichsenergiepreise (PID 27001).
    #[test]
    fn pricat_fv20260401_parses_ausgleichsenergiepreise() {
        let bytes = PricatBuilder::new(Release::new("2.1"))
            .sender("9900357000004")
            .receiver("4012345000023")
            .pruefidentifikator(27001)
            .document_id("PRIC27001001")
            .serialize()
            .unwrap();
        let AnyMessage::Pricat(m) = Platform::with_all_profiles().parse(&bytes).unwrap() else {
            panic!("expected Pricat");
        };
        assert_eq!(m.assoc_code(), "2.1");
        assert!(m.bgm().is_some());
        assert!(m.sender().is_some());
        assert_eq!(
            m.detect_pruefidentifikator()
                .expect("PID must be detected")
                .as_u32(),
            27001
        );
    }

    /// fv20260401 (MIG 2.1) — Preisblatt NB-Leistungen (PID 27003).
    #[test]
    fn pricat_fv20260401_parses_preisblatt_nb() {
        let bytes = PricatBuilder::new(Release::new("2.1"))
            .sender("4012345000023")
            .receiver("9900357000004")
            .pruefidentifikator(27003)
            .document_id("PRIC27003001")
            .document_code("Z77")
            .serialize()
            .unwrap();
        let AnyMessage::Pricat(m) = Platform::with_all_profiles().parse(&bytes).unwrap() else {
            panic!("expected Pricat");
        };
        assert_eq!(m.assoc_code(), "2.1");
        assert!(m.bgm().is_some());
        assert_eq!(
            m.detect_pruefidentifikator()
                .expect("PID must be detected")
                .as_u32(),
            27003
        );
    }

    /// DTM+137 is emitted in format 303 (not 102) as required by the PRICAT MIG.
    #[test]
    fn pricat_dtm137_uses_format_303() {
        let bytes = PricatBuilder::new(Release::new("2.1"))
            .document_date("20260601")
            .serialize()
            .unwrap();
        let raw = String::from_utf8(bytes).unwrap();
        // Must contain format 303 datetime, not 102.
        assert!(
            raw.contains(":303'") || raw.contains(":303+"),
            "DTM+137 must use format 303, got: {raw}"
        );
        assert!(!raw.contains(":102'"), "DTM+137 must NOT use format 102");
    }

    /// Price body (SG17/SG36/SG40) round-trip: build with a price group,
    /// serialize, re-parse, and verify PID and sender survive intact.
    #[test]
    fn pricat_price_body_survives_roundtrip() {
        use edi_energy::builders::{PricatLineItem, PricatPriceEntry, PricatPriceGroup};

        let price = PricatPriceEntry::new("CAL", "5.50", "EUR")
            .valid_from("202504010000+0000")
            .valid_to("202505010000+0000");
        let line = PricatLineItem::new(price)
            .schedule_id("AEP001")
            .description("Ausgleichsenergie positiv");
        let group = PricatPriceGroup::new("Z01", line);

        let bytes = PricatBuilder::new(Release::new("2.1"))
            .sender("9900357000004")
            .receiver("4012345000023")
            .pruefidentifikator(27001)
            .document_id("PRIC-BODY-001")
            .add_price_group(group)
            .serialize()
            .unwrap();

        let msg = Platform::with_all_profiles().parse(&bytes).unwrap();
        let AnyMessage::Pricat(m) = msg else {
            panic!("expected Pricat");
        };
        assert_eq!(m.assoc_code(), "2.1");
        assert_eq!(
            m.detect_pruefidentifikator()
                .expect("PID must survive")
                .as_u32(),
            27001
        );
        assert_eq!(
            m.sender().unwrap().party_id.as_deref(),
            Some("9900357000004")
        );
        // Verify price body segments are present.
        let raw = String::from_utf8(
            m.segments()
                .iter()
                .flat_map(|s| {
                    let mut v = s.tag.as_bytes().to_vec();
                    v.push(b'+');
                    v
                })
                .collect::<Vec<_>>(),
        )
        .unwrap();
        assert!(raw.contains("PGI+"), "PGI segment must be present");
        assert!(raw.contains("LIN+"), "LIN segment must be present");
        assert!(raw.contains("PRI+"), "PRI segment must be present");
    }
}

#[cfg(feature = "utilts")]
const UTILTS_ALL_RELEASES: &[&str] = &["1.1e"];

// ── UTILTS round-trip ─────────────────────────────────────────────────────────

#[cfg(feature = "utilts")]
mod utilts_roundtrip {
    use super::UTILTS_ALL_RELEASES;
    use edi_energy::builders::{
        UtiltsBuilder, UtiltsCalcStep, UtiltsDefinitionBlock, UtiltsEnergyAmountRef,
        UtiltsUsagePeriod, UtiltsVorgang,
    };
    use edi_energy::{AnyMessage, EdiEnergyMessage, Platform, Release};

    /// Serialize then re-parse UTILTS for every registered release; verify that
    /// assoc_code, sender, Prüfidentifikator, and Vorgangsnummer survive round-trip.
    ///
    /// Both fv20241001 (AHB 1.0) and fv20260401 (AHB 1.1) use MIG 1.1e, so
    /// UTILTS_ALL_RELEASES has a single entry "1.1e". The test validates that the
    /// same wire format works through the builder → serialize → parse → inspect cycle.
    #[test]
    fn utilts_survives_roundtrip() {
        for &release_str in UTILTS_ALL_RELEASES {
            let release = Release::new(release_str);
            let bytes = UtiltsBuilder::new(release.clone())
                .sender("9900259000002")
                .receiver("9900259000001")
                .document_id("UTILTS20241001001")
                .add_vorgang(UtiltsVorgang::new("Vorgang001", 25001))
                .serialize()
                .unwrap_or_else(|e| panic!("serialize failed for release {release_str}: {e}"));

            let msg = Platform::with_all_profiles()
                .parse(&bytes)
                .unwrap_or_else(|e| panic!("parse failed for release {release_str}: {e}"));
            let AnyMessage::Utilts(m) = msg else {
                panic!("expected Utilts for release {release_str}");
            };
            assert_eq!(
                m.assoc_code(),
                release_str,
                "assoc_code must survive round-trip for release {release_str}"
            );
            assert_eq!(
                m.sender().unwrap().party_id.as_deref(),
                Some("9900259000002"),
                "sender must survive round-trip for release {release_str}"
            );
            assert_eq!(
                m.detect_pruefidentifikator()
                    .expect("PID must be detected after round-trip")
                    .as_u32(),
                25001,
                "pruefidentifikator must survive round-trip for release {release_str}"
            );
        }
    }

    /// fv20241001 (AHB 1.0, MIG 1.1e) — Berechnungsformel (PID 25001).
    ///
    /// Validates: PID extracted from SG5→SG6 RFF+Z13 (rff_z13 pid_source),
    /// wire code "1.1e", BGM code "Z36".
    #[test]
    fn utilts_fv20241001_parses_berechnungsformel() {
        let bytes = UtiltsBuilder::new(Release::new("1.1e"))
            .sender("9900259000002")
            .receiver("9900259000001")
            .document_id("MKIDI5422")
            .add_vorgang(UtiltsVorgang::new("Vorgang001", 25001))
            .serialize()
            .unwrap();
        let AnyMessage::Utilts(m) = Platform::with_all_profiles().parse(&bytes).unwrap() else {
            panic!("expected Utilts");
        };
        assert_eq!(m.assoc_code(), "1.1e");
        assert!(m.bgm().is_some());
        assert!(m.sender().is_some());
        assert_eq!(
            m.detect_pruefidentifikator()
                .expect("PID must be detected")
                .as_u32(),
            25001
        );
    }

    /// fv20260401 (AHB 1.1, same MIG 1.1e) — Berechnungsformel (PID 25001).
    ///
    /// Validates that the wire format is identical to fv20241001 — the annual
    /// change is AHB-only (new package conditions, role [63] NB added), not
    /// structural. The same builder and same PID work with both AHB versions.
    #[test]
    fn utilts_fv20260401_parses_berechnungsformel() {
        let bytes = UtiltsBuilder::new(Release::new("1.1e"))
            .sender("4012345000023")
            .receiver("9900259000002")
            .document_id("MKIDI9988")
            .document_code("Z78")
            .add_vorgang(UtiltsVorgang::new("Vorgang002", 25004))
            .serialize()
            .unwrap();
        let AnyMessage::Utilts(m) = Platform::with_all_profiles().parse(&bytes).unwrap() else {
            panic!("expected Utilts");
        };
        assert_eq!(m.assoc_code(), "1.1e");
        assert!(m.bgm().is_some());
        assert_eq!(
            m.detect_pruefidentifikator()
                .expect("PID must be detected")
                .as_u32(),
            25004
        );
    }

    /// DTM+137 is emitted in format 303 (not 102) as required by the UTILTS MIG 1.1e.
    ///
    /// UTILTS uses the same format-303 convention as PRICAT, different from
    /// UTILMD/MSCONS which use format 102.
    #[test]
    fn utilts_dtm137_uses_format_303() {
        let bytes = UtiltsBuilder::new(Release::new("1.1e"))
            .document_date("20241001")
            .add_vorgang(UtiltsVorgang::new("V001", 25001))
            .serialize()
            .unwrap();
        let raw = String::from_utf8(bytes).unwrap();
        assert!(
            raw.contains(":303'") || raw.contains(":303+"),
            "DTM+137 must use format 303, got: {raw}"
        );
        assert!(!raw.contains(":102'"), "DTM+137 must NOT use format 102");
    }

    /// Multiple Vorgänge in a single UTILTS message — PID of first Vorgang wins.
    #[test]
    fn utilts_multiple_vorgaenge_survives_roundtrip() {
        let bytes = UtiltsBuilder::new(Release::new("1.1e"))
            .sender("9900259000002")
            .receiver("9900259000001")
            .add_vorgang(UtiltsVorgang::new("V001", 25004))
            .add_vorgang(UtiltsVorgang::new("V002", 25004))
            .add_vorgang(UtiltsVorgang::new("V003", 25004))
            .serialize()
            .unwrap();
        let AnyMessage::Utilts(m) = Platform::with_all_profiles().parse(&bytes).unwrap() else {
            panic!("expected Utilts");
        };
        // First Vorgang PID is used as message-level PID.
        assert_eq!(
            m.detect_pruefidentifikator()
                .expect("PID must be detected")
                .as_u32(),
            25004
        );
    }

    /// Full Berechnungsformel body (PID 25001) — usage period, energy-amount
    /// reference, and one calculation step with operator and energy direction.
    ///
    /// Validates: SEQ+Z36, SEQ+Z37+{id}, CCI+++Z86, CAV+Z69, CCI+++Z87, CAV+Z71,
    /// RFF+Z46, RFF+Z23, RFF+Z49::{id}, DTM+Z25, STS+Z23, LOC+172.
    #[test]
    fn utilts_berechnungsformel_body_survives_roundtrip() {
        let malo = "DE0000012345678901234567890123456789";
        let messlok = "DE00000456789012345678900000000003D";

        let bytes = UtiltsBuilder::new(Release::new("1.1e"))
            .sender("9900259000002")
            .receiver("9900259000001")
            .document_id("MKIDI5422")
            .add_vorgang(
                UtiltsVorgang::new("V001", 25001)
                    .location(malo)
                    .formula_status("Z33", 1)
                    .add_usage_period(UtiltsUsagePeriod::new(1, "202710012200+00"))
                    .add_energy_ref(UtiltsEnergyAmountRef::new(1, 1))
                    .add_calc_step(
                        UtiltsCalcStep::new(1)
                            .time_period(1)
                            .messlokation(messlok)
                            .operator("Z69")
                            .energy_direction("Z71"),
                    ),
            )
            .serialize()
            .unwrap();

        let raw = String::from_utf8(bytes.clone()).unwrap();

        // SG5 body segments must be present
        assert!(raw.contains("LOC+172+"), "must contain LOC+172 meldepunkt");
        assert!(
            raw.contains("STS+Z23"),
            "must contain STS+Z23 formula status"
        );
        assert!(raw.contains("RFF+Z13:25001"), "must contain PID RFF");
        assert!(
            raw.contains("RFF+Z49::1"),
            "must contain Verwendungszeitraum RFF"
        );
        assert!(
            raw.contains("DTM+Z25:"),
            "must contain Verwendungszeitraum from DTM"
        );

        // SG8 SEQ+Z36 (energy amount ref)
        assert!(
            raw.contains("SEQ+Z36"),
            "must contain SEQ+Z36 energy-amount ref"
        );
        assert!(
            raw.contains("RFF+Z46:1"),
            "must contain RFF+Z46 time-period ref"
        );

        // SG8 SEQ+Z37 (calc step)
        assert!(
            raw.contains("SEQ+Z37+1"),
            "must contain SEQ+Z37+1 calc step"
        );
        assert!(
            raw.contains("RFF+Z19:"),
            "must contain RFF+Z19 messlokation ref"
        );

        // SG9 CCI/CAV chains
        assert!(raw.contains("CCI+++Z86"), "must contain CCI+++Z86 operator");
        assert!(
            raw.contains("CAV+Z69"),
            "must contain CAV+Z69 addition operator"
        );
        assert!(
            raw.contains("CCI+++Z87"),
            "must contain CCI+++Z87 direction"
        );
        assert!(raw.contains("CAV+Z71"), "must contain CAV+Z71 Verbrauch");

        // Full roundtrip: re-parse and check PID
        let AnyMessage::Utilts(m) = Platform::with_all_profiles().parse(&bytes).unwrap() else {
            panic!("expected Utilts");
        };
        assert_eq!(m.assoc_code(), "1.1e");
        assert_eq!(
            m.detect_pruefidentifikator()
                .expect("PID must be detected")
                .as_u32(),
            25001,
        );
    }

    /// Berechnungsformel step with loss factors and split factor.
    ///
    /// Validates SG9 CCI+++Z16 (Trafo), CCI+++ZB2 (Leitung), CCI+++ZG6 (split).
    #[test]
    fn utilts_calc_step_loss_and_split_factors_roundtrip() {
        let bytes = UtiltsBuilder::new(Release::new("1.1e"))
            .add_vorgang(
                UtiltsVorgang::new("V002", 25001)
                    .add_energy_ref(UtiltsEnergyAmountRef::new(1, 1))
                    .add_calc_step(
                        UtiltsCalcStep::new(1)
                            .time_period(1)
                            .messlokation("DE00000456789012345678900000000003D")
                            .operator("Z82") // Multiplikation
                            .loss_factor_trafo("1.04")
                            .loss_factor_line("1.02")
                            .split_factor("0.2"),
                    ),
            )
            .serialize()
            .unwrap();

        let raw = String::from_utf8(bytes).unwrap();
        assert!(raw.contains("SEQ+Z37+1"), "SEQ+Z37+1 must be present");
        assert!(raw.contains("CCI+++Z86"), "operator CCI must be present");
        assert!(
            raw.contains("CAV+Z82"),
            "Multiplikation operator must be present"
        );
        assert!(
            raw.contains("CCI+++Z16"),
            "Trafo loss factor CCI must be present"
        );
        assert!(
            raw.contains("CAV+Z28:::1.04"),
            "Trafo loss factor value must be present"
        );
        assert!(
            raw.contains("CCI+++ZB2"),
            "Leitung loss factor CCI must be present"
        );
        assert!(
            raw.contains("CAV+Z28:::1.02"),
            "Leitung loss factor value must be present"
        );
        assert!(
            raw.contains("CCI+++ZG6"),
            "split factor CCI must be present"
        );
        assert!(
            raw.contains("CAV+ZH6:::0.2"),
            "split factor value must be present"
        );
    }

    /// Multiple usage periods with usage_to on the non-last period.
    ///
    /// Validates: two RFF+Z49::{id} blocks; the first has DTM+Z25 + DTM+Z26,
    /// the second has only DTM+Z25 (no DTM+Z26).
    #[test]
    fn utilts_multiple_usage_periods_survives_roundtrip() {
        let bytes = UtiltsBuilder::new(Release::new("1.1e"))
            .add_vorgang(
                UtiltsVorgang::new("V003", 25001)
                    .add_usage_period(
                        UtiltsUsagePeriod::new(1, "202510012200+00").usage_to("202610012200+00"),
                    )
                    .add_usage_period(UtiltsUsagePeriod::new(2, "202610012200+00")),
            )
            .serialize()
            .unwrap();

        let raw = String::from_utf8(bytes.clone()).unwrap();
        assert!(
            raw.contains("RFF+Z49::1"),
            "first period RFF must be present"
        );
        assert!(
            raw.contains("RFF+Z49::2"),
            "second period RFF must be present"
        );
        assert!(raw.contains("DTM+Z25:20251001"), "first period from DTM");
        assert!(raw.contains("DTM+Z26:20261001"), "first period to DTM");
        // The second period's DTM+Z25 has the same start as first period's end
        // (20261001). Check the raw contains two occurrences of "DTM+Z25:20261001".
        assert!(
            raw.matches("DTM+Z25:20261001").count() >= 1,
            "second period from DTM must be present"
        );
        // Second period must NOT have a DTM+Z26
        let second_start = raw.rfind("RFF+Z49::2").expect("second period RFF");
        let after_second = &raw[second_start..];
        let next_rff_pos = after_second
            .find("RFF+Z13")
            .or_else(|| after_second.find("SEQ+"))
            .or_else(|| after_second.find("UNT+"))
            .unwrap_or(after_second.len());
        assert!(
            !after_second[..next_rff_pos].contains("DTM+Z26"),
            "last usage period must not have DTM+Z26"
        );

        // roundtrip parse
        let AnyMessage::Utilts(m) = Platform::with_all_profiles().parse(&bytes).unwrap() else {
            panic!("expected Utilts");
        };
        assert_eq!(
            m.detect_pruefidentifikator()
                .expect("PID must be detected")
                .as_u32(),
            25001
        );
    }

    /// Zählzeitdefinition overview (PID 25004) — definition block SEQ+Z42.
    ///
    /// Validates: SEQ+Z42, CCI+Z39++{code}, CAV+ZE0:::{freq}, CAV+ZD5:::{tr}.
    #[test]
    fn utilts_zaehlzeitdefinition_body_survives_roundtrip() {
        let bytes = UtiltsBuilder::new(Release::new("1.1e"))
            .document_code("Z78")
            .add_vorgang(
                UtiltsVorgang::new("V004", 25004)
                    .definition_code("ZZ1")
                    .add_definition_block(
                        UtiltsDefinitionBlock::new("Z42")
                            .definition_code("ZZ1")
                            .frequency("Z33")
                            .transmissibility("Z23"),
                    ),
            )
            .serialize()
            .unwrap();

        let raw = String::from_utf8(bytes.clone()).unwrap();
        assert!(
            raw.contains("LOC+Z09+ZZ1"),
            "must contain LOC+Z09 definition code"
        );
        assert!(raw.contains("SEQ+Z42"), "must contain SEQ+Z42 Zählzeit");
        assert!(
            raw.contains("CCI+Z39"),
            "must contain CCI+Z39 Zählzeitdefinition type"
        );
        assert!(raw.contains("CAV+ZE0:::Z33"), "must contain frequency CAV");
        assert!(
            raw.contains("CAV+ZD5:::Z23"),
            "must contain transmissibility CAV"
        );

        let AnyMessage::Utilts(m) = Platform::with_all_profiles().parse(&bytes).unwrap() else {
            panic!("expected Utilts");
        };
        assert_eq!(
            m.detect_pruefidentifikator()
                .expect("PID must be detected")
                .as_u32(),
            25004
        );
    }

    /// Schaltzeitdefinition (PID 25006) — definition block SEQ+Z69.
    ///
    /// Validates: SEQ+Z69, DTM+Z44 (change time), CCI+Z52++{code}, switching action.
    #[test]
    fn utilts_schaltzeitdefinition_body_survives_roundtrip() {
        let bytes = UtiltsBuilder::new(Release::new("1.1e"))
            .document_code("Z80")
            .add_vorgang(
                UtiltsVorgang::new("V005", 25006)
                    .definition_code("ZS1")
                    .add_definition_block(
                        UtiltsDefinitionBlock::new("Z69")
                            .change_time("202110070605+00")
                            .definition_code("ZS1")
                            .frequency("Z33")
                            .transmissibility("Z23")
                            .switching_action("Z30"),
                    ),
            )
            .serialize()
            .unwrap();

        let raw = String::from_utf8(bytes.clone()).unwrap();
        assert!(raw.contains("SEQ+Z69"), "must contain SEQ+Z69 Schaltzeit");
        assert!(raw.contains("DTM+Z44:"), "must contain DTM+Z44 change time");
        assert!(raw.contains("CCI+Z52"), "must contain CCI+Z52 type");
        assert!(raw.contains("CAV+ZE0:::Z33"), "must contain frequency");
        assert!(
            raw.contains("CCI+Z58"),
            "must contain CCI+Z58 switching action"
        );

        let AnyMessage::Utilts(m) = Platform::with_all_profiles().parse(&bytes).unwrap() else {
            panic!("expected Utilts");
        };
        assert_eq!(
            m.detect_pruefidentifikator()
                .expect("PID must be detected")
                .as_u32(),
            25006
        );
    }

    /// Leistungskurvendefinition (PID 25007) — definition block SEQ+Z70.
    ///
    /// Validates: SEQ+Z70, DTM+Z45 (change time), CCI+Z53++{code}.
    #[test]
    fn utilts_leistungskurvendefinition_body_survives_roundtrip() {
        let bytes = UtiltsBuilder::new(Release::new("1.1e"))
            .document_code("Z81")
            .add_vorgang(
                UtiltsVorgang::new("V006", 25007)
                    .definition_code("ZL1")
                    .add_definition_block(
                        UtiltsDefinitionBlock::new("Z70")
                            .change_time("202110070605+00")
                            .definition_code("ZL1")
                            .frequency("Z34")
                            .transmissibility("Z23"),
                    ),
            )
            .serialize()
            .unwrap();

        let raw = String::from_utf8(bytes.clone()).unwrap();
        assert!(
            raw.contains("SEQ+Z70"),
            "must contain SEQ+Z70 Leistungskurve"
        );
        assert!(raw.contains("DTM+Z45:"), "must contain DTM+Z45 change time");
        assert!(raw.contains("CCI+Z53"), "must contain CCI+Z53 type");
        assert!(raw.contains("CAV+ZE0:::Z34"), "must contain frequency Z34");

        let AnyMessage::Utilts(m) = Platform::with_all_profiles().parse(&bytes).unwrap() else {
            panic!("expected Utilts");
        };
        assert_eq!(
            m.detect_pruefidentifikator()
                .expect("PID must be detected")
                .as_u32(),
            25007
        );
    }

    /// Z53 qualifier for Viertelstunden usage period.
    #[test]
    fn utilts_usage_period_z53_qualifier_roundtrip() {
        let bytes =
            UtiltsBuilder::new(Release::new("1.1e"))
                .add_vorgang(UtiltsVorgang::new("V007", 25001).add_usage_period(
                    UtiltsUsagePeriod::new(1, "202510012200+00").qualifier("Z53"),
                ))
                .serialize()
                .unwrap();

        let raw = String::from_utf8(bytes).unwrap();
        assert!(
            raw.contains("RFF+Z53::1"),
            "Z53 qualifier must appear in wire"
        );
    }
}
