#!/bin/bash
# dev/init-db.sh — PostgreSQL init for local development.
# Identical schema to demos/nb-stp/init-db.sh; credentials use POSTGRES_USER (dev/dev).
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
    CREATE DATABASE marktd;
    GRANT ALL PRIVILEGES ON DATABASE marktd TO "$POSTGRES_USER";
    CREATE DATABASE processd;
    GRANT ALL PRIVILEGES ON DATABASE processd TO "$POSTGRES_USER";
    CREATE DATABASE invoicd;
    GRANT ALL PRIVILEGES ON DATABASE invoicd TO "$POSTGRES_USER";
    CREATE DATABASE edmd;
    GRANT ALL PRIVILEGES ON DATABASE edmd TO "$POSTGRES_USER";
    CREATE DATABASE obsd;
    GRANT ALL PRIVILEGES ON DATABASE obsd TO "$POSTGRES_USER";
    CREATE DATABASE netzbilanzd;
    GRANT ALL PRIVILEGES ON DATABASE netzbilanzd TO "$POSTGRES_USER";
    CREATE DATABASE sperrd;
    GRANT ALL PRIVILEGES ON DATABASE sperrd TO "$POSTGRES_USER";
    CREATE DATABASE einsd;
    GRANT ALL PRIVILEGES ON DATABASE einsd TO "$POSTGRES_USER";
    CREATE DATABASE tarifbd;
    GRANT ALL PRIVILEGES ON DATABASE tarifbd TO "$POSTGRES_USER";
    CREATE DATABASE billingd;
    GRANT ALL PRIVILEGES ON DATABASE billingd TO "$POSTGRES_USER";
    CREATE DATABASE accountingd;
    GRANT ALL PRIVILEGES ON DATABASE accountingd TO "$POSTGRES_USER";
    CREATE DATABASE vertragd;
    GRANT ALL PRIVILEGES ON DATABASE vertragd TO "$POSTGRES_USER";
    CREATE DATABASE mabis_syncd;
    GRANT ALL PRIVILEGES ON DATABASE mabis_syncd TO "$POSTGRES_USER";
    CREATE DATABASE agentd;
    GRANT ALL PRIVILEGES ON DATABASE agentd TO "$POSTGRES_USER";
EOSQL
