//! ERP command ingestion API.
//!
//! ## Should we use BO4E?
//!
//! **Yes — but BO4E objects are master data, not process messages.**
//!
//! A BO4E `MARKTLOKATION` carries: `marktlokationsId`, `sparte`, `netzgebiet`,
//! `bilanzierungsgebiet`.  That is enough to *identify* a supply point.
//!
//! A UTILMD for Lieferbeginn additionally needs:
//! - **Lieferbeginn-Datum** — not in BO4E; ERP supplies it
//! - **Sender MP-ID** — always our operator MP-ID (`--tenant-id`); ERP never sends this
//! - **Receiver MP-ID (NB)** — resolved by the engine from the MaLo cache via `marktlokationsId`; ERP never sends this
//! - **PID** (55001 vs 55002 vs 55016) — implied by the command name; ERP never sends this
//! - **Message reference** — generated by the engine; ERP never sends this
//!
//! The conclusion: BO4E is the right integration standard (all major German energy
//! ERPs — SAP IS-U, Powercloud, Wilken, Schleupen — implement it), but each
//! command's payload is a **typed, command-specific envelope that embeds BO4E
//! objects alongside the process-specific fields** BO4E doesn't carry.
//!
//! ## Design
//!
//! The ERP names the exact MaKo command it wants to trigger.  The engine
//! resolves the Marktrolle and dispatches the command to the correct workflow,
//! generating EDIFACT.  BO4E objects are never used for routing.
//!
//! **Single-role commands** (e.g. `gpke.lieferbeginn.anmelden` → always `LF`)
//! do not require a `marktrolle` field — the engine infers it from the command
//! name.  **Multi-role commands** (e.g. `wim.geraetewechsel.beauftragen` →
//! `NB` or `MSB`) require `marktrolle` so the engine knows which EDIFACT
//! qualifier and workflow variant to use.
//!
//! The `--marktrollen` startup flag declares which roles this instance is
//! licensed for (e.g. `LF,LFG` for a dual-fuel supplier, `NB,MSB` for an
//! integrated Stadtwerke).  Commands for unlicensed roles are rejected with
//! `422 role_not_configured`.
//!
//! ## Endpoint
//!
//! ### `POST /api/v1/commands`
//!
//! **Request headers**
//!
//! | Header | Required | Notes |
//! |--------|----------|-------|
//! | `Content-Type` | Yes | Must be `application/json` |
//! | `Idempotency-Key` | **Required** | Stable per business request. The accepted response is stored under it for 24 h and replayed verbatim on a retry; reusing one key for a different command or payload is refused with `422 idempotency_key_reuse` |
//!
//! **Request body** — an [`ErpCommand`] envelope with a command-specific payload:
//!
//! ```json
//! {
//!   "command": "gpke.lieferbeginn.anmelden",
//!   "payload": {
//!     "malo_id":            "10001234558",
//!     "lieferbeginn_datum": "2026-10-01"
//!   }
//! }
//! ```
//!
//! For multi-role commands, include `"marktrolle"` to disambiguate:
//!
//! ```json
//! {
//!   "command":    "wim.geraetewechsel.beauftragen",
//!   "marktrolle": "NB",
//!   "payload": { "melo_id": "DE00012345678", "process_date": "20261001", "receiver_mp_id": "9900357000004" }
//! }
//! ```
//!
//! ### Why just `malo_id` and not a full BO4E `MARKTLOKATION` object?
//!
//! A UTILMD S2.x Lieferbeginn on the wire is a complex message: it references
//! the Marktlokation, all associated Messlokationen (MeLos), and the current
//! NB/MSB market-partner assignments valid at the supply-start date.
//!
//! All of that data is **already in the MaLo cache** — the ERP must seed it
//! first via `PUT /admin/malo/{malo_id}` using the NB's `MaloIdentResultPositive`
//! response from the API-Webdienste Strom endpoint.  That cached record carries:
//!
//! - `data_meter_locations` — the MeLo(s) (Messlokationen)
//! - `data_market_location_network_operators` — the NB MP-ID (receiver)
//! - `data_market_location_measuring_point_operators` — the MSB MP-ID
//!
//! The ERP therefore only needs to supply what the cache **cannot** know:
//! the **process trigger** (which MaLo) and the **process-specific date**.
//!
//! `VERTRAG` (Lieferantenvertrag) is an ERP-internal concept and does not
//! appear in the UTILMD wire format; the LF identity is the sender MP-ID.
//!
//! Fields the **engine owns — never supplied by the ERP**:
//! - `sender_party_id` — always our operator party ID (BDEW code / MP-ID / EIC) from `--tenant-id`; the ERP is talking
//!   to us, not the other way round
//! - `receiver_party_id` — resolved by the engine from the MaLo cache / partner
//!   registry using the `marktlokationsId`; the ERP need not know the NB's BDEW code
//! - `pruefidentifikator` — derived from `command` (e.g. `gpke.lieferbeginn.anmelden` → 55001)
//! - `message_ref` — derived by the EDIFACT renderer from the outbox entry's `causation_event_id` (UUID)
//! - `document_date` — set by the EDIFACT renderer to today at dispatch time
//!
//! **Response `202 Accepted`**
//!
//! ```json
//! {
//!   "idempotency_key": "01924f4e-3b4a-7e12-8c47-0022f4b2d3a1",
//!   "command":         "gpke.lieferbeginn.anmelden",
//!   "marktrolle":      "LF",
//!   "status":          "accepted"
//! }
//! ```
//!
//! ## Payload schemas per command
//!
//! Each command defines its own required payload fields.  The BO4E object is
//! always embedded under a named key (e.g. `malo`, `zaehler`, `vertrag`), not
//! at the top level, so additional process fields can sit alongside it cleanly.
//!
//! ## What the ERP must supply vs. what the engine derives
//!
//! | Source | Fields |
//! |--------|--------|
//! | **ERP supplies** | BO4E master data object, process dates, process-specific hints |
//! | **Engine derives** | sender MP-ID (tenant config), receiver MP-ID (MaLo cache / partner registry), PID (command name), message ref (generated) |
//!
//! The receiver MP-ID (NB, GNB, MSB) is looked up from the MaLo cache using the
//! `marktlokationsId`.  If the MaLo is not yet in the cache, the engine returns
//! `422 Unprocessable Entity` with `"error": "malo_not_found"` and the ERP must
//! first seed the MaLo via `PUT /admin/malo/{malo_id}`.
//!
//! ## Payload schemas per command
//!
//! Only fields the ERP genuinely owns are listed here.  MP-IDs resolved by the
//! engine (sender, receiver) are intentionally absent.
//!//! ### What the ERP sends vs. what the engine resolves from the MaLo cache
//!
//! | Resolved by engine (from MaLo cache) | Field |
//! |--------------------------------------|-------|
//! | `data_market_location_network_operators` | NB / GNB MP-ID (receiver) |
//! | `data_market_location_measuring_point_operators` | MSB MP-ID |
//! | `data_meter_locations` | MeLo IDs for UTILMD transactions |
//!
//! The MaLo cache is populated by the ERP via `PUT /admin/malo/{malo_id}` using
//! the NB's `MaloIdentResultPositive` response.  If the MaLo is not in the cache
//! yet, the engine returns `422 malo_not_found`.
//!//! | Command | ERP-supplied payload fields |
//! |---------|----------------------------|
//! | `gpke.lieferbeginn.anmelden` | `malo_id`, `lieferbeginn_datum` |
//! | `gpke.lieferende.anmelden` | `malo_id`, `lieferende_datum` |
//! | `gpke.kuendigung.anmelden` | `malo_id`, `kuendigung_datum`, `alter_lf_mp_id`¹ |
//! | `gpke.sperrung.beauftragen` | `malo_id` |
//! | `gpke.entsperrung.beauftragen` | `malo_id` |
//! | `gpke.sperrung.stornieren` | `malo_id` |
//! | `gpke.sperrung.bestaetigen` | `malo_id`, optional `note`/`reason` |
//! | `gpke.sperrung.fehlgeschlagen` | `malo_id`, **`reason`** (or `note`) — required |
//! | `gpke.abrechnung.annehmen` | `rechnung` (RECHNUNG BO4E) |
//! | `gpke.abrechnung.ablehnen` | `rechnung` (RECHNUNG BO4E), `ablehnungsgrund` |
//! | `geli.lieferbeginn.anmelden` | `malo_id` (Erdgas MaLo), `lieferbeginn_datum` |
//! | `geli.lieferende.anmelden` | `malo_id` (Erdgas MaLo), `lieferende_datum` |
//! | `wim.geraetewechsel.beauftragen` | `melo_id`, `process_date` (YYYYMMDD), `receiver_mp_id`, optional `pid`² |
//! | `mabis.abrechnung.einleiten` | `bilanzierungsgebiet`, `abrechnungszeitraum_von`, `abrechnungszeitraum_bis` |
//!
//! ¹ `alter_lf_mp_id` is required only when the old supplier is a different legal
//!   entity; derived from contract data in the ERP, not from the engine.
//!
//! ² For WiM Gerätewechsel the primary key is the `melo_id` (Messlokation),
//!   not the MaLo.  The MSB and NB MP-IDs are resolved from the MeLo cache entry.
//!
//! ### Invoicing commands (`gpke.abrechnung.*`)
//!
//! Billing commands use a BO4E `RECHNUNG` object because the invoice itself
//! is the master data — there is no separate cache to look up.  The ERP
//! supplies the full invoice payload.
//!
//! ## Marktrolle
//!
//! | Value | Bedeutung |
//! |-------|-----------|
//! | `NB` | Netzbetreiber (electricity DSO) |
//! | `GNB` | Gasnetzbetreiber (gas DSO) |
//! | `LF` | Lieferant (electricity supplier) |
//! | `LFG` | Lieferant Gas (gas supplier) |
//! | `MSB` | Messstellenbetreiber |
//! | `BKV` | Bilanzkreisverantwortlicher |
//! | `ÜNB` | Übertragungsnetzbetreiber |
//!
//! ## Command registry
//!
//! | Command | Marktrolle | Process | PIDs |
//! |---------|-----------|---------|------|
//! | `gpke.lieferbeginn.anmelden` | `LF` | GPKE Lieferbeginn Strom | 55001 |
//! | `gpke.lieferbeginn.bestaetigen` | `NB` | GPKE NB bestätigt Lieferbeginn | 55002/55003 |
//! | `gpke.lieferende.anmelden` | `LF` | GPKE Lieferende Strom | 55004 |
//! | `gpke.lieferende.bestaetigen` | `NB` | GPKE NB bestätigt Lieferende | 55005/55006 |
//! | `gpke.kuendigung.anmelden` | `LF` | GPKE Kündigung Lieferbeginn | 55016 |
//! | `gpke.sperrung.beauftragen` | `LF` | GPKE Sperrauftrag (LF → NB; ORDERS) | 17115 |
//! | `gpke.entsperrung.beauftragen` | `LF` | GPKE Entsperrauftrag (LF → NB; ORDERS) | 17117 |
//! | `gpke.sperrung.stornieren` | `LF` | GPKE Stornierung Sperrauftrag (ORDCHG) | 39000 |
//! | `gpke.sperrung.bestaetigen` | `NB` | NB meldet Ausführung → IFTSTA 21039 | 17115/17117 |
//! | `gpke.sperrung.fehlgeschlagen` | `NB` | NB meldet Nichtausführung → IFTSTA 21039 | 17115/17117 |
//! | `gpke.abrechnung.annehmen` | `NB` | GPKE Netznutzungsabrechnung | 31002 |
//! | `gpke.abrechnung.ablehnen` | `NB` | GPKE Abrechnungsstreit | 31001/31002 |
//! | `geli.lieferbeginn.anmelden` | `LFG` | GeLi Gas Lieferbeginn | 44001 |
//! | `geli.lieferbeginn.bestaetigen` | `GNB` | GeLi Gas NB bestätigt | 44002/44003 |
//! | `geli.lieferende.anmelden` | `LFG` | GeLi Gas Lieferende | 44002 |
//! | `geli.lieferende.bestaetigen` | `GNB` | GeLi Gas NB bestätigt | 44005/44006 |
//! | `wim.geraetewechsel.beauftragen` | `NB`/`MSB` | WiM Messstellenbetrieb | 55039, 55042, 55051, 55168 |
//! | `wim.geraetewechsel.bestaetigen` | `MSB` | WiM Messstellenbetrieb abgeschlossen | 55039, 55042, 55051, 55168 |
//! | `mabis.abrechnung.einleiten` | `BKV` | MABIS Bilanzkreisabrechnung Strom | 13003 |
//! | `mabis.abrechnung.daten-einreichen` | `BKV` | MABIS Messdaten liefern | 13003 |
//! | `mabis.abrechnung.begleichen` | `BKV`/`ÜNB` | MABIS Abrechnung begleichen | 13003 |

use std::sync::Arc;

use axum::{
    Router,
    extract::{DefaultBodyLimit, State},
    http::StatusCode,
    response::{IntoResponse, Json},
    routing::post,
};
use mako_engine::{
    deadline::Deadline,
    ids::{ProcessId, TenantId},
    marktrolle::{DeploymentRoles, LicensingError, Marktrolle, resolve_role},
    metrics::EngineMetrics,
    registry::ProcessRegistry as _,
    types::{
        BikoId, BillingPeriod, BkvId, MaLo, MarktpartnerCode, MeLo, MessageRef, Pruefidentifikator,
    },
    version::WorkflowId,
    workflow::OccupiesBusinessKey as _,
};
use mako_gabi_gas::{GaBiGasInvoicWorkflow, INVOIC_WORKFLOW_NAME as GABI_GAS_INVOIC_WORKFLOW_NAME};
use mako_geli_gas::{
    GELI_GAS_DATENABRUF_WORKFLOW_NAME, GELI_GAS_SPERRPROZESSE_INVOIC_WORKFLOW_NAME,
    GasSupplierChangeCommand, GeliGasDatanabrufCommand, GeliGasDatanabrufWorkflow,
    GeliGasLfAnmeldungCommand, GeliGasLfAnmeldungWorkflow, GeliGasSperrprozesseInvoicWorkflow,
    GeliGasSupplierChangeWorkflow, LF_ANMELDUNG_ANFRAGE_PIDS,
};
use mako_gpke::{
    AnkuendigungZuordnungLfCommand, GpkeAbrechnungWorkflow, GpkeAnkuendigungZuordnungLfWorkflow,
    GpkeLfAbmeldungWorkflow, GpkeLfAnmeldungWorkflow, GpkeSupplierChangeWorkflow,
    LfAnmeldungCommand, SupplierChangeCommand,
};
use mako_gpke::{
    GpkeSperrungLfWorkflow, GpkeSperrungWorkflow, SPERRUNG_LF_ANFRAGE_PIDS,
    SPERRUNG_LF_ANTWORT_WINDOW_LABEL, SPERRUNG_LF_WORKFLOW_NAME, SPERRUNG_WORKFLOW_NAME,
    SperrungCommand, SperrungLfCommand,
};
use mako_invoic::InvoicCommand;
use mako_mabis::{
    BillingCommand, BillingVersion, DataStatus, IFTSTA_DATENSTATUS_PID,
    IFTSTA_PIDS as MABIS_IFTSTA_PIDS, MabisBillingWorkflow, PRUEFMITTEILUNG_DEADLINE_LABEL,
};
use mako_markt::repository::{
    NetzzugangAktion, NetzzugangAntrag, NetzzugangAntragTyp, NetzzugangStatus,
};
use mako_wim::invoic::WimInvoicWorkflow;
use mako_wim::steuerungsauftrag::{SteuerungsauftragCommand, WimSteuerungsauftragWorkflow};
use mako_wim::{DeviceChangeCommand, WimDeviceChangeWorkflow};
use mako_wim::{PreisanfrageCommand, WimPreisanfrageWorkflow};
use rubo4e::identifiers::{MaloId, MeloId};
use serde::{Deserialize, Serialize};
use tracing::info;
use utoipa::ToSchema;

use crate::cedar_authz::{CedarAuthorizer, CommandResource};
use crate::malo_cache::{MaloIdentResultCache, SlateDbMaloCache};

// ── Identifier extraction helpers ─────────────────────────────────────────────

/// Extract and validate a `malo_id` field from an ERP JSON payload.
///
/// Returns a 422-ready [`DispatchError::InvalidPayload`] when:
/// - the `malo_id` key is absent or not a JSON string, or
/// - the string fails BDEW MaLo-ID validation (11 digits + alternating-weight
///   checksum, per BDEW MaLo-ID spec).
///
/// Returns the validated identifier as a domain-typed
/// [`mako_engine::types::MaLo`] (constructed from the rubo4e-validated value)
/// so the type survives past the boundary; string sinks use `.as_str()`.
fn extract_malo_id(payload: &serde_json::Value) -> Result<MaLo, DispatchError> {
    let s = payload
        .get("malo_id")
        .and_then(|v| v.as_str())
        .ok_or_else(|| {
            DispatchError::InvalidPayload(
                "payload must contain \"malo_id\" (11-digit Marktlokations-ID)".into(),
            )
        })?;
    s.parse::<MaloId>()
        .map(|id| MaLo::new(id.as_ref()))
        .map_err(|e| DispatchError::InvalidPayload(format!("invalid malo_id {s:?}: {e}")))
}

/// Extract and validate a `melo_id` field from an ERP JSON payload.
///
/// Returns a 422-ready [`DispatchError::InvalidPayload`] when:
/// - the `melo_id` key is absent or not a JSON string, or
/// - the string fails BDEW MeLo-ID validation (ISO 3166-1 alpha-2 prefix
///   + 31 digits, per BO4E / WiM spec).
fn extract_melo_id(payload: &serde_json::Value) -> Result<MeLo, DispatchError> {
    let s = payload
        .get("melo_id")
        .and_then(|v| v.as_str())
        .ok_or_else(|| {
            DispatchError::InvalidPayload(
                "payload must contain \"melo_id\" (Messlokations-ID, e.g. DE000…)".into(),
            )
        })?;
    s.parse::<MeloId>()
        .map(|id| MeLo::new(id.as_ref()))
        .map_err(|e| DispatchError::InvalidPayload(format!("invalid melo_id {s:?}: {e}")))
}

/// Extract a `invoice_ref` field from an ERP JSON payload.
///
/// Used for billing commands (`gpke.abrechnung.annehmen`/`ablehnen`) where the
/// business key is the INVOIC message-reference rather than a MaLo-ID.
/// Returns a 422-ready [`DispatchError::InvalidPayload`] when the field is absent.
fn extract_invoice_ref(payload: &serde_json::Value) -> Result<String, DispatchError> {
    payload
        .get("invoice_ref")
        .and_then(|v| v.as_str())
        .filter(|s| !s.is_empty())
        .map(str::to_owned)
        .ok_or_else(|| {
            DispatchError::InvalidPayload(
                "payload must contain \"invoice_ref\" (EDIFACT INVOIC message reference)".into(),
            )
        })
}

// ── Submodules ────────────────────────────────────────────────────────────────
//
// `types`, `handler`, and `registry` hold the command-API machinery; the
// remaining submodules hold one market-communication domain each. Everything
// is re-exported here so the flat `crate::commands_api::*` paths keep working.

mod esa;
mod gabi_gas;
mod geli_gas;
mod gpke;
mod handler;
pub mod idempotency;
mod iftsta;
mod mabis;
mod netzbilanz;
mod netzzugang;
mod registry;
mod types;
mod wim;

pub use handler::*;
pub use registry::*;
pub use types::*;

use esa::*;
use gabi_gas::*;
use geli_gas::*;
use gpke::*;
use iftsta::*;
use mabis::*;
use netzbilanz::*;
use netzzugang::*;
use wim::*;

/// Return the current BDEW format-version `WorkflowId` for `gpke-lf-anmeldung`.
///
/// Uses the most recent format version from the compiled `edi-energy` profile
/// registry — the same strategy as the AS4 ingest layer.
fn current_workflow_id() -> WorkflowId {
    // Prefer the latest compiled FV.  Falls back to a known good FV if
    // the registry is somehow empty (should never happen in production).
    WorkflowId::new(
        mako_gpke::lf_anmeldung::WORKFLOW_NAME,
        latest_format_version(),
    )
}

/// Return the latest BDEW format version known to the compiled `edi-energy` registry.
fn latest_format_version() -> mako_engine::version::FormatVersion {
    edi_energy::registry::ReleaseRegistry::global()
        .format_versions()
        .into_iter()
        .filter_map(|s| mako_engine::version::FormatVersion::parse(&s).ok())
        .max()
        .unwrap_or_else(|| {
            mako_engine::version::FormatVersion::parse("FV2025-10-01")
                .expect("fallback FV is valid")
        })
}

// ── Duplicate guard ───────────────────────────────────────────────────────────

/// Return the process that still occupies `business_key`, if any.
///
/// This is the check every `anmelden`-style dispatcher runs before spawning a
/// process, and it must not be written as "does the correlation index contain
/// an entry?". The index is append-only — `register_correlated` writes on spawn
/// and nothing calls `remove_correlated` — so presence proves a process once
/// existed, never that one is still running. Refusing on presence blocked a MaLo
/// permanently after its first process, including the routine flow where the
/// counterpart rejects and the sender submits a correction.
///
/// So each candidate is rehydrated and asked
/// [`OccupiesBusinessKey::occupies_business_key`]. That also makes the guard
/// self-healing: a stale index entry stops blocking as soon as its process
/// reaches a terminal state, with no cleanup job to run or to forget.
///
/// # Errors
///
/// Propagates store failures from the correlation lookup or the state replay.
async fn find_occupying_process<W>(
    state: &CommandsApiState,
    business_key: &str,
    workflow_name: &str,
) -> Result<Option<ProcessId>, DispatchError>
where
    W: mako_engine::workflow::Workflow,
    W::State: mako_engine::workflow::OccupiesBusinessKey,
{
    let existing = state
        .store
        .as_process_registry()
        .lookup_correlated(state.tenant_id, business_key)
        .await
        .map_err(DispatchError::Engine)?;

    for identity in existing
        .into_iter()
        .filter(|id| id.workflow_id.name.as_ref() == workflow_name)
    {
        let process_id = identity.process_id;
        let candidate = mako_engine::process::Process::<
            W,
            Arc<mako_engine::store_slatedb::SlateDbStore>,
        >::from_identity(Arc::clone(&state.store), identity);
        if candidate
            .state()
            .await
            .map_err(DispatchError::Engine)?
            .occupies_business_key()
        {
            return Ok(Some(process_id));
        }
        // Retire the stale index entry now that replay has *proved* the process
        // finished. This is what keeps the index's meaning true — "processes that
        // may still be resumed by this business key" — and it is not merely
        // housekeeping:
        //
        // `dispatch_to_process_keyed` requires exactly one match for a business
        // key and fails with `AmbiguousProcess` on two. Allowing a second process
        // (which is the whole point of this guard) would therefore break every
        // follow-up command — `bestaetigen`, `ablehnen`, `aktivieren` — on that
        // MaLo. Pruning here means that by the time a replacement process is
        // registered, the finished one is already gone, so the resume path still
        // sees exactly one.
        //
        // A failure to prune is logged, not propagated: the guard's answer is
        // already known and correct, and refusing a legitimate Anmeldung because
        // a cleanup write failed would be the worse outcome. The next dispatch
        // retries the prune.
        if let Err(e) = state
            .store
            .as_process_registry()
            .remove_correlated(state.tenant_id, business_key, process_id)
            .await
        {
            tracing::warn!(
                business_key,
                workflow_name,
                %process_id,
                error = %e,
                "duplicate guard: could not retire the finished process's correlation entry",
            );
        } else {
            tracing::debug!(
                business_key,
                workflow_name,
                %process_id,
                "duplicate guard: prior process has finished — entry retired, not blocking",
            );
        }
    }
    Ok(None)
}

// ── Phase 3 — Response command dispatchers ────────────────────────────────────
//
// These dispatchers look up an active process by MaLo / MeLo business key
// using the `ProcessRegistry` correlated index and route the ERP response
// command into the appropriate workflow.

/// Look up the single active process for `business_key` under `workflow_name`
/// and execute `make_command` against it.
///
/// Returns `ProcessNotFound` when no active process exists and `AmbiguousProcess`
/// when more than one active process is found (data integrity violation).
async fn dispatch_to_process<W, F>(
    state: &CommandsApiState,
    business_key: &str,
    workflow_name: &'static str,
    make_command: F,
) -> Result<DispatchOutcome, DispatchError>
where
    W: mako_engine::workflow::Workflow,
    W::Command: mako_engine::workflow::CommandPayload + Clone,
    W::State: Default + serde::Serialize,
    F: FnOnce() -> W::Command,
{
    dispatch_to_process_keyed::<W, F>(state, business_key, workflow_name, &[], make_command).await
}

/// [`dispatch_to_process`] that additionally indexes the resumed process under
/// `extra_keys`.
///
/// The ESA registers its process under the Belegnummer of each outbound
/// REQOTE/ORDERS/ORDCHG it sends, so the MSB's answer — which carries no LOC —
/// can be correlated back by the reference that PID's own Zuordnungsschlüssel
/// names (`AAV`, `ON` or `ACW`; see [`mako_wim::esa::korrelation`]).
async fn dispatch_to_process_keyed<W, F>(
    state: &CommandsApiState,
    business_key: &str,
    workflow_name: &'static str,
    extra_keys: &[&str],
    make_command: F,
) -> Result<DispatchOutcome, DispatchError>
where
    W: mako_engine::workflow::Workflow,
    W::Command: mako_engine::workflow::CommandPayload + Clone,
    W::State: Default + serde::Serialize,
    F: FnOnce() -> W::Command,
{
    // ── Lookup active process(es) for business key ────────────────────────────
    let registry = state.store.as_process_registry();
    let identities = registry
        .lookup_correlated(state.tenant_id, business_key)
        .await
        .map_err(|e| {
            DispatchError::Engine(mako_engine::error::EngineError::store(e.to_string()))
        })?;

    // Filter to identities belonging to the target workflow.
    let matching: Vec<_> = identities
        .into_iter()
        .filter(|id| id.workflow_id.name.as_ref() == workflow_name)
        .collect();

    let identity = match matching.len() {
        0 => {
            return Err(DispatchError::ProcessNotFound {
                business_key: business_key.to_owned(),
                workflow_name,
            });
        }
        1 => matching.into_iter().next().expect("len == 1"),
        n => {
            return Err(DispatchError::AmbiguousProcess {
                business_key: business_key.to_owned(),
                count: n,
            });
        }
    };

    let process_id = identity.process_id;
    let identity_for_keys = identity.clone();
    let process = mako_engine::process::Process::<
        W,
        Arc<mako_engine::store_slatedb::SlateDbStore>,
    >::from_identity(Arc::clone(&state.store), identity);

    let domain_cmd = make_command();
    process
        .execute_and_enqueue_with_snapshot_and_retry(
            domain_cmd,
            3,
            &state.snapshot_store,
            state.snapshot_interval,
        )
        .await?;

    // Index the process under any outbound order Belegnummern (best-effort).
    for key in extra_keys.iter().filter(|k| !k.is_empty()) {
        let _ = registry
            .register_correlated(state.tenant_id, key, process_id, identity_for_keys.clone())
            .await;
    }

    Ok(DispatchOutcome::Dispatched { process_id })
}

/// [`dispatch_to_process`] where the command depends on the process's own
/// state.
///
/// Needed when a default can only be resolved from what the process is
/// answering: the WiM MSB-Wechsel Antwortcode comes from the inbound PID's
/// Entscheidungsbaum, and the caller of the REST command knows the MeLo but not
/// which of the four processes is running on it.
async fn dispatch_to_process_with_state<W, F>(
    state: &CommandsApiState,
    business_key: &str,
    workflow_name: &'static str,
    make_command: F,
) -> Result<DispatchOutcome, DispatchError>
where
    W: mako_engine::workflow::Workflow,
    W::Command: mako_engine::workflow::CommandPayload + Clone,
    W::State: Default + serde::Serialize,
    F: FnOnce(&W::State) -> Result<W::Command, DispatchError>,
{
    let registry = state.store.as_process_registry();
    let identities = registry
        .lookup_correlated(state.tenant_id, business_key)
        .await
        .map_err(|e| {
            DispatchError::Engine(mako_engine::error::EngineError::store(e.to_string()))
        })?;
    let matching: Vec<_> = identities
        .into_iter()
        .filter(|id| id.workflow_id.name.as_ref() == workflow_name)
        .collect();
    let identity = match matching.len() {
        0 => {
            return Err(DispatchError::ProcessNotFound {
                business_key: business_key.to_owned(),
                workflow_name,
            });
        }
        1 => matching.into_iter().next().expect("len == 1"),
        n => {
            return Err(DispatchError::AmbiguousProcess {
                business_key: business_key.to_owned(),
                count: n,
            });
        }
    };
    let process_id = identity.process_id;
    let process = mako_engine::process::Process::<
        W,
        Arc<mako_engine::store_slatedb::SlateDbStore>,
    >::from_identity(Arc::clone(&state.store), identity);

    let current = process.state().await?;
    let domain_cmd = make_command(&current)?;
    process
        .execute_and_enqueue_with_snapshot_and_retry(
            domain_cmd,
            3,
            &state.snapshot_store,
            state.snapshot_interval,
        )
        .await?;

    Ok(DispatchOutcome::Dispatched { process_id })
}

// ── Tests ─────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    fn roles(r: &[&str]) -> Vec<String> {
        r.iter().map(|s| s.to_string()).collect()
    }

    // ── Single-role commands ──────────────────────────────────────────────────

    #[test]
    fn single_role_inferred_without_marktrolle() {
        let role = validate_command("gpke.lieferbeginn.anmelden", None, &roles(&["LF"])).unwrap();
        assert_eq!(role, "LF");
    }

    #[test]
    fn single_role_asserted_marktrolle_is_ignored() {
        // For single-role commands the asserted marktrolle is always ignored.
        // An ERP connector that always sends marktrolle should not be rejected.
        let role =
            validate_command("gpke.lieferbeginn.anmelden", Some("NB"), &roles(&["LF"])).unwrap();
        assert_eq!(role, "LF"); // canonical role, not what ERP asserted
    }

    #[test]
    fn nb_role_resolved_for_bestaetigen() {
        let role =
            validate_command("gpke.lieferbeginn.bestaetigen", None, &roles(&["NB"])).unwrap();
        assert_eq!(role, "NB");
    }

    #[test]
    fn gnb_role_resolved_for_gas_bestaetigen() {
        let role =
            validate_command("geli.lieferbeginn.bestaetigen", None, &roles(&["GNB"])).unwrap();
        assert_eq!(role, "GNB");
    }

    #[test]
    fn lfg_role_resolved_for_gas_lieferbeginn() {
        let role = validate_command("geli.lieferbeginn.anmelden", None, &roles(&["LFG"])).unwrap();
        assert_eq!(role, "LFG");
    }

    // ── Instance configuration enforcement ───────────────────────────────────

    #[test]
    fn lf_instance_may_issue_lf_commands() {
        let lf = roles(&["LF"]);
        assert!(validate_command("gpke.lieferbeginn.anmelden", None, &lf).is_ok());
        assert!(validate_command("gpke.lieferende.anmelden", None, &lf).is_ok());
        assert!(validate_command("gpke.kuendigung.anmelden", None, &lf).is_ok());
    }

    #[test]
    fn nb_instance_may_not_issue_lf_command() {
        // Resolves to LF; NB is not configured → RoleNotConfigured.
        let nb = roles(&["NB"]);
        assert!(validate_command("gpke.lieferbeginn.anmelden", None, &nb).is_err());
    }

    #[test]
    fn lf_instance_may_not_issue_nb_command() {
        // Resolves to NB; LF is not configured for NB role.
        let lf = roles(&["LF"]);
        assert!(validate_command("gpke.lieferbeginn.bestaetigen", None, &lf).is_err());
    }

    #[test]
    fn dual_fuel_instance_permits_strom_and_gas() {
        let lf_lfg = roles(&["LF", "LFG"]);
        assert!(validate_command("gpke.lieferbeginn.anmelden", None, &lf_lfg).is_ok());
        assert!(validate_command("geli.lieferbeginn.anmelden", None, &lf_lfg).is_ok());
    }

    #[test]
    fn strom_only_instance_blocks_gas_commands() {
        let lf = roles(&["LF"]);
        assert!(validate_command("geli.lieferbeginn.anmelden", None, &lf).is_err());
    }

    #[test]
    fn gas_only_instance_blocks_strom_commands() {
        let lfg = roles(&["LFG"]);
        assert!(validate_command("gpke.lieferbeginn.anmelden", None, &lfg).is_err());
    }

    // ── Multi-role commands ───────────────────────────────────────────────────

    #[test]
    fn multi_role_requires_marktrolle() {
        // wim.geraetewechsel.beauftragen → NB or MSB; no marktrolle → err.
        assert!(validate_command("wim.geraetewechsel.beauftragen", None, &roles(&["NB"])).is_err());
    }

    #[test]
    fn nb_may_initiate_geraetewechsel() {
        assert!(
            validate_command(
                "wim.geraetewechsel.beauftragen",
                Some("NB"),
                &roles(&["NB"])
            )
            .is_ok()
        );
    }

    #[test]
    fn msb_may_initiate_geraetewechsel() {
        assert!(
            validate_command(
                "wim.geraetewechsel.beauftragen",
                Some("MSB"),
                &roles(&["MSB"])
            )
            .is_ok()
        );
    }

    #[test]
    fn lf_may_not_initiate_geraetewechsel() {
        // LF is not in the permitted set → RoleNotPermitted.
        assert!(
            validate_command(
                "wim.geraetewechsel.beauftragen",
                Some("LF"),
                &roles(&["LF"])
            )
            .is_err()
        );
    }

    /// The Sparte-neutral Storno must be answerable by everyone it can reach.
    ///
    /// PID 31004 cancels an invoice from *any* billing family (INVOIC AHB
    /// § 3.1.2 — GPKE, MMM, WiM Strom + Gas, Kapazität, AWH, GeLi), so whoever
    /// could receive the original can receive its cancellation. Its permitted
    /// set is the union of the families' own sets, derived here rather than
    /// trusted: a role missing from the hand-written list cannot answer a
    /// cancellation of an invoice it received itself.
    #[test]
    fn the_storno_answers_every_family_it_cancels() {
        let family_commands = [
            "gpke.abrechnung.annehmen",
            "wim.rechnung.annehmen",
            "gabi.rechnung.annehmen",
            "invoic.sonstige-leistung.annehmen",
        ];
        let mut required: Vec<Marktrolle> = Vec::new();
        for command in family_commands {
            let d = COMMAND_REGISTRY
                .iter()
                .find(|d| d.name == command)
                .unwrap_or_else(|| panic!("{command} is registered"));
            for role in d.permitted_roles {
                if !required.contains(role) {
                    required.push(*role);
                }
            }
        }

        let storno = COMMAND_REGISTRY
            .iter()
            .find(|d| d.name == "invoic.stornorechnung.annehmen")
            .expect("the Storno command is registered");
        for role in &required {
            assert!(
                storno.permitted_roles.contains(role),
                "{role:?} can receive a billing invoice but not its Stornorechnung"
            );
        }
    }

    /// The GaBi Gas billing family reaches **two** roles, and the command that
    /// answers it must permit both.
    ///
    /// One workflow settles all three PIDs: the MGV receives the aggregated
    /// MMM-Rechnung 31007/31008, the BKV the Kapazitätsrechnung 31010. A
    /// descriptor naming one PID must still permit both, or the recipient of
    /// the other cannot answer its own invoices.
    #[test]
    fn the_gabi_billing_family_is_answerable_by_both_of_its_recipients() {
        for role in ["MGV", "BKV"] {
            for command in ["gabi.rechnung.annehmen", "gabi.rechnung.ablehnen"] {
                assert!(
                    validate_command(command, Some(role), &roles(&[role])).is_ok(),
                    "{role} receives a GaBi Gas invoice and must be able to answer it \
                     with {command}"
                );
            }
        }
    }

    /// …and not by a role that receives none of them.
    #[test]
    fn a_supplier_may_not_answer_a_gabi_gas_invoice() {
        assert!(validate_command("gabi.rechnung.annehmen", Some("LF"), &roles(&["LF"])).is_err());
    }

    #[test]
    fn nb_msb_instance_permits_both_wim_roles() {
        let nb_msb = roles(&["NB", "MSB"]);
        assert!(validate_command("wim.geraetewechsel.beauftragen", Some("NB"), &nb_msb).is_ok());
        assert!(validate_command("wim.geraetewechsel.beauftragen", Some("MSB"), &nb_msb).is_ok());
    }

    #[test]
    fn nb_only_instance_may_not_act_as_msb() {
        let nb = roles(&["NB"]);
        // MSB is permitted by the registry but not configured on this instance.
        assert!(validate_command("wim.geraetewechsel.beauftragen", Some("MSB"), &nb).is_err());
    }

    // ── BKV / ÜNB ────────────────────────────────────────────────────────────

    #[test]
    fn bkv_single_role_commands_infer_role() {
        // einleiten and daten-einreichen are single-role (BKV only).
        assert_eq!(
            validate_command("mabis.abrechnung.einleiten", None, &roles(&["BKV"])).unwrap(),
            "BKV"
        );
        assert_eq!(
            validate_command("mabis.abrechnung.daten-einreichen", None, &roles(&["BKV"])).unwrap(),
            "BKV"
        );
    }

    #[test]
    fn begleichen_is_multi_role_bkv_and_uenb() {
        // begleichen permits BKV and ÜNB → marktrolle required.
        assert!(
            validate_command("mabis.abrechnung.begleichen", Some("BKV"), &roles(&["BKV"])).is_ok()
        );
        assert!(
            validate_command("mabis.abrechnung.begleichen", Some("ÜNB"), &roles(&["ÜNB"])).is_ok()
        );
        assert!(validate_command("mabis.abrechnung.begleichen", None, &roles(&["BKV"])).is_err());
    }

    #[test]
    fn uenb_instance_may_not_initiate_mabis() {
        // einleiten resolves to BKV; ÜNB instance not configured for BKV.
        let uenb = roles(&["ÜNB"]);
        assert!(validate_command("mabis.abrechnung.einleiten", None, &uenb).is_err());
    }

    // ── Unknown command ───────────────────────────────────────────────────────

    #[test]
    fn unknown_command_is_rejected() {
        assert!(validate_command("gpke.nonexistent.action", None, &roles(&["LF"])).is_err());
    }

    // ── MABIS billing dispatch (F-006) ──────────────────────────────────────
    //
    // These tests exercise the full `dispatch_command` path for the three MABIS
    // billing commands.  Before F-001 was fixed, all three fell through to the
    // `NotImplemented` catch-all; this module is the regression gate.

    /// Build a minimal `CommandsApiState` backed by an in-memory store.
    ///
    /// Uses the same wiring as `main.rs` but with `SlateDbStore::open_in_memory()`
    /// so no filesystem setup is required.  Cedar keys are omitted — dispatch
    /// tests call `dispatch_command` directly, bypassing the HTTP auth layer.
    async fn mabis_dispatch_state(marktrollen: &[&str]) -> CommandsApiState {
        let store = mako_engine::store_slatedb::SlateDbStore::open_in_memory()
            .await
            .expect("open in-memory SlateDB");
        let cedar = Arc::new(
            CedarAuthorizer::new(
                vec![],
                None,
                None,
                None,
                crate::cedar_authz::DefaultPolicy::PermitAll,
            )
            .expect("cedar build"),
        );
        CommandsApiState {
            tenant_id: TenantId::from_party_id("4033872000022"),
            sender_party_id: "4033872000022".to_owned(),
            configured_marktrollen: marktrollen.iter().map(|s| s.to_uppercase()).collect(),
            max_body_bytes: 1_048_576,
            snapshot_interval: 100,
            cedar,
            snapshot_store: store.as_snapshot_store(),
            malo_cache: Arc::new(SlateDbMaloCache::new(store.clone())),
            maloid_result_cache: MaloIdentResultCache::new(store.clone()),
            store: Arc::new(store),
            marktd_client: None,
        }
    }

    /// `mabis.abrechnung.einleiten` must spawn a new billing process
    /// (`DispatchOutcome::Spawned`), not report `NotImplemented`.
    #[tokio::test]
    async fn dispatch_mabis_einleiten_spawns_process() {
        let state = mabis_dispatch_state(&["BKV"]).await;
        let payload = serde_json::json!({
            "billing_period": "2025-09",
            "bkv_id":         "4033872000022",
            "biko_id":        "10YDE-VE-TRANSMIX",
            "version":        "vorlaeufig",
        });
        let outcome = dispatch_command(&state, "mabis.abrechnung.einleiten", &payload)
            .await
            .expect("einleiten must succeed");
        assert!(
            matches!(outcome, DispatchOutcome::Spawned { .. }),
            "first einleiten must return Spawned; got: {outcome:?}"
        );
    }

    /// Duplicate `einleiten` for the same BKV/period must be idempotent.
    ///
    /// The second call returns `Dispatched` (reuses the existing process)
    /// rather than spawning a second one.
    #[tokio::test]
    async fn dispatch_mabis_einleiten_is_idempotent() {
        let state = mabis_dispatch_state(&["BKV"]).await;
        let payload = serde_json::json!({
            "billing_period": "2025-09",
            "bkv_id":         "4033872000022",
            "biko_id":        "10YDE-VE-TRANSMIX",
            "version":        "vorlaeufig",
        });
        dispatch_command(&state, "mabis.abrechnung.einleiten", &payload)
            .await
            .expect("first einleiten");
        let second = dispatch_command(&state, "mabis.abrechnung.einleiten", &payload)
            .await
            .expect("second einleiten must be idempotent");
        assert!(
            matches!(second, DispatchOutcome::Dispatched { .. }),
            "duplicate einleiten must return Dispatched; got: {second:?}"
        );
    }

    /// `mabis.abrechnung.daten-einreichen` must route to an existing process.
    ///
    /// Regression guard for F-001: `daten-einreichen` returned `NotImplemented`
    /// before the dispatch arm was added.
    #[tokio::test]
    async fn dispatch_mabis_daten_einreichen_routes_to_process() {
        let state = mabis_dispatch_state(&["BKV"]).await;
        // Seed the process.
        dispatch_command(
            &state,
            "mabis.abrechnung.einleiten",
            &serde_json::json!({
                "billing_period": "2025-09",
                "bkv_id":         "4033872000022",
                "biko_id":        "10YDE-VE-TRANSMIX",
                "version":        "vorlaeufig",
            }),
        )
        .await
        .expect("einleiten");
        // Send positive Prüfmitteilung.
        let outcome = dispatch_command(
            &state,
            "mabis.abrechnung.daten-einreichen",
            &serde_json::json!({
                "bkv_id":         "4033872000022",
                "billing_period": "2025-09",
                "reject":         false,
            }),
        )
        .await
        .expect("daten-einreichen must succeed");
        assert!(
            matches!(outcome, DispatchOutcome::Dispatched { .. }),
            "daten-einreichen must return Dispatched; got: {outcome:?}"
        );
    }

    /// `mabis.abrechnung.begleichen` must route Datenstatus to an existing process.
    ///
    /// Regression guard for F-001: `begleichen` returned `NotImplemented` before
    /// the dispatch arm was added.
    #[tokio::test]
    async fn dispatch_mabis_begleichen_routes_to_process() {
        let state = mabis_dispatch_state(&["BKV"]).await;
        let bkv = "4033872000022";
        let period = "2025-09";
        // Seed + advance to PruefmitteilungSent.
        dispatch_command(
            &state,
            "mabis.abrechnung.einleiten",
            &serde_json::json!({
                "billing_period": period,
                "bkv_id":         bkv,
                "biko_id":        "10YDE-VE-TRANSMIX",
                "version":        "vorlaeufig",
            }),
        )
        .await
        .expect("einleiten");
        dispatch_command(
            &state,
            "mabis.abrechnung.daten-einreichen",
            &serde_json::json!({ "bkv_id": bkv, "billing_period": period, "reject": false }),
        )
        .await
        .expect("daten-einreichen");
        // Now receive Datenstatus → Settled.
        let outcome = dispatch_command(
            &state,
            "mabis.abrechnung.begleichen",
            &serde_json::json!({
                "bkv_id":         bkv,
                "billing_period": period,
                "data_status":    "abgerechnete_daten",
            }),
        )
        .await
        .expect("begleichen must succeed");
        assert!(
            matches!(outcome, DispatchOutcome::Dispatched { .. }),
            "begleichen must return Dispatched; got: {outcome:?}"
        );
    }

    /// `netzzugang.energysharing.registrieren` (§20b Abs. 2 Nr. 3) must
    /// validate the payload, enqueue a `NetzzugangAntrag` outbox message and
    /// return `Spawned` — the sender then delivers it with outbox semantics.
    #[tokio::test]
    async fn dispatch_netzzugang_registrierung_enqueues_outbox_antrag() {
        use mako_engine::outbox::OutboxStore as _;
        let state = mabis_dispatch_state(&["LF"]).await;

        // Missing required fields → InvalidPayload.
        let err = dispatch_command(
            &state,
            "netzzugang.energysharing.registrieren",
            &serde_json::json!({ "netzanschluss_id": "NA-1" }),
        )
        .await
        .expect_err("incomplete payload must be rejected");
        assert!(matches!(err, DispatchError::InvalidPayload(_)), "{err:?}");

        // Complete payload → Spawned + one outbox message with the antrag.
        let outcome = dispatch_command(
            &state,
            "netzzugang.energysharing.registrieren",
            &serde_json::json!({
                "netzanschluss_id": "NA-1",
                "nb_mp_id": "9900001000001",
                "antragsteller_ref": "kunde-42",
                "details": { "vereinbarung_ref": "ES-2026-001" },
            }),
        )
        .await
        .expect("registrieren must succeed");
        assert!(
            matches!(outcome, DispatchOutcome::Spawned { .. }),
            "{outcome:?}"
        );

        let pending = state
            .store
            .pending(
                10,
                time::OffsetDateTime::now_utc() + time::Duration::minutes(1),
            )
            .await
            .expect("outbox pending");
        let msg = pending
            .iter()
            .find(|m| m.message_type.as_ref() == crate::netzzugang::NETZZUGANG_MESSAGE_TYPE)
            .expect("NetzzugangAntrag outbox message enqueued");
        let antrag: NetzzugangAntrag =
            serde_json::from_value(msg.payload.clone()).expect("payload is a NetzzugangAntrag");
        assert_eq!(
            antrag.antrag_typ,
            NetzzugangAntragTyp::EnergySharingVereinbarung
        );
        assert_eq!(antrag.aktion, NetzzugangAktion::Registrierung);
        assert_eq!(antrag.status, NetzzugangStatus::Erfasst);
        assert_eq!(msg.recipient.as_ref(), "9900001000001");
    }

    /// The two Bestellung use cases (§20b Abs. 2 Nr. 1/2) require a valid
    /// `aktion` from the statutory triple.
    #[tokio::test]
    async fn dispatch_netzzugang_bestellung_validates_the_aktion() {
        let state = mabis_dispatch_state(&["MSB"]).await;
        let base = serde_json::json!({
            "netzanschluss_id": "NA-2",
            "nb_mp_id": "9900001000001",
            "antragsteller_ref": "kunde-7",
        });

        let mut bad = base.clone();
        bad["aktion"] = "stornierung".into();
        let err = dispatch_command(&state, "netzzugang.zaehlpunktanordnung.beauftragen", &bad)
            .await
            .expect_err("invalid aktion must be rejected");
        assert!(matches!(err, DispatchError::InvalidPayload(_)), "{err:?}");

        let mut ok = base;
        ok["aktion"] = "aenderung".into();
        let outcome = dispatch_command(&state, "netzzugang.verrechnungskonzept.beauftragen", &ok)
            .await
            .expect("aenderung must succeed");
        assert!(
            matches!(outcome, DispatchOutcome::Spawned { .. }),
            "{outcome:?}"
        );
    }

    /// `mabis.abrechnung.einleiten` with a missing required field must return
    /// `DispatchError::InvalidPayload`, not `NotImplemented`.
    #[tokio::test]
    async fn dispatch_mabis_einleiten_missing_field_returns_invalid_payload() {
        let state = mabis_dispatch_state(&["BKV"]).await;
        let payload = serde_json::json!({
            // "billing_period" intentionally omitted
            "bkv_id":  "4033872000022",
            "biko_id": "10YDE-VE-TRANSMIX",
            "version": "vorlaeufig",
        });
        let err = dispatch_command(&state, "mabis.abrechnung.einleiten", &payload)
            .await
            .expect_err("missing billing_period must return Err");
        assert!(
            matches!(err, DispatchError::InvalidPayload(_)),
            "must be InvalidPayload; got: {err:?}"
        );
    }
}
