use rust_decimal::Decimal;
use serde::{Deserialize, Serialize};
use time::{Date, OffsetDateTime};
use uuid::Uuid;

/// MSCONS PIDs that `edmd` consumes from `marktd` webhook fan-out.
///
/// Source: GPKE BK6-24-174 / WiM BK6-24-174; direction NB → LF.
pub const MSCONS_PIDS: &[u32] = &[
    13005, 13006, 13007, 13015, 13016, 13017, 13018, 13019, 13025, 13027,
];

/// MSCONS PIDs that carry Gas quality data (Brennwert + Zustandszahl).
///
/// PID 13007 = Gasbeschaffenheitsdaten (NB → LF): contains Abrechnungsbrennwert
/// (`QTY+Z08`, kWh/m³) and Zustandszahl (`QTY+Z10`, dimensionless).
///
/// Source: MSCONS AHB Gas 1.x; Allgemeine Festlegungen V6.1d §6.
pub const GAS_QUALITY_PIDS: &[u32] = &[13007];

/// Metering / balancing classification of a Marktlokation.
///
/// Determines the applicable Mindestvorlauffrist and billing-period aggregation
/// rules.
///
/// | Variant | Description | Vorlauffrist |
/// |---------|-------------|--------------|
/// | `Slp` | Standard load profile — synthetic, grid-area-based | Next Arbeitstag (15:00 cutoff) |
/// | `Rlm` | Registrierte Lastgangmessung — interval meter | 2 Werktage minimum |
/// | `Imsys` | Intelligentes Messsystem — smart meter | Treated as SLP for Vorlauffrist |
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum Messtyp {
    /// Standardlastprofil metering.
    Slp,
    /// Registrierende Lastgangmessung (interval metering, typically 15-min).
    Rlm,
    /// Intelligentes Messsystem (smart meter).
    Imsys,
}

impl std::fmt::Display for Messtyp {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::Slp => write!(f, "SLP"),
            Self::Rlm => write!(f, "RLM"),
            Self::Imsys => write!(f, "IMSYS"),
        }
    }
}

impl std::str::FromStr for Messtyp {
    type Err = String;
    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s.to_ascii_uppercase().as_str() {
            "SLP" => Ok(Self::Slp),
            "RLM" => Ok(Self::Rlm),
            "IMSYS" => Ok(Self::Imsys),
            other => Err(format!("unknown Messtyp: {other:?}")),
        }
    }
}

/// Quality flag for a meter reading (MSCONS DE7085 mapping).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum QualityFlag {
    /// Reading directly from meter (DE7085: 67 / Z83).
    Measured,
    /// Estimated value (DE7085: 79 / Z79).
    Estimated,
    /// Substitute value (Ersatzwert) generated by NB (DE7085: 63 / ZC2).
    Substituted,
    /// Calculated from SLP formula (DE7085: 220 / Z78).
    Calculated,
    /// Unknown / not mapped.
    Unknown,
}

impl Default for QualityFlag {
    fn default() -> Self {
        Self::Unknown
    }
}

/// Energy commodity (Sparte).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum Sparte {
    Strom,
    Gas,
}

/// A delivery receipt: confirms that MSCONS meter data was received for a MaLo.
///
/// Stored by `edmd` when a `de.mako.process.completed` event arrives for an
/// MSCONS PID. The actual kWh values are stored separately as [`MeterRead`]
/// records once the domain crates emit typed meter reads in the payload.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MeterDataReceipt {
    /// Process ID in `makod` (UUID v4).
    pub process_id: Uuid,
    /// MSCONS Prüfidentifikator.
    pub pid: u32,
    /// 11-digit MaLo-ID.
    pub malo_id: String,
    /// GLN of the sending NB/MSB.
    pub sender_mp_id: String,
    /// EDIFACT message reference.
    pub message_ref: Option<String>,
    /// UTC timestamp of the `de.mako.process.completed` event.
    pub received_at: OffsetDateTime,
    /// Tenant ID for multi-tenant deployments.
    pub tenant_id: Option<Uuid>,
}

/// A single metered interval read sourced from an MSCONS message.
///
/// Populated when domain crates emit typed read payloads in `ProcessCompleted`.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MeterRead {
    /// 11-digit Marktlokations-ID.
    pub malo_id: String,
    /// 33-character Messlokations-ID, if available.
    pub melo_id: Option<String>,
    /// Interval start (UTC).
    pub dtm_from: OffsetDateTime,
    /// Interval end (UTC).
    pub dtm_to: OffsetDateTime,
    /// Energy quantity in kWh.
    pub quantity_kwh: Decimal,
    /// Quality of the reading.
    pub quality: QualityFlag,
    /// Source PID (e.g. 13005).
    pub pid: u32,
    /// Energy commodity.
    pub sparte: Sparte,
    /// OBIS-Kennzahl (e.g. `"1-1:1.29.0"` for active energy, `"7-20:3.0.0"` for Gas volume).
    ///
    /// `None` when the MSCONS source did not include a PIA segment.
    pub obis_code: Option<String>,
    /// Tenant ID for multi-tenant deployments.
    pub tenant_id: Option<Uuid>,
}

/// Query parameters for time-series reads.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TimeSeriesQuery {
    pub malo_id: String,
    pub from: OffsetDateTime,
    pub to: OffsetDateTime,
    pub sparte: Option<Sparte>,
    pub tenant_id: Option<Uuid>,
}

/// Mehr-/Mindermengen imbalance report for one MaLo and one billing period.
///
/// Computed from [`MeterRead`] records by comparing LF-expected quantities
/// against NB-reported quantities.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ImbalanceReport {
    pub malo_id: String,
    /// Start of billing period (inclusive).
    pub period_from: Date,
    /// End of billing period (inclusive).
    pub period_to: Date,
    /// Total LF quantity (kWh) in period.
    pub lf_quantity_kwh: Decimal,
    /// Total NB reported quantity (kWh) in period.
    pub nb_quantity_kwh: Decimal,
    /// Delta = lf − nb.
    pub delta_kwh: Decimal,
    /// Delta as percentage of nb quantity. Zero when nb_quantity is zero.
    pub delta_pct: Decimal,
    /// Worst quality flag across all reads in the period.
    pub quality: QualityFlag,
}

/// Aggregated billing period summary for one MaLo.
///
/// Consumed by `invoicd` for INVOIC plausibility checks and by `netzbilanzd`
/// for NNE invoice generation.  Covers both SLP and RLM metering.
///
/// ## M15 requirement
///
/// This struct provides the inputs for all NNE billing positions:
/// - SLP: `arbeitsmenge_kwh` (total energy quantity)
/// - RLM Strom: `spitzenleistung_kw` (peak demand — Leistungspreisanteil = `Leistungspreis × spitzenleistung_kw`)
/// - Gas: `brennwert_kwh_per_m3` × `zustandszahl` → energy content from volume (m³ → kWh)
///
/// Lastgang (15-min intervals) is **NOT** inlined here — fetch separately via
/// `GET /api/v1/timeseries/{malo_id}` to avoid transferring 35 k rows per MaLo
/// in a billing-period summary response.
///
/// Source: GPKE BK6-22-024; GeLi Gas BK7-24-01-009; Allgemeine Festlegungen §6.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MeterBillingPeriod {
    /// 11-digit Marktlokations-ID.
    pub malo_id: String,
    /// Start of billing period (German local date, inclusive).
    pub period_from: Date,
    /// End of billing period (German local date, inclusive).
    pub period_to: Date,
    /// Metering classification: SLP / RLM / iMSys.
    pub messtyp: Messtyp,
    /// Energy commodity.
    pub sparte: Sparte,
    /// Total energy quantity in kWh (HT + NT combined for dual-tariff meters).
    pub arbeitsmenge_kwh: Decimal,
    /// High-tariff (Hochtarif, HT) quantity — `None` for single-tariff SLP.
    pub arbeitsmenge_ht_kwh: Option<Decimal>,
    /// Low-tariff (Niedertarif, NT) quantity — `None` for single-tariff SLP.
    pub arbeitsmenge_nt_kwh: Option<Decimal>,
    /// Peak demand in kW (Spitzenleistung).
    ///
    /// **RLM Strom only.** The 15-min interval with the highest average kW
    /// reading in the billing period.  Used to compute the Leistungspreisanteil:
    /// `Leistungspreis_EUR_per_kW × spitzenleistung_kw`.
    ///
    /// `None` for SLP, iMSys, and Gas MaLos.
    pub spitzenleistung_kw: Option<Decimal>,
    /// Abrechnungsbrennwert in kWh/m³ (Gas only).
    ///
    /// Supplied by the gas grid operator in PID 13007 or 17103.
    /// Used to convert volume (m³) to energy (kWh):
    /// `kWh = m³ × brennwert_kwh_per_m3 × zustandszahl`.
    ///
    /// `None` for Strom MaLos.
    pub brennwert_kwh_per_m3: Option<Decimal>,
    /// Zustandszahl (Gas only) — dimensionless compressibility factor.
    ///
    /// Accounts for temperature and pressure corrections.  **Not** a tariff
    /// zone — it is a physical gas Beschaffenheit factor.  Typically 0.95–1.05.
    ///
    /// `None` for Strom MaLos.
    pub zustandszahl: Option<Decimal>,
    /// Meter start reading (Zählerstand Anfang) — optional.
    pub zaehlerstand_anfang: Option<Decimal>,
    /// Meter end reading (Zählerstand Ende) — optional.
    pub zaehlerstand_ende: Option<Decimal>,
    /// Worst quality flag across all reads contributing to this summary.
    pub quality: QualityFlag,
    /// Tenant ID.
    pub tenant_id: Option<Uuid>,
}

/// Query parameters for a billing-period summary request.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BillingPeriodQuery {
    /// 11-digit Marktlokations-ID.
    pub malo_id: String,
    /// Start of requested billing period (inclusive).
    pub period_from: Date,
    /// End of requested billing period (inclusive).
    pub period_to: Date,
    /// Tenant scope.
    pub tenant_id: Option<Uuid>,
}
