-- ── netzbilanzd schema ────────────────────────────────────────────────────────
--
-- `invoice_drafts`: stores BO4E Rechnung drafts generated by `mako-netzbilanz`.
--
-- Lifecycle: draft → dispatched (via makod INVOIC command)
--            draft → rejected   (operator decision)
--
-- PIDs: 31001 (NNE Strom), 31002 (MMM Strom), 31005 (NNE Gas).
-- Source: GPKE BK6-22-024 §5; BDEW INVOIC AHB.

CREATE TABLE IF NOT EXISTS invoice_drafts (
    id               UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    malo_id          TEXT        NOT NULL,
    nb_mp_id         TEXT        NOT NULL,          -- invoice sender (NB/GNB)
    lf_mp_id         TEXT        NOT NULL,          -- invoice recipient (LF)
    pid              INTEGER     NOT NULL,           -- 31001 | 31002 | 31005
    period_from      DATE        NOT NULL,
    period_to        DATE        NOT NULL,
    rechnung         JSONB       NOT NULL DEFAULT '{}',  -- BO4E Rechnung payload
    gross_eur_units  BIGINT      NOT NULL DEFAULT 0,     -- total × 10⁻⁵ EUR
    check_outcome    TEXT,                           -- 'Ok' | 'Warn' | 'Dispute'
    status           TEXT        NOT NULL DEFAULT 'draft'  -- draft | dispatched | rejected
                     CHECK (status IN ('draft', 'dispatched', 'rejected')),
    dispatch_ref     TEXT,                           -- makod command UUID (if dispatched)
    reject_reason    TEXT,                           -- operator note (if rejected)
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at       TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS id_malo_period   ON invoice_drafts (malo_id, period_from, period_to);
CREATE INDEX IF NOT EXISTS id_nb_status     ON invoice_drafts (nb_mp_id, status);
CREATE INDEX IF NOT EXISTS id_status_pid    ON invoice_drafts (status, pid);
CREATE INDEX IF NOT EXISTS id_created       ON invoice_drafts (created_at DESC);
