-- ── netzbilanzd schema — NNE / MMM / MSB / AWH Billing Engine (NB role) ──────
--
-- `invoice_drafts`: BO4E Rechnung drafts generated by grid-billing.
--   Lifecycle: draft → dispatched → paid | rejected | Dispute.
--   Storno and Korrekturrechnung reference the original via original_draft_id.
--   Double-billing prevented by partial unique index (id_no_double_billing).
--
-- `kostenblatt_records`: Redispatch 2.0 Kostenblatt per BK6-20-061.
--   One record per activation event per TechnischeRessource.
--   Monthly submission to ÜNB due 15th of following month.
--
-- `fremdkosten_records`: typed BO4E Fremdkosten / FremdkostenBlock / FremdkostenPosition.
--   External cost pass-through (ÜNB balancing, third-party MSB) linked to draft.

-- ── Invoice drafts ────────────────────────────────────────────────────────────

CREATE TABLE invoice_drafts (
    id                  UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    malo_id             TEXT        NOT NULL,
    nb_mp_id            TEXT        NOT NULL,   -- invoice sender (NB/GNB)
    lf_mp_id            TEXT        NOT NULL,   -- invoice recipient (LF)
    tenant              TEXT        NOT NULL,
    pid                 INTEGER     NOT NULL,   -- 31001 | 31002 | 31005 | 31009 | 31011
    period_from         DATE        NOT NULL,
    period_to           DATE        NOT NULL,
    rechnung            JSONB       NOT NULL DEFAULT '{}',  -- rubo4e::current::Rechnung
    bo4e_version        TEXT        NOT NULL DEFAULT 'v202607.0.0',
    -- Total invoice amount × 10⁻⁵ EUR (for fast reporting without JSONB parse)
    gross_eur_units     BIGINT      NOT NULL DEFAULT 0,
    -- 'RECHNUNG' | 'STORNORECHNUNG' | 'KORREKTURRECHNUNG'
    rechnungsart        TEXT        NOT NULL DEFAULT 'RECHNUNG'
                        CHECK (rechnungsart IN ('RECHNUNG', 'STORNORECHNUNG', 'KORREKTURRECHNUNG')),
    -- FK to original draft for Storno/Korrektur audit chain
    original_draft_id   UUID        REFERENCES invoice_drafts(id) ON DELETE SET NULL,
    check_outcome       TEXT,       -- 'Ok' | 'Warn' | 'Dispute' (from invoic-checker)
    status              TEXT        NOT NULL DEFAULT 'draft'
                        CHECK (status IN ('draft', 'dispatched', 'rejected', 'paid')),
    dispatch_ref        TEXT,       -- makod command UUID (when dispatched)
    reject_reason       TEXT,       -- operator note (when rejected)
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT now()
);

COMMENT ON TABLE invoice_drafts IS
    'NNE/MMM/MSB/AWH billing drafts generated by grid-billing crate. '
    'Lifecycle: draft → dispatched → paid | rejected. '
    'Storno/Korrektur chains via original_draft_id.';

COMMENT ON COLUMN invoice_drafts.gross_eur_units IS
    'Total invoice amount × 10⁻⁵ EUR (stored as integer for exact arithmetic). '
    'Derived from GridSettlement.total_eur × 100000 in service layer.';

-- Tenant + MaLo billing history
CREATE INDEX id_tenant_malo    ON invoice_drafts (tenant, malo_id, created_at DESC);
-- Status workflow per NB
CREATE INDEX id_tenant_status  ON invoice_drafts (tenant, status, pid);
-- Storno/Korrektur lookup
CREATE INDEX id_original_draft ON invoice_drafts (original_draft_id)
    WHERE original_draft_id IS NOT NULL;
-- Storno filter for exception reports
CREATE INDEX id_rechnungsart   ON invoice_drafts (rechnungsart)
    WHERE rechnungsart IN ('STORNORECHNUNG', 'KORREKTURRECHNUNG');
-- Double-billing guard: one RECHNUNG per MaLo × period × PID × tenant
-- Storno/Korrektur and rejected drafts are explicitly excluded.
CREATE UNIQUE INDEX id_no_double_billing
    ON invoice_drafts (tenant, malo_id, period_from, period_to, pid)
    WHERE rechnungsart = 'RECHNUNG' AND status != 'rejected';

COMMENT ON INDEX id_no_double_billing IS
    'Prevents duplicate NNE/MMM billing for the same MaLo, period, and PID per tenant. '
    'Storno/Korrektur (rechnungsart != RECHNUNG) and rejected drafts are excluded.';

-- ── Redispatch 2.0 Kostenblatt ────────────────────────────────────────────────
-- BK6-20-061 §4.2: VNB submits monthly Kostenblatt to ÜNB by 15th of following month.
-- One record per activation event per TechnischeRessource.

CREATE TABLE kostenblatt_records (
    id                      UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant                  TEXT        NOT NULL,

    -- Redispatch activation reference (mako-engine process UUID)
    activation_id           TEXT        NOT NULL,
    -- TechnischeRessource-ID of the dispatched resource
    tr_id                   TEXT        NOT NULL,
    -- MaLo-ID of the connection point
    malo_id                 TEXT,

    -- Billing period (calendar month containing the activation)
    period_year             SMALLINT    NOT NULL,
    period_month            SMALLINT    NOT NULL CHECK (period_month BETWEEN 1 AND 12),

    uenb_mp_id              TEXT        NOT NULL,   -- ÜNB receiving the Kostenblatt
    vnb_mp_id               TEXT        NOT NULL,   -- VNB (our NB / sender)

    -- Einsatzkosten = dispatch_kwh × arbeitspreis_eur_per_kwh (STORED generated column)
    dispatch_kwh            NUMERIC(18, 3) NOT NULL DEFAULT 0,
    arbeitspreis_eur_per_kwh NUMERIC(12, 6) NOT NULL DEFAULT 0,
    einsatzkosten_eur       NUMERIC(16, 5)
        GENERATED ALWAYS AS (dispatch_kwh * arbeitspreis_eur_per_kwh) STORED,

    -- Activation window (UTC) — required for re-computation from edmd Lastgang
    activation_start_utc    TIMESTAMPTZ,
    activation_end_utc      TIMESTAMPTZ,

    -- Provenance of dispatch_kwh for §22 MessZV auditability:
    --   'lastgang_sum'    — summed from edmd 15-min intervals (most precise)
    --   'billing_period'  — fallback: edmd billing-period aggregate
    --   'manual_override' — supplied by operator
    dispatch_source         TEXT        CHECK (dispatch_source IN (
                                'lastgang_sum', 'billing_period', 'manual_override'
                            )),

    -- Full typed BO4E Fremdkosten JSONB (optional external cost breakdown)
    kosten_json             JSONB,

    status                  TEXT        NOT NULL DEFAULT 'pending'
                            CHECK (status IN (
                                'pending',      -- calculated, not yet submitted
                                'submitted',    -- sent to ÜNB via makod
                                'confirmed',    -- ÜNB acknowledged
                                'disputed',     -- ÜNB raised dispute
                                'paid'          -- ÜNB confirmed payment
                            )),
    submitted_at            TIMESTAMPTZ,
    dispatch_ref            TEXT,               -- makod command UUID

    created_at              TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at              TIMESTAMPTZ NOT NULL DEFAULT now(),

    UNIQUE (tenant, activation_id, tr_id)
);

COMMENT ON TABLE kostenblatt_records IS
    'Redispatch 2.0 Kostenblatt (BK6-20-061 §4.2). '
    'One row per activation event per TechnischeRessource. '
    'Monthly submission to ÜNB due 15th of following month.';

COMMENT ON COLUMN kostenblatt_records.einsatzkosten_eur IS
    'GENERATED: dispatch_kwh × arbeitspreis_eur_per_kwh. '
    'Always consistent — cannot be set directly.';

COMMENT ON COLUMN kostenblatt_records.dispatch_source IS
    '§22 MessZV provenance tracking: lastgang_sum (15-min edmd data) is most precise; '
    'billing_period is a fallback; manual_override requires operator justification.';

CREATE INDEX kb_period           ON kostenblatt_records (tenant, period_year, period_month, status);
CREATE INDEX kb_activation       ON kostenblatt_records (activation_id);
CREATE INDEX kb_activation_window ON kostenblatt_records (activation_start_utc, activation_end_utc)
    WHERE activation_start_utc IS NOT NULL;
-- Gap detection: records without energy data
CREATE INDEX kb_gaps             ON kostenblatt_records (tenant, period_year, period_month)
    WHERE dispatch_kwh = 0 AND dispatch_source IS NULL AND status = 'pending';
-- Due-date alert: pending Kostenblätter approaching the 15th-of-month deadline
CREATE INDEX kb_pending_15th     ON kostenblatt_records (period_year, period_month)
    WHERE status = 'pending';

-- ── Fremdkosten (external cost pass-through) ──────────────────────────────────
-- Typed BO4E Fremdkosten/FremdkostenBlock/FremdkostenPosition linked to an invoice draft.
-- External fees (ÜNB balancing charges, third-party MSB) passed through to LF in INVOIC.
-- Merged into Rechnung.zusatzAttribute on dispatch per §22 MessZV.

CREATE TABLE fremdkosten_records (
    id                  UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant              TEXT        NOT NULL,
    -- Invoice draft this Fremdkosten record augments
    draft_id            UUID        NOT NULL REFERENCES invoice_drafts(id) ON DELETE CASCADE,
    -- Full rubo4e::current::Fremdkosten JSONB (includes FremdkostenBlock list)
    fremdkosten_json    JSONB       NOT NULL,
    bezeichnung         TEXT,
    -- Pre-computed total (sum of all FremdkostenPosition.betrag.wert)
    total_eur           NUMERIC(16, 5) NOT NULL DEFAULT 0,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    -- One Fremdkosten record per draft per tenant
    UNIQUE (tenant, draft_id)
);

COMMENT ON TABLE fremdkosten_records IS
    '§22 MessZV typed external-cost pass-through. '
    'One record per invoice draft; multiple cost blocks embedded in fremdkosten_json. '
    'Merged into Rechnung.zusatzAttribute on dispatch.';

CREATE INDEX fk_draft_id ON fremdkosten_records (draft_id);
CREATE INDEX fk_tenant   ON fremdkosten_records (tenant, created_at DESC);
