//! ERP command ingestion API.
//!
//! ## Should we use BO4E?
//!
//! **Yes — but BO4E objects are master data, not process messages.**
//!
//! A BO4E `MARKTLOKATION` carries: `marktlokationsId`, `sparte`, `netzgebiet`,
//! `bilanzierungsgebiet`.  That is enough to *identify* a supply point.
//!
//! A UTILMD for Lieferbeginn additionally needs:
//! - **Lieferbeginn-Datum** — not in BO4E; ERP supplies it
//! - **Sender GLN** — always our operator GLN (`--tenant-id`); ERP never sends this
//! - **Receiver GLN (NB)** — resolved by the engine from the MaLo cache via `marktlokationsId`; ERP never sends this
//! - **PID** (55001 vs 55002 vs 55016) — implied by the command name; ERP never sends this
//! - **Message reference** — generated by the engine; ERP never sends this
//!
//! The conclusion: BO4E is the right integration standard (all major German energy
//! ERPs — SAP IS-U, Powercloud, Wilken, Schleupen — implement it), but each
//! command's payload is a **typed, command-specific envelope that embeds BO4E
//! objects alongside the process-specific fields** BO4E doesn't carry.
//!
//! ## Design
//!
//! The ERP names the exact MaKo command it wants to trigger.  The engine
//! resolves the Marktrolle and dispatches the command to the correct workflow,
//! generating EDIFACT.  BO4E objects are never used for routing.
//!
//! **Single-role commands** (e.g. `gpke.lieferbeginn.anmelden` → always `LF`)
//! do not require a `marktrolle` field — the engine infers it from the command
//! name.  **Multi-role commands** (e.g. `wim.geraetewechsel.beauftragen` →
//! `NB` or `MSB`) require `marktrolle` so the engine knows which EDIFACT
//! qualifier and workflow variant to use.
//!
//! The `--marktrollen` startup flag declares which roles this instance is
//! licensed for (e.g. `LF,LFG` for a dual-fuel supplier, `NB,MSB` for an
//! integrated Stadtwerke).  Commands for unlicensed roles are rejected with
//! `422 role_not_configured`.
//!
//! ## Endpoint
//!
//! ### `POST /api/v1/commands`
//!
//! **Request headers**
//!
//! | Header | Required | Notes |
//! |--------|----------|-------|
//! | `Content-Type` | Yes | Must be `application/json` |
//! | `Idempotency-Key` | Recommended | Stable UUID; prevents double-execution |
//!
//! **Request body** — an [`ErpCommand`] envelope with a command-specific payload:
//!
//! ```json
//! {
//!   "command": "gpke.lieferbeginn.anmelden",
//!   "payload": {
//!     "malo_id":            "10001234567",
//!     "lieferbeginn_datum": "2026-10-01"
//!   }
//! }
//! ```
//!
//! For multi-role commands, include `"marktrolle"` to disambiguate:
//!
//! ```json
//! {
//!   "command":    "wim.geraetewechsel.beauftragen",
//!   "marktrolle": "NB",
//!   "payload": { "melo_id": "DE00012345678", "wechseldatum": "2026-10-01" }
//! }
//! ```
//!
//! ### Why just `malo_id` and not a full BO4E `MARKTLOKATION` object?
//!
//! A UTILMD S2.x Lieferbeginn on the wire is a complex message: it references
//! the Marktlokation, all associated Messlokationen (MeLos), and the current
//! NB/MSB market-partner assignments valid at the supply-start date.
//!
//! All of that data is **already in the MaLo cache** — the ERP must seed it
//! first via `PUT /admin/malo/{malo_id}` using the NB's `MaloIdentResultPositive`
//! response from the API-Webdienste Strom endpoint.  That cached record carries:
//!
//! - `data_meter_locations` — the MeLo(s) (Messlokationen)
//! - `data_market_location_network_operators` — the NB GLN (receiver)
//! - `data_market_location_measuring_point_operators` — the MSB GLN
//!
//! The ERP therefore only needs to supply what the cache **cannot** know:
//! the **process trigger** (which MaLo) and the **process-specific date**.
//!
//! `VERTRAG` (Lieferantenvertrag) is an ERP-internal concept and does not
//! appear in the UTILMD wire format; the LF identity is the sender GLN.
//!
//! Fields the **engine owns — never supplied by the ERP**:
//! - `sender_party_id` — always our operator party ID (BDEW code / GLN / EIC) from `--tenant-id`; the ERP is talking
//!   to us, not the other way round
//! - `receiver_party_id` — resolved by the engine from the MaLo cache / partner
//!   registry using the `marktlokationsId`; the ERP need not know the NB's BDEW code
//! - `pruefidentifikator` — derived from `command` (e.g. `gpke.lieferbeginn.anmelden` → 55001)
//! - `message_ref` — derived by the EDIFACT renderer from the outbox entry's `causation_event_id` (UUID)
//! - `document_date` — set by the EDIFACT renderer to today at dispatch time
//!
//! **Response `202 Accepted`**
//!
//! ```json
//! {
//!   "idempotency_key": "01924f4e-3b4a-7e12-8c47-0022f4b2d3a1",
//!   "command":         "gpke.lieferbeginn.anmelden",
//!   "marktrolle":      "LF",
//!   "status":          "accepted"
//! }
//! ```
//!
//! ## Payload schemas per command
//!
//! Each command defines its own required payload fields.  The BO4E object is
//! always embedded under a named key (e.g. `malo`, `zaehler`, `vertrag`), not
//! at the top level, so additional process fields can sit alongside it cleanly.
//!
//! ## What the ERP must supply vs. what the engine derives
//!
//! | Source | Fields |
//! |--------|--------|
//! | **ERP supplies** | BO4E master data object, process dates, process-specific hints |
//! | **Engine derives** | sender GLN (tenant config), receiver GLN (MaLo cache / partner registry), PID (command name), message ref (generated) |
//!
//! The receiver GLN (NB, GNB, MSB) is looked up from the MaLo cache using the
//! `marktlokationsId`.  If the MaLo is not yet in the cache, the engine returns
//! `422 Unprocessable Entity` with `"error": "malo_not_found"` and the ERP must
//! first seed the MaLo via `PUT /admin/malo/{malo_id}`.
//!
//! ## Payload schemas per command
//!
//! Only fields the ERP genuinely owns are listed here.  GLNs resolved by the
//! engine (sender, receiver) are intentionally absent.
//!//! ### What the ERP sends vs. what the engine resolves from the MaLo cache
//!
//! | Resolved by engine (from MaLo cache) | Field |
//! |--------------------------------------|-------|
//! | `data_market_location_network_operators` | NB / GNB GLN (receiver) |
//! | `data_market_location_measuring_point_operators` | MSB GLN |
//! | `data_meter_locations` | MeLo IDs for UTILMD transactions |
//!
//! The MaLo cache is populated by the ERP via `PUT /admin/malo/{malo_id}` using
//! the NB's `MaloIdentResultPositive` response.  If the MaLo is not in the cache
//! yet, the engine returns `422 malo_not_found`.
//!//! | Command | ERP-supplied payload fields |
//! |---------|----------------------------|
//! | `gpke.lieferbeginn.anmelden` | `malo_id`, `lieferbeginn_datum` |
//! | `gpke.lieferende.anmelden` | `malo_id`, `lieferende_datum` |
//! | `gpke.kuendigung.anmelden` | `malo_id`, `kuendigung_datum`, `alter_lf_gln`¹ |
//! | `gpke.sperrung.bestaetigen` | `malo_id`, `ausfuehrungsdatum` |
//! | `gpke.abrechnung.annehmen` | `rechnung` (RECHNUNG BO4E) |
//! | `gpke.abrechnung.ablehnen` | `rechnung` (RECHNUNG BO4E), `ablehnungsgrund` |
//! | `geli.lieferbeginn.anmelden` | `malo_id` (Erdgas MaLo), `lieferbeginn_datum` |
//! | `geli.lieferende.anmelden` | `malo_id` (Erdgas MaLo), `lieferende_datum` |
//! | `wim.geraetewechsel.beauftragen` | `melo_id`, `wechseldatum`² |
//! | `mabis.abrechnung.einleiten` | `bilanzierungsgebiet`, `abrechnungszeitraum_von`, `abrechnungszeitraum_bis` |
//!
//! ¹ `alter_lf_gln` is required only when the old supplier is a different legal
//!   entity; derived from contract data in the ERP, not from the engine.
//!
//! ² For WiM Gerätewechsel the primary key is the `melo_id` (Messlokation),
//!   not the MaLo.  The MSB and NB GLNs are resolved from the MeLo cache entry.
//!
//! ### Invoicing commands (`gpke.abrechnung.*`)
//!
//! Billing commands use a BO4E `RECHNUNG` object because the invoice itself
//! is the master data — there is no separate cache to look up.  The ERP
//! supplies the full invoice payload.
//!
//! ## Marktrolle
//!
//! | Value | Bedeutung |
//! |-------|-----------|
//! | `NB` | Netzbetreiber (electricity DSO) |
//! | `GNB` | Gasnetzbetreiber (gas DSO) |
//! | `LF` | Lieferant (electricity supplier) |
//! | `LFG` | Lieferant Gas (gas supplier) |
//! | `MSB` | Messstellenbetreiber |
//! | `BKV` | Bilanzkreisverantwortlicher |
//! | `ÜNB` | Übertragungsnetzbetreiber |
//!
//! ## Command registry
//!
//! | Command | Marktrolle | Process | PIDs |
//! |---------|-----------|---------|------|
//! | `gpke.lieferbeginn.anmelden` | `LF` | GPKE Lieferbeginn Strom | 55001 |
//! | `gpke.lieferbeginn.bestaetigen` | `NB` | GPKE NB bestätigt Lieferbeginn | 55003/55004 |
//! | `gpke.lieferende.anmelden` | `LF` | GPKE Lieferende Strom | 55002 |
//! | `gpke.lieferende.bestaetigen` | `NB` | GPKE NB bestätigt Lieferende | 55005/55006 |
//! | `gpke.kuendigung.anmelden` | `LF` | GPKE Kündigung Lieferbeginn | 55016 |
//! | `gpke.sperrung.bestaetigen` | `LF` | GPKE Sperrung bestätigt (LFN → NB; ORDERS 17115/17117) | — |
//! | `gpke.abrechnung.annehmen` | `NB` | GPKE Netznutzungsabrechnung | 31001/31002 |
//! | `gpke.abrechnung.ablehnen` | `NB` | GPKE Abrechnungsstreit | 31001/31002 |
//! | `geli.lieferbeginn.anmelden` | `LFG` | GeLi Gas Lieferbeginn | 44001 |
//! | `geli.lieferbeginn.bestaetigen` | `GNB` | GeLi Gas NB bestätigt | 44003/44004 |
//! | `geli.lieferende.anmelden` | `LFG` | GeLi Gas Lieferende | 44002 |
//! | `geli.lieferende.bestaetigen` | `GNB` | GeLi Gas NB bestätigt | 44005/44006 |
//! | `wim.geraetewechsel.beauftragen` | `NB`/`MSB` | WiM Messstellenbetrieb | 55039, 55042, 55051, 55168 |
//! | `wim.geraetewechsel.bestaetigen` | `MSB` | WiM Messstellenbetrieb abgeschlossen | 55039, 55042, 55051, 55168 |
//! | `mabis.abrechnung.einleiten` | `BKV` | MABIS Bilanzkreisabrechnung Strom | 13003 |
//! | `mabis.abrechnung.daten-einreichen` | `BKV` | MABIS Messdaten liefern | 13003 |
//! | `mabis.abrechnung.begleichen` | `BKV`/`ÜNB` | MABIS Abrechnung begleichen | 13003 |

use std::sync::Arc;

use axum::{
    Router,
    extract::{DefaultBodyLimit, State},
    http::StatusCode,
    response::{IntoResponse, Json},
    routing::post,
};
use mako_engine::{
    deadline::{Deadline, DeadlineStore as _},
    ids::{ProcessId, TenantId},
    metrics::EngineMetrics,
    registry::ProcessRegistry as _,
    types::{MaLo, MarktpartnerCode, MessageRef, Pruefidentifikator},
    version::WorkflowId,
};
use mako_geli_gas::{GasSupplierChangeCommand, GeliGasSupplierChangeWorkflow};
use mako_gpke::{
    GpkeLfAnmeldungWorkflow, GpkeSupplierChangeWorkflow, LfAnmeldungCommand, SupplierChangeCommand,
};
use mako_mabis::{
    BillingCommand, DataStatus, IFTSTA_DATENSTATUS_PID, IFTSTA_PIDS as MABIS_IFTSTA_PIDS,
    MabisBillingWorkflow,
};
use mako_wim::steuerungsauftrag::{SteuerungsauftragCommand, WimSteuerungsauftragWorkflow};
use mako_wim::{DeviceChangeCommand, WimDeviceChangeWorkflow};
use secrecy::{ExposeSecret as _, SecretString};
use serde::{Deserialize, Serialize};
use subtle::ConstantTimeEq;
use tracing::info;

use crate::malo_cache::{MaloIdentResultCache, SlateDbMaloCache};

// ── Shared state ─────────────────────────────────────────────────────────────

/// Shared state for the ERP commands API.
#[derive(Clone)]
pub struct CommandsApiState {
    /// Operator tenant identifier (our GLN as a TenantId).
    pub tenant_id: TenantId,
    /// Our operator GLN as a string (from `--tenant-id`).
    pub sender_party_id: String,
    /// Maximum request body size in bytes.
    ///
    /// Applied via [`DefaultBodyLimit`] to prevent unbounded heap allocation
    /// on malicious or oversized ERP payloads.
    pub max_body_bytes: usize,
    /// Marktrollen this instance is licensed and configured for (upper-case).
    ///
    /// When non-empty, only commands whose effective Marktrolle appears in this
    /// list are accepted.  Commands for unconfigured roles are rejected with
    /// `422 role_not_configured`.  Set via `--marktrollen` at startup.
    ///
    /// When empty, role configuration checking is skipped (permissive /
    /// backward-compatible mode).
    pub configured_marktrollen: Vec<String>,
    /// When `Some`, every request must supply `Authorization: Bearer <token>`.
    pub optional_token: Option<SecretString>,
    /// Shared SlateDB store — used for process dispatch and deadline registration.
    pub store: Arc<mako_engine::store_slatedb::SlateDbStore>,
    /// Snapshot store — shares the same underlying DB as `store`.
    ///
    /// Passed to `execute_and_enqueue_with_snapshot_and_retry` so replay cost
    /// for long-lived processes is bounded to at most 100 tail events instead
    /// of a full O(n) event scan on every command dispatch.
    pub snapshot_store: mako_engine::store_slatedb::SlateDbSnapshotStore,
    /// MaLo master-data cache — used to resolve NB/MSB GLNs from MaLo IDs.
    pub malo_cache: Arc<SlateDbMaloCache>,
    /// MaLo-ID result cache — maps `tx_id → (malo_id, nb_gln)` for the
    /// `maloid.lieferbeginn.fortsetzen` continuation command.
    ///
    /// Written by `MaloIdentSender` after a positive callback is delivered.
    /// The ERP receives `MaloIdentified` via the ERP webhook and then calls
    /// `maloid.lieferbeginn.fortsetzen` with only the `tx_id` and
    /// `lieferbeginn_datum` — `makod` resolves the `malo_id` and `nb_gln`
    /// from this cache.
    pub maloid_result_cache: MaloIdentResultCache,
    /// Number of events between automatic process snapshots.
    ///
    /// Defaults to 100. Configurable via `--snapshot-interval` at startup
    /// so operators can tune replay latency vs. write amplification without
    /// recompiling.
    pub snapshot_interval: u64,
}

// ── Command envelope ──────────────────────────────────────────────────────────

/// Inbound ERP command envelope.
///
/// The ERP explicitly names the MaKo process command it wants to trigger and
/// its own Marktrolle.  The BO4E object(s) carrying domain data are placed in
/// `payload` — they are never used for routing.
#[derive(Debug, Deserialize)]
pub struct ErpCommand {
    /// Dotted command name: `<domain>.<prozess>.<aktion>`.
    ///
    /// Examples: `gpke.lieferbeginn.anmelden`, `wim.geraetewechsel.beauftragen`
    pub command: String,

    /// Marktrolle of the ERP system issuing this command.
    ///
    /// **Required only for multi-role commands** such as
    /// `wim.geraetewechsel.beauftragen` (permitted for both `NB` and `MSB`).
    /// For single-role commands (e.g. `gpke.lieferbeginn.anmelden` → always `LF`)
    /// this field is optional — the role is inferred from the command name.
    ///
    /// Examples: `"NB"`, `"LF"`, `"LFG"`, `"GNB"`, `"MSB"`, `"BKV"`, `"ÜNB"`
    pub marktrolle: Option<String>,

    /// Command-specific payload.
    ///
    /// Each command defines its own required fields.  For most GPKE/GeLi
    /// commands the minimal payload is a `malo_id` string (the 11-digit
    /// Marktlokations-ID) plus the process-specific date.  The engine
    /// resolves all partner GLNs (NB, MSB) and MeLo data from the MaLo cache.
    ///
    /// Example for `gpke.lieferbeginn.anmelden`:
    /// ```json
    /// {
    ///   "malo_id":            "10001234567",
    ///   "lieferbeginn_datum": "2026-10-01"
    /// }
    /// ```
    ///
    /// Billing commands embed a BO4E `RECHNUNG` object because the invoice is
    /// the master data itself (no separate cache lookup needed).
    ///
    /// **Never include** `sender_party_id`, `receiver_party_id`, `pruefidentifikator`, or
    /// `message_ref` — these are engine-owned and will be ignored or rejected.
    pub payload: serde_json::Value,
}

/// Successful command acceptance response.
#[derive(Serialize)]
pub struct CommandAccepted {
    /// Idempotency key echoed back to the caller.
    pub idempotency_key: String,
    /// The command name as received.
    pub command: String,
    /// The Marktrolle as received.
    pub marktrolle: String,
    /// Always `"accepted"` for HTTP 202.
    pub status: &'static str,
}

// ── Router ────────────────────────────────────────────────────────────────────

/// Build the ERP commands router.
pub fn router(state: Arc<CommandsApiState>) -> Router {
    let max_body = state.max_body_bytes;
    Router::new()
        .route("/api/v1/commands", post(handle_command))
        .layer(DefaultBodyLimit::max(max_body))
        .with_state(state)
}

// ── Handler ───────────────────────────────────────────────────────────────────

async fn handle_command(
    State(state): State<Arc<CommandsApiState>>,
    headers: axum::http::HeaderMap,
    Json(envelope): Json<ErpCommand>,
) -> impl IntoResponse {
    // ── Bearer token authentication ───────────────────────────────────────────
    if let Some(expected_token) = &state.optional_token {
        match extract_bearer(&headers) {
            None => {
                return (
                    StatusCode::UNAUTHORIZED,
                    Json(serde_json::json!({
                        "error": "Unauthorized",
                        "detail": "Authorization: Bearer <token> header required"
                    })),
                )
                    .into_response();
            }
            Some(provided) => {
                let ok: bool = provided
                    .as_bytes()
                    .ct_eq(expected_token.expose_secret().as_bytes())
                    .into();
                if !ok {
                    return (
                        StatusCode::UNAUTHORIZED,
                        Json(serde_json::json!({
                            "error": "Unauthorized",
                            "detail": "invalid token"
                        })),
                    )
                        .into_response();
                }
            }
        }
    }

    // ── Resolve and validate Marktrolle ────────────────────────────────────────
    //
    // Single-role commands (e.g. `gpke.lieferbeginn.anmelden` → always `LF`):
    // the role is inferred; any asserted `marktrolle` in the request is ignored.
    //
    // Multi-role commands (e.g. `wim.geraetewechsel.beauftragen` → `NB` or `MSB`):
    // the ERP must supply `marktrolle` so the engine knows which EDIFACT
    // qualifier and workflow variant to use.
    let cmd_lower = envelope.command.to_lowercase();
    let asserted = envelope.marktrolle.as_deref().map(str::to_uppercase);

    let effective_marktrolle = match validate_command(
        &cmd_lower,
        asserted.as_deref(),
        &state.configured_marktrollen,
    ) {
        Ok(role) => role,
        Err(e) => {
            let (code, detail) = match e {
                CommandError::UnknownCommand => (
                    StatusCode::UNPROCESSABLE_ENTITY,
                    format!(
                        "Unknown command {:?}. See module documentation for the command registry.",
                        envelope.command
                    ),
                ),
                CommandError::MarktrolleRequired => (
                    StatusCode::UNPROCESSABLE_ENTITY,
                    format!(
                        "Command {:?} is permitted for multiple Marktrollen — \
                         supply \"marktrolle\" in the request body to disambiguate.",
                        envelope.command
                    ),
                ),
                CommandError::RoleNotPermitted => (
                    StatusCode::UNPROCESSABLE_ENTITY,
                    format!(
                        "Marktrolle {:?} is not permitted to issue command {:?}.",
                        envelope.marktrolle, envelope.command
                    ),
                ),
                CommandError::RoleNotConfigured => (
                    StatusCode::UNPROCESSABLE_ENTITY,
                    format!(
                        "This makod instance is not configured for the Marktrolle \
                         required by command {:?}. Set --marktrollen at startup.",
                        envelope.command
                    ),
                ),
            };
            return (
                code,
                Json(serde_json::json!({ "error": "command_rejected", "detail": detail })),
            )
                .into_response();
        }
    };

    // ── Idempotency key ───────────────────────────────────────────────────────
    let idempotency_key = headers
        .get("idempotency-key")
        .or_else(|| headers.get("Idempotency-Key"))
        .and_then(|v| v.to_str().ok())
        .map(str::to_owned)
        .unwrap_or_else(|| uuid::Uuid::new_v4().to_string());

    info!(
        idempotency_key = %idempotency_key,
        command         = %cmd_lower,
        marktrolle      = %effective_marktrolle,
        tenant_id       = %state.tenant_id,
        "ERP command accepted",
    );

    // ── Dispatch to workflow ──────────────────────────────────────────────────
    match dispatch_command(&state, &cmd_lower, &envelope.payload).await {
        Ok(DispatchOutcome::Spawned { process_id }) => {
            info!(
                idempotency_key = %idempotency_key,
                command         = %cmd_lower,
                process_id      = %process_id,
                "ERP command dispatched — process spawned",
            );
            // Track per-family process initiation for the Prometheus metrics endpoint.
            EngineMetrics::global().process_initiated("gpke");
        }
        Ok(DispatchOutcome::Dispatched { process_id }) => {
            info!(
                idempotency_key = %idempotency_key,
                command         = %cmd_lower,
                process_id      = %process_id,
                "ERP command dispatched — existing process updated",
            );
        }
        Err(DispatchError::MaloNotFound(malo_id)) => {
            return (
                StatusCode::UNPROCESSABLE_ENTITY,
                Json(serde_json::json!({
                    "error":  "malo_not_found",
                    "detail": format!(
                        "MaLo {malo_id:?} is not in the cache. \
                         Seed it first via PUT /admin/malo/{malo_id}."
                    ),
                    "malo_id": malo_id,
                })),
            )
                .into_response();
        }
        Err(DispatchError::InvalidPayload(msg)) => {
            return (
                StatusCode::UNPROCESSABLE_ENTITY,
                Json(serde_json::json!({
                    "error":  "invalid_payload",
                    "detail": msg,
                })),
            )
                .into_response();
        }
        Err(DispatchError::ProcessNotFound {
            business_key,
            workflow_name,
        }) => {
            return (
                StatusCode::NOT_FOUND,
                Json(serde_json::json!({
                    "error":        "process_not_found",
                    "detail":       format!(
                        "No active {workflow_name} process found for business key {business_key:?}. \
                         Initiate the Anmeldung first via the corresponding anmelden command."
                    ),
                    "business_key":  business_key,
                    "workflow_name": workflow_name,
                })),
            )
                .into_response();
        }
        Err(DispatchError::AmbiguousProcess {
            business_key,
            count,
        }) => {
            tracing::error!(
                business_key = %business_key,
                count        = count,
                "ERP dispatch: multiple active processes for business key — data integrity issue",
            );
            return (
                StatusCode::CONFLICT,
                Json(serde_json::json!({
                    "error":        "ambiguous_process",
                    "detail":       format!(
                        "{count} active processes found for business key {business_key:?}; \
                         expected exactly one. This indicates a data integrity issue."
                    ),
                    "business_key": business_key,
                    "count":        count,
                })),
            )
                .into_response();
        }
        Err(DispatchError::DuplicateProcess {
            process_id,
            malo_id,
        }) => {
            tracing::warn!(
                malo_id    = %malo_id,
                process_id = %process_id,
                "ERP dispatch: duplicate anmelden rejected — active process exists",
            );
            return (
                StatusCode::CONFLICT,
                Json(serde_json::json!({
                    "error":      "duplicate_process",
                    "detail":     format!(
                        "An active process for MaLo {malo_id:?} already exists. \
                         Route follow-up commands (bestaetigen/ablehnen/aktivieren) \
                         to the existing process, or wait until it reaches a terminal \
                         state before re-initiating."
                    ),
                    "malo_id":    malo_id,
                    "process_id": process_id.to_string(),
                })),
            )
                .into_response();
        }
        Err(DispatchError::Engine(e)) => {
            tracing::error!(
                idempotency_key = %idempotency_key,
                command         = %cmd_lower,
                error           = %e,
                "ERP dispatch: engine error",
            );
            return (
                StatusCode::INTERNAL_SERVER_ERROR,
                Json(serde_json::json!({
                    "error":  "engine_error",
                    "detail": e.to_string(),
                })),
            )
                .into_response();
        }
        Err(DispatchError::NotImplemented(cmd)) => {
            tracing::warn!(
                command = %cmd,
                "ERP dispatch: command not yet implemented — returning 501",
            );
            return (
                StatusCode::NOT_IMPLEMENTED,
                Json(serde_json::json!({
                    "error":  "not_implemented",
                    "detail": format!("command '{cmd}' is not yet dispatchable — do not retry automatically"),
                })),
            )
                .into_response();
        }
    }

    (
        StatusCode::ACCEPTED,
        Json(CommandAccepted {
            idempotency_key,
            command: envelope.command,
            marktrolle: effective_marktrolle,
            status: "accepted",
        }),
    )
        .into_response()
}

// ── Dispatch ──────────────────────────────────────────────────────────────────

enum DispatchOutcome {
    Spawned {
        process_id: ProcessId,
    },
    /// Command routed to an existing process (response / confirmation).
    Dispatched {
        process_id: ProcessId,
    },
}

enum DispatchError {
    /// Required `malo_id` not in the cache — ERP must seed it first.
    MaloNotFound(String),
    /// Payload is missing a required field or carries a malformed value.
    InvalidPayload(String),
    /// Engine error (version conflict, storage failure, …).
    Engine(mako_engine::error::EngineError),
    /// No active process found for the given business key.
    ///
    /// For LF-side commands this means the Anmeldung has not been initiated
    /// yet, or the process has already reached a terminal state.
    ProcessNotFound {
        business_key: String,
        workflow_name: &'static str,
    },
    /// More than one active process exists for the given business key.
    ///
    /// This should not occur under normal operation — it indicates a bug in
    /// the process-initiation path that registered the same MaLo twice.
    AmbiguousProcess { business_key: String, count: usize },
    /// An active process for the given MaLo already exists.
    ///
    /// ERP must not re-initiate a process that is still in progress. Use
    /// the existing `process_id` to route follow-up commands (bestaetigen,
    /// ablehnen, aktivieren). Retry the `anmelden` command only after the
    /// existing process has reached a terminal state.
    ///
    /// Note: a narrow TOCTOU window exists if two concurrent calls arrive
    /// simultaneously. The check-then-spawn sequence is not atomic. In practice
    /// ERP serialises requests per MaLo so the window is negligible.
    DuplicateProcess {
        process_id: ProcessId,
        malo_id: String,
    },
    /// Command is known but the full workflow routing is not yet implemented.
    NotImplemented(String),
}

impl From<mako_engine::error::EngineError> for DispatchError {
    fn from(e: mako_engine::error::EngineError) -> Self {
        Self::Engine(e)
    }
}

/// Map an ERP command to a workflow command and dispatch it.
async fn dispatch_command(
    state: &CommandsApiState,
    command: &str,
    payload: &serde_json::Value,
) -> Result<DispatchOutcome, DispatchError> {
    match command {
        // ── GPKE LF-side Anmeldung (new process, outbound UTILMD) ────────────
        "gpke.lieferbeginn.anmelden" => {
            dispatch_lf_anmeldung(state, payload, 55001, "lieferbeginn_datum").await
        }
        "gpke.lieferende.anmelden" => {
            dispatch_lf_anmeldung(state, payload, 55002, "lieferende_datum").await
        }
        "gpke.kuendigung.anmelden" => {
            dispatch_lf_anmeldung(state, payload, 55016, "kuendigung_datum").await
        }

        // ── GPKE MaLo-ID continuation ────────────────────────────────
        //
        // ERP receives `MaloIdentified` ERP event with a `tx_id`, then calls
        // this command to auto-dispatch PID 55001 Lieferbeginn without having
        // to know the malo_id in advance.  makod resolves malo_id + nb_gln
        // from the `mc_txres/` cache written by MaloIdentSender.
        "maloid.lieferbeginn.fortsetzen" => {
            dispatch_maloid_lieferbeginn_fortsetzen(state, payload).await
        }

        // ── GPKE LF-side responses (routes to existing gpke-lf-anmeldung) ────
        "gpke.lieferbeginn.bestaetigen" | "gpke.lieferende.bestaetigen" => {
            let (response_pid_code, payload_pid_key) = if command == "gpke.lieferbeginn.bestaetigen"
            {
                (55003u32, "response_pid")
            } else {
                (55005u32, "response_pid")
            };
            let response_pid_code = payload
                .get(payload_pid_key)
                .and_then(|v| v.as_u64())
                .map(|n| n as u32)
                .unwrap_or(response_pid_code);
            dispatch_lf_antwort(state, payload, true, response_pid_code).await
        }
        "gpke.lieferbeginn.ablehnen" | "gpke.lieferende.ablehnen" => {
            let response_pid_code = if command == "gpke.lieferbeginn.ablehnen" {
                55004u32
            } else {
                55006u32
            };
            let response_pid_code = payload
                .get("response_pid")
                .and_then(|v| v.as_u64())
                .map(|n| n as u32)
                .unwrap_or(response_pid_code);
            dispatch_lf_antwort(state, payload, false, response_pid_code).await
        }
        "gpke.lieferbeginn.aktivieren" => dispatch_lf_activate(state, payload).await,

        // ── GeLi Gas LFG-side responses (routes to geli-gas-lf-anmeldung) ────
        "geli.lieferbeginn.bestaetigen" | "geli.lieferende.bestaetigen" => {
            let response_pid_code = if command == "geli.lieferbeginn.bestaetigen" {
                44003u32
            } else {
                44005u32
            };
            let response_pid_code = payload
                .get("response_pid")
                .and_then(|v| v.as_u64())
                .map(|n| n as u32)
                .unwrap_or(response_pid_code);
            dispatch_geli_gas_antwort(state, payload, true, response_pid_code).await
        }
        "geli.lieferbeginn.ablehnen" | "geli.lieferende.ablehnen" => {
            let response_pid_code = if command == "geli.lieferbeginn.ablehnen" {
                44004u32
            } else {
                44006u32
            };
            let response_pid_code = payload
                .get("response_pid")
                .and_then(|v| v.as_u64())
                .map(|n| n as u32)
                .unwrap_or(response_pid_code);
            dispatch_geli_gas_antwort(state, payload, false, response_pid_code).await
        }

        // ── WiM NB-side APERAK (routes to existing wim-device-change) ────────
        "wim.geraetewechsel.bestaetigen" => dispatch_wim_aperak(state, payload, true).await,
        "wim.geraetewechsel.ablehnen" => dispatch_wim_aperak(state, payload, false).await,

        // ── WiM Steuerungsauftrag (MSB role — REST Control Measures ──
        //
        // After `makod` receives a `konfiguration` or `initialZustand` via the
        // API-Webdienste Strom Control Measures endpoint, the ERP sends one of
        // these commands to confirm or reject the execution.
        //
        // The `wim.steuerungsauftrag.bestaetigen` command is identified by the
        // `tx_id` from the original REST request (the same tx_id the NB/LF sent).
        "wim.steuerungsauftrag.bestaetigen" => {
            dispatch_steuerungsauftrag_endantwort(state, payload, true).await
        }
        "wim.steuerungsauftrag.ablehnen" => {
            dispatch_steuerungsauftrag_endantwort(state, payload, false).await
        }

        // ── Commands that are registered but not yet dispatched ───────────────
        // IFTSTA status commands — route inbound Vollzugsmeldungen and
        // status messages received via the REST channel (e.g. ERP replay,
        // manual override) to the correct workflow instance.
        "gpke.vollzugsmeldung.empfangen" => dispatch_gpke_iftsta(state, payload).await,
        "wim.iftsta.empfangen" => dispatch_wim_iftsta(state, payload).await,
        "mabis.iftsta.empfangen" => dispatch_mabis_iftsta(state, payload, false).await,
        "mabis.datenstatus.empfangen" => dispatch_mabis_iftsta(state, payload, true).await,

        cmd => Err(DispatchError::NotImplemented(cmd.to_owned())),
    }
}

/// Dispatch a GPKE LF-side Anmeldung (Lieferbeginn / Lieferende / Kündigung).
///
/// 1. Extract `malo_id` and `process_date_field` from the ERP payload.
/// 2. Resolve the NB GLN from the MaLo cache.
/// 3. Spawn a new `GpkeLfAnmeldungWorkflow` process.
/// 4. Execute `InitiateAnmeldung` — writes the `Initiated` event and enqueues
///    the outbound UTILMD outbox entry atomically.
/// 5. Register a 24h NB-response deadline (GPKE BK6-22-024).
async fn dispatch_lf_anmeldung(
    state: &CommandsApiState,
    payload: &serde_json::Value,
    pid_code: u32,
    process_date_key: &str,
) -> Result<DispatchOutcome, DispatchError> {
    // ── Extract ERP-supplied fields ───────────────────────────────────────────
    let malo_id = payload
        .get("malo_id")
        .and_then(|v| v.as_str())
        .ok_or_else(|| {
            DispatchError::InvalidPayload(
                "payload must contain \"malo_id\" (11-digit Marktlokations-ID string)".into(),
            )
        })?
        .to_owned();

    let process_date = payload
        .get(process_date_key)
        .and_then(|v| v.as_str())
        .ok_or_else(|| {
            DispatchError::InvalidPayload(format!(
                "payload must contain \"{process_date_key}\" (ISO-8601 date string)",
            ))
        })?
        .to_owned();

    // Optional: ERP may supply `alter_lf_gln` for Kündigung (PID 55016) when
    // the old supplier is a different legal entity.  Not yet used in the domain
    // command but extracted here for future use.
    let _alter_lf_gln = payload
        .get("alter_lf_gln")
        .and_then(|v| v.as_str())
        .map(str::to_owned);

    // ── Resolve NB GLN from MaLo cache ───────────────────────────────────────
    //
    // `data_market_location_network_operators` is a time-sliced list of NBs.
    // We take the entry with the latest `execution_time_from` that has no
    // `execution_time_until` (i.e. the currently active NB).
    let malo_record = state
        .malo_cache
        .get(&state.tenant_id.to_string(), &malo_id)
        .await
        .map_err(|e| DispatchError::Engine(mako_engine::error::EngineError::store(e.to_string())))?
        .ok_or_else(|| DispatchError::MaloNotFound(malo_id.clone()))?;

    let nb_gln = malo_record
        .data_market_location
        .data_market_location_network_operators
        .iter()
        // Prefer currently open time slice (no execution_time_until) or latest.
        .max_by_key(|p| (p.execution_time_until.is_none(), &p.execution_time_from))
        .map(|p| MarktpartnerCode::new(format!("{:013}", p.market_partner_id)))
        .ok_or_else(|| {
            DispatchError::InvalidPayload(format!(
                "MaLo {malo_id} in cache has no network_operator entry — \
             the NB GLN cannot be resolved",
            ))
        })?;

    // ── Build typed domain command ────────────────────────────────────────────
    let pid = Pruefidentifikator::new(pid_code).map_err(DispatchError::InvalidPayload)?;

    let domain_cmd = LfAnmeldungCommand::InitiateAnmeldung {
        pid,
        sender: MarktpartnerCode::new(state.sender_party_id.clone()),
        receiver: nb_gln,
        location_id: MaLo::new(malo_id.clone()),
        process_date,
    };

    // ── Idempotency guard ─────────────────────────────────────────────────────
    //
    // Reject duplicate Anmeldung for the same MaLo. ERP retries should re-send
    // after the existing process reaches a terminal state.
    let existing = state
        .store
        .as_process_registry()
        .lookup_correlated(state.tenant_id, &malo_id)
        .await
        .map_err(DispatchError::Engine)?;
    if let Some(first) = existing.into_iter().next() {
        let dup_id = first.process_id;
        tracing::warn!(
            malo_id    = %malo_id,
            process_id = %dup_id,
            "anmelden refused: active process already registered for this MaLo",
        );
        return Err(DispatchError::DuplicateProcess {
            process_id: dup_id,
            malo_id,
        });
    }

    // ── Spawn process and execute command ─────────────────────────────────────
    //
    // `Process::new` generates a fresh ProcessId + StreamId.
    // `execute_and_enqueue_with_snapshot_and_retry` atomically appends the
    // `Initiated` event AND enqueues the outbound UTILMD outbox entry in a
    // single SlateDB WriteBatch (dual-write atomicity — no lost APERAKs on
    // crash).  Retries up to 3 times on VersionConflict and takes a snapshot
    // every 100 events so future replay is bounded to at most 100 tail events.
    let workflow_id = current_workflow_id();
    let process = mako_engine::process::Process::<
        GpkeLfAnmeldungWorkflow,
        Arc<mako_engine::store_slatedb::SlateDbStore>,
    >::new(
        Arc::clone(&state.store),
        state.tenant_id,
        workflow_id.clone(),
    );

    let process_id = process.process_id();
    process
        .execute_and_enqueue_with_snapshot_and_retry(
            domain_cmd,
            /* max_attempts      */ 3,
            &state.snapshot_store,
            state.snapshot_interval,
        )
        .await?;

    // ── Register 24h NB-response deadline (GPKE BK6-22-024) ──────────────────
    //
    // If the NB does not respond within 24 wall-clock hours the deadline
    // scheduler fires `LfAnmeldungCommand::TimeoutExpired`, which transitions
    // the process to `Rejected` and the ERP webhook receives an `AperakTimeout`.
    let due_at = mako_engine::fristen::add_hours(time::OffsetDateTime::now_utc(), 24);
    let deadline = Deadline::new(
        process.stream_id().clone(),
        process_id,
        state.tenant_id,
        workflow_id,
        "nb-response-window-24h",
        due_at,
    );
    if let Err(e) = state.store.as_deadline_store().register(&deadline).await {
        tracing::warn!(
            process_id = %process_id,
            error      = %e,
            "ERP dispatch: deadline registration failed (non-fatal — process was spawned)",
        );
    }

    // ── Register process under MaLo business key ──────────────────────────────
    //
    // This enables Phase 3 response commands (`gpke.lieferbeginn.bestaetigen`,
    // `gpke.lieferbeginn.aktivieren`, etc.) to look up the active process by
    // `malo_id` without an exhaustive scan of all process streams.
    //
    // Registration is non-fatal: if it fails (e.g. transient storage error)
    // the process has already been spawned and the Anmeldung is underway.
    // The ERP must re-issue the command to trigger retry — the 202 is not sent
    // here so the ERP is not misled, but we log prominently for ops.
    let identity = process.identity();
    if let Err(e) = state
        .store
        .as_process_registry()
        .register_correlated(state.tenant_id, &malo_id, process_id, identity)
        .await
    {
        tracing::warn!(
            process_id = %process_id,
            malo_id    = %malo_id,
            error      = %e,
            "ERP dispatch: business-key registration failed (non-fatal — Anmeldung was spawned); \
             response commands (bestaetigen/ablehnen/aktivieren) will return process_not_found \
             until the next successful anmelden call re-registers the process",
        );
    }

    Ok(DispatchOutcome::Spawned { process_id })
}

/// Dispatch `maloid.lieferbeginn.fortsetzen` — auto-continue to GPKE PID 55001
/// after a MaLo-ID identification has completed.
///
/// ## Flow
///
/// 1. ERP receives `MaloIdentified` ERP event with `tx_id`.
/// 2. ERP calls `POST /api/v1/commands`:
///    ```json
///    {
///      "command": "maloid.lieferbeginn.fortsetzen",
///      "marktrolle": "LF",
///      "payload": {
///        "tx_id":              "<tx_id from the maloId request>",
///        "lieferbeginn_datum": "2026-10-01"
///      }
///    }
///    ```
/// 3. `makod` looks up `(malo_id, nb_gln)` from the `mc_txres/` cache using
///    the `tx_id` — no need for the ERP to track the MaLo-ID.
/// 4. Dispatches `LfAnmeldungCommand::InitiateAnmeldung` (PID 55001) with the
///    resolved data, exactly like `gpke.lieferbeginn.anmelden`.
///
/// ## Error cases
///
/// - `tx_id` unknown or result not yet cached → `422 tx_id_not_resolved`.
/// - `tx_id` resolved but `nb_gln` is empty → falls back to MaLo cache lookup.
async fn dispatch_maloid_lieferbeginn_fortsetzen(
    state: &CommandsApiState,
    payload: &serde_json::Value,
) -> Result<DispatchOutcome, DispatchError> {
    // ── Extract tx_id and lieferbeginn_datum ──────────────────────────────────
    let tx_id = payload
        .get("tx_id")
        .and_then(|v| v.as_str())
        .ok_or_else(|| {
            DispatchError::InvalidPayload(
                "payload must contain \"tx_id\" (the MaLo-ID request transaction ID)".into(),
            )
        })?
        .to_owned();

    let lieferbeginn_datum = payload
        .get("lieferbeginn_datum")
        .and_then(|v| v.as_str())
        .ok_or_else(|| {
            DispatchError::InvalidPayload(
                "payload must contain \"lieferbeginn_datum\" (ISO-8601 date, e.g. \"2026-10-01\")"
                    .into(),
            )
        })?
        .to_owned();

    // ── Look up resolved result from tx_id cache ──────────────────────────────
    let resolved = state
        .maloid_result_cache
        .get_result(&state.tenant_id.to_string(), &tx_id)
        .await
        .map_err(|e| DispatchError::Engine(
            mako_engine::error::EngineError::store(e.to_string()),
        ))?
        .ok_or_else(|| DispatchError::InvalidPayload(format!(
            "tx_id {tx_id:?} not found in result cache — \
             the MaLo-ID identification may not yet have completed (positive callback not yet delivered). \
             Retry after receiving the MaloIdentified ERP event, or use \
             gpke.lieferbeginn.anmelden with an explicit malo_id.",
        )))?;

    // ── Build the synthetic ERP payload for dispatch_lf_anmeldung ────────────
    let synthetic_payload = serde_json::json!({
        "malo_id":           resolved.malo_id,
        "lieferbeginn_datum": lieferbeginn_datum,
    });

    tracing::info!(
        tx_id            = %tx_id,
        malo_id          = %resolved.malo_id,
        nb_gln           = %resolved.nb_gln,
        lieferbeginn_dat = %lieferbeginn_datum,
        "maloid.lieferbeginn.fortsetzen: resolved tx_id — dispatching PID 55001"
    );

    dispatch_lf_anmeldung(state, &synthetic_payload, 55001, "lieferbeginn_datum").await
}

/// Return the current BDEW format-version `WorkflowId` for `gpke-lf-anmeldung`.
///
/// Uses the most recent format version from the compiled `edi-energy` profile
/// registry — the same strategy as the AS4 ingest layer.
fn current_workflow_id() -> WorkflowId {
    // Prefer the latest compiled FV.  Falls back to a known good FV if
    // the registry is somehow empty (should never happen in production).
    WorkflowId::new(
        mako_gpke::lf_anmeldung::WORKFLOW_NAME,
        latest_format_version(),
    )
}

/// Return the latest BDEW format version known to the compiled `edi-energy` registry.
fn latest_format_version() -> mako_engine::version::FormatVersion {
    edi_energy::registry::ReleaseRegistry::global()
        .format_versions()
        .into_iter()
        .filter_map(|s| mako_engine::version::FormatVersion::parse(&s).ok())
        .max_by(|a, b| a.as_str().cmp(b.as_str()))
        .unwrap_or_else(|| {
            mako_engine::version::FormatVersion::parse("FV2025-10-01")
                .expect("fallback FV is valid")
        })
}

// ── Phase 3 — Response command dispatchers ────────────────────────────────────
//
// These dispatchers look up an active process by MaLo / MeLo business key
// using the `ProcessRegistry` correlated index and route the ERP response
// command into the appropriate workflow.

/// Look up the single active process for `business_key` under `workflow_name`
/// and execute `make_command` against it.
///
/// Returns `ProcessNotFound` when no active process exists and `AmbiguousProcess`
/// when more than one active process is found (data integrity violation).
async fn dispatch_to_process<W, F>(
    state: &CommandsApiState,
    business_key: &str,
    workflow_name: &'static str,
    make_command: F,
) -> Result<DispatchOutcome, DispatchError>
where
    W: mako_engine::workflow::Workflow,
    W::Command: mako_engine::workflow::CommandPayload + Clone,
    W::State: Default + serde::Serialize,
    F: FnOnce() -> W::Command,
{
    // ── Lookup active process(es) for business key ────────────────────────────
    let registry = state.store.as_process_registry();
    let identities = registry
        .lookup_correlated(state.tenant_id, business_key)
        .await
        .map_err(|e| {
            DispatchError::Engine(mako_engine::error::EngineError::store(e.to_string()))
        })?;

    // Filter to identities belonging to the target workflow.
    let matching: Vec<_> = identities
        .into_iter()
        .filter(|id| id.workflow_id.name.as_ref() == workflow_name)
        .collect();

    let identity = match matching.len() {
        0 => {
            return Err(DispatchError::ProcessNotFound {
                business_key: business_key.to_owned(),
                workflow_name,
            });
        }
        1 => matching.into_iter().next().expect("len == 1"),
        n => {
            return Err(DispatchError::AmbiguousProcess {
                business_key: business_key.to_owned(),
                count: n,
            });
        }
    };

    let process_id = identity.process_id;
    let process = mako_engine::process::Process::<
        W,
        Arc<mako_engine::store_slatedb::SlateDbStore>,
    >::from_identity(Arc::clone(&state.store), identity);

    let domain_cmd = make_command();
    process
        .execute_and_enqueue_with_snapshot_and_retry(
            domain_cmd,
            3,
            &state.snapshot_store,
            state.snapshot_interval,
        )
        .await?;

    Ok(DispatchOutcome::Dispatched { process_id })
}

/// Dispatch a GPKE NB→LF Antwort (Bestätigung or Ablehnung) to an existing
/// `GpkeLfAnmeldungWorkflow` process looked up by `malo_id`.
///
/// Called for `gpke.lieferbeginn.bestaetigen`, `gpke.lieferbeginn.ablehnen`,
/// `gpke.lieferende.bestaetigen`, `gpke.lieferende.ablehnen`.
async fn dispatch_lf_antwort(
    state: &CommandsApiState,
    payload: &serde_json::Value,
    accepted: bool,
    response_pid_code: u32,
) -> Result<DispatchOutcome, DispatchError> {
    let malo_id = payload
        .get("malo_id")
        .and_then(|v| v.as_str())
        .ok_or_else(|| DispatchError::InvalidPayload("payload must contain \"malo_id\"".into()))?
        .to_owned();

    let reason = payload
        .get("reason")
        .and_then(|v| v.as_str())
        .map(str::to_owned);

    let response_ref = payload
        .get("response_ref")
        .and_then(|v| v.as_str())
        .map(MessageRef::new)
        .unwrap_or_else(|| MessageRef::new(""));

    let response_pid =
        Pruefidentifikator::new(response_pid_code).map_err(DispatchError::InvalidPayload)?;

    dispatch_to_process::<GpkeLfAnmeldungWorkflow, _>(
        state,
        &malo_id,
        mako_gpke::lf_anmeldung::WORKFLOW_NAME,
        || LfAnmeldungCommand::HandleAntwort {
            response_pid,
            accepted,
            reason: reason.clone(),
            response_ref: response_ref.clone(),
        },
    )
    .await
}

/// Dispatch `LfAnmeldungCommand::Activate` to an existing `GpkeLfAnmeldungWorkflow`
/// process looked up by `malo_id`.
///
/// Called for `gpke.lieferbeginn.aktivieren`.
async fn dispatch_lf_activate(
    state: &CommandsApiState,
    payload: &serde_json::Value,
) -> Result<DispatchOutcome, DispatchError> {
    let malo_id = payload
        .get("malo_id")
        .and_then(|v| v.as_str())
        .ok_or_else(|| DispatchError::InvalidPayload("payload must contain \"malo_id\"".into()))?
        .to_owned();

    dispatch_to_process::<GpkeLfAnmeldungWorkflow, _>(
        state,
        &malo_id,
        mako_gpke::lf_anmeldung::WORKFLOW_NAME,
        || LfAnmeldungCommand::Activate,
    )
    .await
}

/// Dispatch a GeLi Gas GNB→LFG Antwort to an existing
/// `GeliGasSupplierChangeWorkflow` process looked up by gas `malo_id`.
///
/// Called for `geli.lieferbeginn.bestaetigen`, `geli.lieferbeginn.ablehnen`,
/// `geli.lieferende.bestaetigen`, `geli.lieferende.ablehnen`.
async fn dispatch_geli_gas_antwort(
    state: &CommandsApiState,
    payload: &serde_json::Value,
    positive: bool,
    response_pid_code: u32,
) -> Result<DispatchOutcome, DispatchError> {
    let malo_id = payload
        .get("malo_id")
        .and_then(|v| v.as_str())
        .ok_or_else(|| {
            DispatchError::InvalidPayload(
                "payload must contain \"malo_id\" (gas Marktlokations-ID)".into(),
            )
        })?
        .to_owned();

    let reason = payload
        .get("reason")
        .and_then(|v| v.as_str())
        .map(str::to_owned);

    // GeLi Gas uses DispatchAperak (not HandleAntwort) — the GNB dispatches
    // an APERAK to the LFG, which is the positive/negative response.
    let _ = response_pid_code; // recorded in audit log, not in DispatchAperak
    dispatch_to_process::<GeliGasSupplierChangeWorkflow, _>(
        state,
        &malo_id,
        mako_geli_gas::WORKFLOW_NAME,
        move || GasSupplierChangeCommand::DispatchAperak {
            positive,
            reason: reason.clone(),
        },
    )
    .await
}

/// Dispatch `DeviceChangeCommand::DispatchAperak` to an existing
/// `WimDeviceChangeWorkflow` process looked up by `melo_id`.
///
/// Called for `wim.geraetewechsel.bestaetigen` and `wim.geraetewechsel.ablehnen`.
async fn dispatch_wim_aperak(
    state: &CommandsApiState,
    payload: &serde_json::Value,
    positive: bool,
) -> Result<DispatchOutcome, DispatchError> {
    let melo_id = payload
        .get("melo_id")
        .and_then(|v| v.as_str())
        .ok_or_else(|| {
            DispatchError::InvalidPayload(
                "payload must contain \"melo_id\" (Messlokations-ID)".into(),
            )
        })?
        .to_owned();

    let reason = payload
        .get("reason")
        .and_then(|v| v.as_str())
        .map(str::to_owned);

    // WiM uses melo_id as the business key (not malo_id).
    dispatch_to_process::<WimDeviceChangeWorkflow, _>(
        state,
        &melo_id,
        mako_wim::WORKFLOW_NAME,
        move || DeviceChangeCommand::DispatchAperak {
            positive,
            reason: reason.clone(),
        },
    )
    .await
}

/// Dispatch `wim.steuerungsauftrag.bestaetigen` / `.ablehnen` to an existing
/// `WimSteuerungsauftragWorkflow` process looked up by `tx_id`.
///
/// The `tx_id` is the transaction ID that arrived in the original
/// `POST /steuerbefehl/konfiguration/` or `/initialZustand/` REST request.
/// It is the natural business key for the process registry.
async fn dispatch_steuerungsauftrag_endantwort(
    state: &CommandsApiState,
    payload: &serde_json::Value,
    positive: bool,
) -> Result<DispatchOutcome, DispatchError> {
    let tx_id = payload
        .get("tx_id")
        .and_then(|v| v.as_str())
        .ok_or_else(|| {
            DispatchError::InvalidPayload(
                "payload must contain \"tx_id\" (transaction ID from the original \
             konfiguration/initialZustand request)"
                    .into(),
            )
        })?
        .to_owned();

    let reason = payload
        .get("reason")
        .and_then(|v| v.as_str())
        .map(str::to_owned);

    if positive {
        let reference_id = payload
            .get("reference_id")
            .and_then(|v| v.as_str())
            .map(str::to_owned)
            .unwrap_or_else(|| uuid::Uuid::new_v4().to_string());

        dispatch_to_process::<WimSteuerungsauftragWorkflow, _>(
            state,
            &tx_id,
            mako_wim::steuerungsauftrag::WORKFLOW_NAME,
            move || SteuerungsauftragCommand::SendEndantwortPositiv {
                reference_id: reference_id.clone(),
            },
        )
        .await
    } else {
        dispatch_to_process::<WimSteuerungsauftragWorkflow, _>(
            state,
            &tx_id,
            mako_wim::steuerungsauftrag::WORKFLOW_NAME,
            move || SteuerungsauftragCommand::SendEndantwortNegativ {
                reason: reason.clone(),
            },
        )
        .await
    }
}

// ── IFTSTA REST command dispatch helpers ──────────────────────────────────────

/// Dispatch a `gpke.vollzugsmeldung.empfangen` REST command.
///
/// Constructs [`SupplierChangeCommand::ReceiveVollzugsmeldung`] and executes
/// it on the existing `gpke-supplier-change` process identified by
/// `stream_id` in the payload.
///
/// Expected payload fields:
/// - `stream_id`     — Process stream ID (UUID)
/// - `pid`           — IFTSTA Prüfidentifikator (21024–21033)
/// - `sender_gln`    — Sender party GLN
/// - `receiver_gln`  — Receiver party GLN
/// - `message_ref`   — EDIFACT message reference string
async fn dispatch_gpke_iftsta(
    state: &CommandsApiState,
    payload: &serde_json::Value,
) -> Result<DispatchOutcome, DispatchError> {
    let stream_id = payload
        .get("stream_id")
        .and_then(|v| v.as_str())
        .ok_or_else(|| DispatchError::InvalidPayload("\"stream_id\" is required".into()))?
        .to_owned();
    let pid_code = payload
        .get("pid")
        .and_then(|v| v.as_u64())
        .map(|n| n as u32)
        .ok_or_else(|| DispatchError::InvalidPayload("\"pid\" (u32) is required".into()))?;
    let pid = Pruefidentifikator::new(pid_code).map_err(DispatchError::InvalidPayload)?;
    let sender = MarktpartnerCode::new(
        payload
            .get("sender_gln")
            .and_then(|v| v.as_str())
            .unwrap_or(""),
    );
    let receiver = MarktpartnerCode::new(
        payload
            .get("receiver_gln")
            .and_then(|v| v.as_str())
            .unwrap_or(""),
    );
    let message_ref = MessageRef::new(
        payload
            .get("message_ref")
            .and_then(|v| v.as_str())
            .unwrap_or(""),
    );
    dispatch_to_process::<GpkeSupplierChangeWorkflow, _>(
        state,
        &stream_id,
        "gpke-supplier-change",
        move || SupplierChangeCommand::ReceiveVollzugsmeldung {
            pid,
            sender,
            receiver,
            message_ref,
            // IFTSTA arrives via ERP REST, not AS4; no EDIFACT AHB profile applies.
            // The ERP operator is responsible for providing a conformant IFTSTA payload.
            validation_passed: true,
            validation_errors: vec![],
        },
    )
    .await
}

/// Dispatch a `wim.iftsta.empfangen` REST command.
///
/// Constructs [`DeviceChangeCommand::ReceiveIftsta`] and executes it on the
/// existing `wim-device-change` process identified by `stream_id` in the payload.
///
/// Expected payload fields: `stream_id`, `pid`, `sender_gln`, `receiver_gln`,
/// `message_ref`.
async fn dispatch_wim_iftsta(
    state: &CommandsApiState,
    payload: &serde_json::Value,
) -> Result<DispatchOutcome, DispatchError> {
    let stream_id = payload
        .get("stream_id")
        .and_then(|v| v.as_str())
        .ok_or_else(|| DispatchError::InvalidPayload("\"stream_id\" is required".into()))?
        .to_owned();
    let pid_code = payload
        .get("pid")
        .and_then(|v| v.as_u64())
        .map(|n| n as u32)
        .ok_or_else(|| DispatchError::InvalidPayload("\"pid\" (u32) is required".into()))?;
    let pid = Pruefidentifikator::new(pid_code).map_err(DispatchError::InvalidPayload)?;
    let sender = MarktpartnerCode::new(
        payload
            .get("sender_gln")
            .and_then(|v| v.as_str())
            .unwrap_or(""),
    );
    let receiver = MarktpartnerCode::new(
        payload
            .get("receiver_gln")
            .and_then(|v| v.as_str())
            .unwrap_or(""),
    );
    let message_ref = MessageRef::new(
        payload
            .get("message_ref")
            .and_then(|v| v.as_str())
            .unwrap_or(""),
    );
    dispatch_to_process::<WimDeviceChangeWorkflow, _>(
        state,
        &stream_id,
        "wim-device-change",
        move || DeviceChangeCommand::ReceiveIftsta {
            pid,
            sender,
            receiver,
            message_ref,
            // IFTSTA arrives via ERP REST, not AS4; no EDIFACT AHB profile applies.
            // The ERP operator is responsible for providing a conformant IFTSTA payload.
            validation_passed: true,
            validation_errors: vec![],
        },
    )
    .await
}

/// Dispatch `mabis.iftsta.empfangen` or `mabis.datenstatus.empfangen`.
///
/// When `is_datenstatus = true` (`mabis.datenstatus.empfangen`), the payload
/// must include `data_status` (`"abrechnungsdaten"` / `"abgerechnete_daten"` /
/// `"abgerechnete_daten_kbka"`). The PID is forced to 21004.
///
/// When `is_datenstatus = false` (`mabis.iftsta.empfangen`), `data_status` is
/// `None` and `pid` must be a non-21004 MaBiS IFTSTA PID from
/// [`MABIS_IFTSTA_PIDS`].
///
/// Expected payload fields: `stream_id`, `pid` (optional for datenstatus),
/// `sender_gln`, `receiver_gln`, `message_ref`. For datenstatus: `data_status`.
async fn dispatch_mabis_iftsta(
    state: &CommandsApiState,
    payload: &serde_json::Value,
    is_datenstatus: bool,
) -> Result<DispatchOutcome, DispatchError> {
    let stream_id = payload
        .get("stream_id")
        .and_then(|v| v.as_str())
        .ok_or_else(|| DispatchError::InvalidPayload("\"stream_id\" is required".into()))?
        .to_owned();
    let pid_code = if is_datenstatus {
        IFTSTA_DATENSTATUS_PID
    } else {
        let code = payload
            .get("pid")
            .and_then(|v| v.as_u64())
            .map(|n| n as u32)
            .ok_or_else(|| DispatchError::InvalidPayload("\"pid\" (u32) is required".into()))?;
        if !MABIS_IFTSTA_PIDS.contains(&code) || code == IFTSTA_DATENSTATUS_PID {
            return Err(DispatchError::InvalidPayload(format!(
                "pid {code} is not a valid non-datenstatus MaBiS IFTSTA PID; \
                 use mabis.datenstatus.empfangen for PID {IFTSTA_DATENSTATUS_PID}"
            )));
        }
        code
    };
    let pid = Pruefidentifikator::new(pid_code).map_err(DispatchError::InvalidPayload)?;
    let sender = MarktpartnerCode::new(
        payload
            .get("sender_gln")
            .and_then(|v| v.as_str())
            .unwrap_or(""),
    );
    let receiver = MarktpartnerCode::new(
        payload
            .get("receiver_gln")
            .and_then(|v| v.as_str())
            .unwrap_or(""),
    );
    let message_ref = MessageRef::new(
        payload
            .get("message_ref")
            .and_then(|v| v.as_str())
            .unwrap_or(""),
    );
    let data_status = if is_datenstatus {
        let code = payload
            .get("data_status")
            .and_then(|v| v.as_str())
            .ok_or_else(|| {
                DispatchError::InvalidPayload(
                    "\"data_status\" is required for mabis.datenstatus.empfangen".into(),
                )
            })?;
        let ds = match code {
            "abrechnungsdaten" => DataStatus::Abrechnungsdaten,
            "abgerechnete_daten" => DataStatus::AbgerechtneteDaten,
            "abgerechnete_daten_kbka" => DataStatus::AbgerechtneteDatenKbka,
            other => {
                return Err(DispatchError::InvalidPayload(format!(
                    "unknown data_status \"{other}\"; valid values: \
                     abrechnungsdaten, abgerechnete_daten, abgerechnete_daten_kbka"
                )));
            }
        };
        Some(ds)
    } else {
        None
    };
    dispatch_to_process::<MabisBillingWorkflow, _>(state, &stream_id, "mabis-billing", move || {
        BillingCommand::ReceiveIftsta {
            pid,
            sender,
            receiver,
            message_ref,
            // IFTSTA arrives via ERP REST, not AS4; no EDIFACT AHB profile applies.
            // The ERP operator is responsible for providing a conformant IFTSTA payload.
            validation_passed: true,
            validation_errors: vec![],
            data_status,
        }
    })
    .await
}

// ── Command registry ──────────────────────────────────────────────────────────

/// Errors from [`validate_command`].
#[derive(Debug)]
enum CommandError {
    /// Command name is not in the registry.
    UnknownCommand,
    /// Multi-role command but no `marktrolle` was supplied.
    MarktrolleRequired,
    /// Asserted `marktrolle` is not in the command's permitted set.
    RoleNotPermitted,
    /// The effective role is not in [`CommandsApiState::configured_marktrollen`].
    RoleNotConfigured,
}

/// Resolve and validate the effective Marktrolle for a command.
///
/// ## Resolution rules
///
/// - **Single-role commands** (`permitted.len() == 1`): the role is inferred
///   from the registry.  Any `asserted` marktrolle in the request is ignored.
/// - **Multi-role commands** (`permitted.len() > 1`): `asserted` must be `Some`
///   and must be in the permitted set — the engine cannot infer which hat to wear.
///
/// ## Instance configuration
///
/// After resolving the effective role the function checks it against `configured`
/// (the startup `--marktrollen` list).  If `configured` is empty the check is
/// skipped (permissive / backward-compatible mode).
///
/// Returns the resolved Marktrolle string on success.
fn validate_command(
    command: &str,
    asserted: Option<&str>,
    configured: &[String],
) -> Result<String, CommandError> {
    // Registry: command → permitted Marktrollen (upper-case).
    //
    // Sources:
    // - BDEW GPKE AHB (BK6-22-024, LFW24)
    // - BDEW GeLi Gas AHB (BK7)
    // - BDEW WiM AHB (BK6-18-032)
    // - BDEW MABIS AHB
    const REGISTRY: &[(&str, &[&str])] = &[
        // ── GPKE Lieferbeginn / Lieferende (electricity) ──────────────────────
        // LF (new supplier) sends Anmeldung to NB — PID 55001
        ("gpke.lieferbeginn.anmelden", &["LF"]),
        // NB accepts or rejects Lieferbeginn Anmeldung — PID 55003/55004
        ("gpke.lieferbeginn.bestaetigen", &["NB"]),
        // LF (old supplier) sends Lieferende Anmeldung to NB — PID 55002
        ("gpke.lieferende.anmelden", &["LF"]),
        // NB accepts or rejects Lieferende Anmeldung — PID 55005/55006
        ("gpke.lieferende.bestaetigen", &["NB"]),
        // LF sends Kündigung Lieferbeginn to old LFA — PID 55016
        ("gpke.kuendigung.anmelden", &["LF"]),
        // LF confirms Sperrung execution to NB (ORDERS 17115/17117 — no outbound UTILMD PID)
        ("gpke.sperrung.bestaetigen", &["LF"]),
        // NB (recipient) settles a Netznutzungsabrechnung INVOIC — PIDs 31001/31002
        ("gpke.abrechnung.annehmen", &["NB"]),
        // NB disputes a Netznutzungsabrechnung INVOIC
        ("gpke.abrechnung.ablehnen", &["NB"]),
        // ── GeLi Gas Lieferbeginn / Lieferende (gas) ─────────────────────────
        // LFG (new gas supplier) sends Anmeldung to GNB — PID 44001
        ("geli.lieferbeginn.anmelden", &["LFG"]),
        // GNB accepts or rejects gas Lieferbeginn — PID 44003/44004
        ("geli.lieferbeginn.bestaetigen", &["GNB"]),
        // LFG sends gas Lieferende Anmeldung to GNB — PID 44002
        ("geli.lieferende.anmelden", &["LFG"]),
        // GNB accepts or rejects gas Lieferende — PID 44005/44006
        ("geli.lieferende.bestaetigen", &["GNB"]),
        // ── WiM Messstellenbetrieb ───────────────────────────────────────────────
        // NB or MSB initiates a meter-device change — PIDs 55039, 55042, 55051, 55168
        ("wim.geraetewechsel.beauftragen", &["NB", "MSB"]),
        // MSB confirms the physical device swap — PIDs 55039, 55042, 55051, 55168
        ("wim.geraetewechsel.bestaetigen", &["MSB"]),
        // ── WiM Steuerungsauftrag (REST Control Measures ──────────────
        // MSB sends final positive response to NB/LF
        ("wim.steuerungsauftrag.bestaetigen", &["MSB"]),
        // MSB sends final negative response to NB/LF
        ("wim.steuerungsauftrag.ablehnen", &["MSB"]),
        // ── MABIS Bilanzkreisabrechnung ────────────────────────────────────────
        // BKV opens a billing period — PID 13001
        ("mabis.abrechnung.einleiten", &["BKV"]),
        // BKV submits pre-aggregated meter data — PID 13001
        ("mabis.abrechnung.daten-einreichen", &["BKV"]),
        // BKV or ÜNB marks the billing period as settled — PID 13001
        ("mabis.abrechnung.begleichen", &["BKV", "ÜNB"]),
        // ── IFTSTA status messages (REST replay / manual override) ────────────
        // GPKE Vollzugsmeldung received via REST — PIDs 21024–21033
        ("gpke.vollzugsmeldung.empfangen", &["NB", "LFN", "LFA"]),
        // WiM IFTSTA status message received via REST — PIDs 21009–21018
        ("wim.iftsta.empfangen", &["NB", "MSB"]),
        // MABIS IFTSTA informational status received via REST — PIDs 21000–21003, 21005, 21007
        ("mabis.iftsta.empfangen", &["BKV", "NB", "ÜNB", "BIKO"]),
        // MABIS Datenstatus received via REST — PID 21004 (BIKO → BKV/NB)
        ("mabis.datenstatus.empfangen", &["BKV", "NB", "BIKO"]),
    ];

    let permitted = REGISTRY
        .iter()
        .find(|(cmd, _)| *cmd == command)
        .map(|(_, roles)| *roles)
        .ok_or(CommandError::UnknownCommand)?;

    // Resolve the effective Marktrolle.
    let effective: &str = if permitted.len() == 1 {
        // Single-role command — role is fully implied by the command name.
        // Ignore any asserted marktrolle to avoid spurious errors from
        // misconfigured ERP connectors that always send a fixed role.
        permitted[0]
    } else {
        // Multi-role command — the ERP must tell us which hat it is wearing.
        let r = asserted.ok_or(CommandError::MarktrolleRequired)?;
        if !permitted.contains(&r) {
            return Err(CommandError::RoleNotPermitted);
        }
        r
    };

    // Cross-check against instance configuration.
    // Empty configured list → permissive / backward-compatible mode (no check).
    if !configured.is_empty() && !configured.iter().any(|r| r.as_str() == effective) {
        return Err(CommandError::RoleNotConfigured);
    }

    Ok(effective.to_owned())
}

// ── Bearer token extraction ───────────────────────────────────────────────────

fn extract_bearer(headers: &axum::http::HeaderMap) -> Option<String> {
    headers
        .get(axum::http::header::AUTHORIZATION)
        .and_then(|v| v.to_str().ok())
        .and_then(|v| v.strip_prefix("Bearer "))
        .map(str::to_owned)
}

// ── Tests ─────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    fn roles(r: &[&str]) -> Vec<String> {
        r.iter().map(|s| s.to_string()).collect()
    }
    /// Permissive mode: no `--marktrollen` configured → skip instance check.
    fn any() -> Vec<String> {
        vec![]
    }

    // ── Single-role commands ──────────────────────────────────────────────────

    #[test]
    fn single_role_inferred_without_marktrolle() {
        let role = validate_command("gpke.lieferbeginn.anmelden", None, &any()).unwrap();
        assert_eq!(role, "LF");
    }

    #[test]
    fn single_role_asserted_marktrolle_is_ignored() {
        // For single-role commands the asserted marktrolle is always ignored.
        // An ERP connector that always sends marktrolle should not be rejected.
        let role = validate_command("gpke.lieferbeginn.anmelden", Some("NB"), &any()).unwrap();
        assert_eq!(role, "LF"); // canonical role, not what ERP asserted
    }

    #[test]
    fn nb_role_resolved_for_bestaetigen() {
        let role = validate_command("gpke.lieferbeginn.bestaetigen", None, &any()).unwrap();
        assert_eq!(role, "NB");
    }

    #[test]
    fn gnb_role_resolved_for_gas_bestaetigen() {
        let role = validate_command("geli.lieferbeginn.bestaetigen", None, &any()).unwrap();
        assert_eq!(role, "GNB");
    }

    #[test]
    fn lfg_role_resolved_for_gas_lieferbeginn() {
        let role = validate_command("geli.lieferbeginn.anmelden", None, &any()).unwrap();
        assert_eq!(role, "LFG");
    }

    // ── Instance configuration enforcement ───────────────────────────────────

    #[test]
    fn lf_instance_may_issue_lf_commands() {
        let lf = roles(&["LF"]);
        assert!(validate_command("gpke.lieferbeginn.anmelden", None, &lf).is_ok());
        assert!(validate_command("gpke.lieferende.anmelden", None, &lf).is_ok());
        assert!(validate_command("gpke.kuendigung.anmelden", None, &lf).is_ok());
    }

    #[test]
    fn nb_instance_may_not_issue_lf_command() {
        // Resolves to LF; NB is not configured → RoleNotConfigured.
        let nb = roles(&["NB"]);
        assert!(validate_command("gpke.lieferbeginn.anmelden", None, &nb).is_err());
    }

    #[test]
    fn lf_instance_may_not_issue_nb_command() {
        // Resolves to NB; LF is not configured for NB role.
        let lf = roles(&["LF"]);
        assert!(validate_command("gpke.lieferbeginn.bestaetigen", None, &lf).is_err());
    }

    #[test]
    fn dual_fuel_instance_permits_strom_and_gas() {
        let lf_lfg = roles(&["LF", "LFG"]);
        assert!(validate_command("gpke.lieferbeginn.anmelden", None, &lf_lfg).is_ok());
        assert!(validate_command("geli.lieferbeginn.anmelden", None, &lf_lfg).is_ok());
    }

    #[test]
    fn strom_only_instance_blocks_gas_commands() {
        let lf = roles(&["LF"]);
        assert!(validate_command("geli.lieferbeginn.anmelden", None, &lf).is_err());
    }

    #[test]
    fn gas_only_instance_blocks_strom_commands() {
        let lfg = roles(&["LFG"]);
        assert!(validate_command("gpke.lieferbeginn.anmelden", None, &lfg).is_err());
    }

    // ── Multi-role commands ───────────────────────────────────────────────────

    #[test]
    fn multi_role_requires_marktrolle() {
        // wim.geraetewechsel.beauftragen → NB or MSB; no marktrolle → err.
        assert!(validate_command("wim.geraetewechsel.beauftragen", None, &any()).is_err());
    }

    #[test]
    fn nb_may_initiate_geraetewechsel() {
        assert!(validate_command("wim.geraetewechsel.beauftragen", Some("NB"), &any()).is_ok());
    }

    #[test]
    fn msb_may_initiate_geraetewechsel() {
        assert!(validate_command("wim.geraetewechsel.beauftragen", Some("MSB"), &any()).is_ok());
    }

    #[test]
    fn lf_may_not_initiate_geraetewechsel() {
        // LF is not in the permitted set → RoleNotPermitted.
        assert!(validate_command("wim.geraetewechsel.beauftragen", Some("LF"), &any()).is_err());
    }

    #[test]
    fn nb_msb_instance_permits_both_wim_roles() {
        let nb_msb = roles(&["NB", "MSB"]);
        assert!(validate_command("wim.geraetewechsel.beauftragen", Some("NB"), &nb_msb).is_ok());
        assert!(validate_command("wim.geraetewechsel.beauftragen", Some("MSB"), &nb_msb).is_ok());
    }

    #[test]
    fn nb_only_instance_may_not_act_as_msb() {
        let nb = roles(&["NB"]);
        // MSB is permitted by the registry but not configured on this instance.
        assert!(validate_command("wim.geraetewechsel.beauftragen", Some("MSB"), &nb).is_err());
    }

    // ── BKV / ÜNB ────────────────────────────────────────────────────────────

    #[test]
    fn bkv_single_role_commands_infer_role() {
        // einleiten and daten-einreichen are single-role (BKV only).
        assert_eq!(
            validate_command("mabis.abrechnung.einleiten", None, &any()).unwrap(),
            "BKV"
        );
        assert_eq!(
            validate_command("mabis.abrechnung.daten-einreichen", None, &any()).unwrap(),
            "BKV"
        );
    }

    #[test]
    fn begleichen_is_multi_role_bkv_and_uenb() {
        // begleichen permits BKV and ÜNB → marktrolle required.
        assert!(validate_command("mabis.abrechnung.begleichen", Some("BKV"), &any()).is_ok());
        assert!(validate_command("mabis.abrechnung.begleichen", Some("ÜNB"), &any()).is_ok());
        assert!(validate_command("mabis.abrechnung.begleichen", None, &any()).is_err());
    }

    #[test]
    fn uenb_instance_may_not_initiate_mabis() {
        // einleiten resolves to BKV; ÜNB instance not configured for BKV.
        let uenb = roles(&["ÜNB"]);
        assert!(validate_command("mabis.abrechnung.einleiten", None, &uenb).is_err());
    }

    // ── Unknown command ───────────────────────────────────────────────────────

    #[test]
    fn unknown_command_is_rejected() {
        assert!(validate_command("gpke.nonexistent.action", None, &any()).is_err());
    }

    // ── Bearer token extraction ───────────────────────────────────────────────

    #[test]
    fn extract_bearer_parses_header() {
        let mut hm = axum::http::HeaderMap::new();
        hm.insert(
            axum::http::header::AUTHORIZATION,
            axum::http::HeaderValue::from_static("Bearer my-secret-token"),
        );
        assert_eq!(extract_bearer(&hm), Some("my-secret-token".to_owned()));
    }
}
