//! Embeds the profiles under `profiles/<type>/<fv>/` and emits two things
//! into `OUT_DIR/profiles.rs`:
//!
//! - `register_profiles(&mut Vec<&'static Profile>)`, one lazily parsed
//!   `static` per profile directory, gated on the message type's feature;
//! - the `releases` module with one accessor per profile
//!   (`utilmd_fv20261001()` → the `Release` it carries), so a caller names a
//!   Formatversion by identifier and a removed profile is a compile error.
//!
//! Also collapses "is any message type compiled in?" into the `any_message`
//! cfg, which a dozen items across the crate are gated on.

use std::fmt::Write as _;
use std::path::Path;

const MESSAGE_FEATURES: &[&str] = &[
    "utilmd", "mscons", "aperak", "contrl", "invoic", "remadv", "orders", "iftsta", "insrpt",
    "reqote", "partin", "ordchg", "ordrsp", "quotes", "comdis", "pricat", "utilts",
];

fn main() {
    println!("cargo::rerun-if-changed=build.rs");
    println!("cargo::rerun-if-changed=profiles");
    println!("cargo::rustc-check-cfg=cfg(any_message)");

    let any_enabled = MESSAGE_FEATURES.iter().any(|f| {
        std::env::var_os(format!(
            "CARGO_FEATURE_{}",
            f.to_uppercase().replace('-', "_")
        ))
        .is_some()
    });
    if any_enabled {
        println!("cargo::rustc-cfg=any_message");
    }

    let manifest_dir = std::env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR");
    let profiles = Path::new(&manifest_dir).join("profiles");
    let mut entries: Vec<(String, String)> = Vec::new(); // (message type dir, fv dir)
    for ty in read_sorted(&profiles) {
        if !ty.is_dir()
            || !MESSAGE_FEATURES.contains(&ty.file_name().and_then(|n| n.to_str()).unwrap_or(""))
        {
            continue;
        }
        for fv in read_sorted(&ty) {
            if fv.is_dir() && fv.join("mig.json").is_file() && fv.join("ahb.json").is_file() {
                entries.push((
                    ty.file_name().unwrap().to_string_lossy().into_owned(),
                    fv.file_name().unwrap().to_string_lossy().into_owned(),
                ));
            }
        }
    }

    let mut out = String::new();
    writeln!(
        out,
        "// Generated by build.rs from profiles/ — do not edit."
    )
    .unwrap();
    for (ty, fv) in &entries {
        let ident = format!("{ty}_{fv}").to_uppercase();
        writeln!(
            out,
            "#[cfg(feature = \"{ty}\")]\nstatic {ident}: std::sync::LazyLock<crate::profile::Profile> = std::sync::LazyLock::new(|| {{\n    crate::profile::Profile::from_json(\n        include_str!(concat!(env!(\"CARGO_MANIFEST_DIR\"), \"/profiles/{ty}/{fv}/mig.json\")),\n        include_str!(concat!(env!(\"CARGO_MANIFEST_DIR\"), \"/profiles/{ty}/{fv}/ahb.json\")),\n    )\n    .expect(\"the committed profile {ty}/{fv} loads\")\n}});"
        )
        .unwrap();
    }
    writeln!(out, "\n/// Register every embedded profile.").unwrap();
    writeln!(
        out,
        "pub(crate) fn register_profiles(profiles: &mut Vec<&'static crate::profile::Profile>) {{"
    )
    .unwrap();
    writeln!(out, "    let _ = &profiles;").unwrap();
    for (ty, fv) in &entries {
        let ident = format!("{ty}_{fv}").to_uppercase();
        writeln!(
            out,
            "    #[cfg(feature = \"{ty}\")]\n    profiles.push(&*{ident});"
        )
        .unwrap();
    }
    writeln!(out, "}}\n").unwrap();
    writeln!(
        out,
        "/// The Formatversionen this build embeds, one accessor per profile directory."
    )
    .unwrap();
    writeln!(out, "pub mod releases {{").unwrap();
    for (ty, fv) in &entries {
        let ident = format!("{ty}_{fv}").to_uppercase();
        writeln!(
            out,
            "    /// `{ty}/{fv}`.\n    #[cfg(feature = \"{ty}\")]\n    #[must_use]\n    pub fn {ty}_{fv}() -> &'static crate::Release {{\n        super::{ident}.release()\n    }}"
        )
        .unwrap();
    }
    writeln!(out, "}}").unwrap();

    let dest = Path::new(&std::env::var("OUT_DIR").expect("OUT_DIR")).join("profiles.rs");
    std::fs::write(dest, out).expect("write profiles.rs");
}

fn read_sorted(dir: &Path) -> Vec<std::path::PathBuf> {
    let mut v: Vec<_> = std::fs::read_dir(dir)
        .map(|rd| rd.filter_map(Result::ok).map(|e| e.path()).collect())
        .unwrap_or_default();
    v.sort();
    v
}
